### ISSUE TITLE
Execution with progressbar (slower) vs execution w/o progressbar (faster) 

### ISSUE THREAD

**Issue by Tset-Noitamotua** [WoLpH/python-progressbar#100]
**DISCLAIMER:** I am a python/programming noob :smile:  

#### Description

I noticed a longer execution time when running the same code with progressbar vs. running w/o progressbar.
Especially the widget `progressbar.Timer()` more than doubles execution time in my case.

Is that normal? Is there a way to get more accurate results?

#### Code

You will find the code I used here: [lesson_122_lists_del_vs_remove.py][1]

Console output of iterative execution
![image](https://cloud.githubusercontent.com/assets/5635462/23795113/1325f9b4-0594-11e7-8a39-7f1a1e561dd2.png)

[1]: https://github.com/Tset-Noitamotua/_learnpython/blob/master/google-python-class/lesson_122_lists_del_vs_remove.py

#### Versions

- Python version: 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]
- Python distribution/environment: CPython
- Operating System: Windows 7 (64bit)
- Package version: 3.12.0

**Comment by WoLpH** [comment]
With very simple loops such as this one the overhead can indeed be quite significant. As soon as you add a `progressbar.Timer()` the progress bar will have to fetch the system time for every update. Since you are executing this `2000000` times it will definitely have an impact.

I would recommend updating the progress bar less often, you won't notice the difference and the impact will be far smaller. It seems like this is something I should actually add as a feature, but for the time being.

If you modify your code to look something like this it will be far better:
```
widgets = [progressbar.Percentage(), progressbar.Bar(), progressbar.Timer()]
bar = progressbar.ProgressBar(widgets=widgets, max_value=range_count).start()
timer_start = time.time()
for i in range(range_count):
    values = [x for x in range(100)]
    del values[95]
    # Only update once for every 10000 values
    if i % 10000 == 0:
        bar.update(i)
bar.finish()
timer_stop = time.time()
print('\ndel - done in %i s' %(timer_stop - timer_start))
```

**Comment by Tset-Noitamotua** [comment]
Many thanks for your suggestion. I will give it a try.

If you like, you can also try this file: [progressbar_examples.py][1]. It has almost all your example bars combined with my `del` and `remove()` examples. (I have not implemented your suggestion there yet)

[1]: https://github.com/Tset-Noitamotua/_learnpython/blob/master/google-python-class/exercises/progressbar_examples.py

**Comment by WoLpH** [comment]
I've just created a new version which is a lot lighter for these type of use-cases. Can you install the latest development version?
```
pip install -e 'git+git@github.com:WoLpH/python-progressbar.git'
```

**Comment by maranov** [comment]
Hi WoLpH, I've had a similar issue of too frequent updates. Tried 2c9220433c175ebf581a7992653846d2f5298d52 and it's quite better. Thanks.

Runtime (mm:ss):
* No progressbar: 1:18
* 3.12.0: 1:44
* develop: 1:22

I'm using `FormatCustomText`, `Timer` and `AdaptiveTransferSpeed`. No problems with develop version.

**Comment by WoLpH** [comment]
Good to hear :)

In these extreme cases I would still recommend adding some rate limiting on your side of the code. The regular progressbar needs to do quite a few sanity checks which can be omitted in many cases. These take time and can easily be skipped for your purposes.

Simply replacing a regular bar with a slightly filtered one can help a lot:

```
import progressbar
from datetime import datetime

N = 10000000

# Regular bar without filtering
bar = progressbar.ProgressBar(max_value=N).start()
begin = datetime.now()
for i in range(N):
    bar.update(i)
bar.finish()

print 'Duration: %s' % (datetime.now() - begin)

# Bar with filtering
bar = progressbar.ProgressBar(max_value=N).start()
begin = datetime.now()
for i in range(N):
    if i % 100000 == 0:  # Only update once every 10000 values
        bar.update(i)
bar.finish()

print 'Duration: %s' % (datetime.now() - begin)
```
Results:
```
100% (10000000 of 10000000) |############################| Elapsed Time: 0:00:06 Time: 0:00:06
Duration: 0:00:06.821132
100% (10000000 of 10000000) |############################| Elapsed Time: 0:00:01 Time: 0:00:01
Duration: 0:00:01.184203
```

**Comment by Tset-Noitamotua** [comment]
Sorry for late feedback :(


I pip installed latest version and tried your suggestion (less frequent updates) - greate solution!

Thanks a lot!
