### ISSUE TITLE
Progressbar finishes before 100%

### ISSUE THREAD

**Issue by ZeweiChu** [WoLpH/python-progressbar#108]
#### Description

Progressbar finishes before 100%

#### Code

> import progressbar
> bar = progressbar.ProgressBar(max_value=14).start()
> 
> for idx in range(14):
>    print(idx)
>    bar.update(idx+1)
> 
> bar.finish()

This code gives: 

> N/A% (0 of 14) |                                                                                                       | Elapsed Time: 0:00:00 ETA:  --:--:--0
> 1
> 2
> 3
> 4
> 5
> 6
> 7
> 8
> 9
> 10
> 11
> 12
> 13

#### Versions

> >>> print(sys.version)
> 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
> [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

- Python distribution/environment: Anaconda
- Operating System: MaxOS
- Package version: 3.17.0

**Comment by gerritholl** [comment]
See also #102 which had the same symptom but was solved.  Looks like this problem is back.

**Comment by WoLpH** [comment]
It's probably a slightly different variant. Apparently it's not easy to test since all tests are still passing.

**Comment by WoLpH** [comment]
I believe the tests should now cover all possible instances of this problem and the problem has been solved as well :)
