### ISSUE TITLE
Documentation on readthedocs.io seems to be out of date

### ISSUE THREAD

**Issue by mmabey** [WoLpH/python-progressbar#109]
#### Description

It seems the documentation on http://progressbar-2.readthedocs.io/en/latest is out of sync with the correct documentation at http://pythonhosted.org/progressbar2/. In particular, the docs for `utils.get_terminal_size()`. Compare the following two documents:

- http://pythonhosted.org/progressbar2/progressbar.utils.html#progressbar.utils.get_terminal_size
- http://progressbar-2.readthedocs.io/en/latest/progressbar.utils.html#progressbar.utils.get_terminal_size

For me, the issue was that the return values are no longer in the order specified on readthedocs.io, which was kind of confusing for a couple minutes...

#### Versions

- Python version: 3.5.2 (default, Sep 22 2016, 14:31:28) [GCC 4.8.5]
- Python distribution/environment: CPython
- Operating System: Linux Mint 17.3
- Package version: 3.17.1

**Comment by WoLpH** [comment]
Unfortunately Pythonhosted has deprecated documentation support in favour of Readthedocs so I haven't updated that lately. It seems that documentation wasn't destroyed yet so I just did that to prevent confusion.

As for readthedocs, apparently the build was broken which caused it to be out of date. I've fixed the docs and in the future it should alert me if it ever breaks again.

Thanks for the heads up!
