### ISSUE TITLE
none of the examples is working in pycharm

### ISSUE THREAD

**Issue by transfluxus** [WoLpH/python-progressbar#110]
#### Description

the first one just doesnt deliver any output until it reaches 100%
the parameter `max_value` and `redirect_stdout` do  not exist in the actual version, there is maxval but there are more issues...

**Comment by WoLpH** [comment]
Which Python version are you running? And which OS?

**Comment by WoLpH** [comment]
I've just ran all examples on PyCharm 16.1.4 on OS X with Python 2.7 and I see no issues.

**Comment by transfluxus** [comment]
hehe. thanks for the ultra fast reply. probably i downloaded the completely wrong at all.
I think you could make it more explicit on the documentation and pypi to download progressbar2
not progressbar... got it running some other time. great work!

**Comment by transfluxus** [comment]
are you using it in pycharm tho? its jumping around like crazy

**Comment by WoLpH** [comment]
It seems an update some time ago accidently removed the install instructions: https://github.com/WoLpH/python-progressbar/commit/dd9deeb168f22f952dece6e151c3032b9d8f77ea#diff-88b99bb28683bd5b7e3a204826ead112
Guess I'll add it again :)

Generally I don't use Pycharm all that much but it should function, the only thing that might not work correctly is the detection of the terminal width in Pycharm. Setting the terminal to a fixed size (`term_width`) might help there: http://progressbar-2.readthedocs.io/en/latest/progressbar.bar.html#progressbar.bar.ProgressBar

**Comment by transfluxus** [comment]
cool. muchas gracias!
