### ISSUE TITLE
Update to python 3 possible?

### ISSUE THREAD

**Issue by wccandm** [WoLpH/python-progressbar#111]
#### Description

Want to use this in a python3 project on a raspberry pi.
#### Code

n/a

#### Versions

- Python version: `import sys; print(sys.version)`
- Python distribution/environment: CPython/Anaconda/IPython/IDLE
- Operating System: Windows 10, Ubuntu Linux, etc.
- Package version: `import progressbar; print(progressbar.__version__)`

**Comment by WoLpH** [comment]
The project supports Python 3 fully and is automatically tested on:

 - Python 2.7
 - Python 3.3
 - Python 3.4
 - Python 3.5
 - Pypy

Do you have any specific problems?

**Comment by wccandm** [comment]
No specific problems, I didn't try.
The front page on PyPi says Python 2.7
I will try on Raspberry Pi (Python 3.4.2).

**Comment by WoLpH** [comment]
Can you give me a link to that page? I see multiple Python versiosn in the "categories" block: https://pypi.python.org/pypi/progressbar2

Or if you're talking about the `.whl` file, that's indeed a tad confusing. It's actually a universal wheel which means it works for both Python 2 and 3 but it was build using Python 2.7

**Comment by wccandm** [comment]
https://pypi.python.org/pypi/progressbar2#downloads

<img width="1137" alt="screenshot 2017-04-12 14 37 58" src="https://cloud.githubusercontent.com/assets/3610210/24957923/cea5e3d0-1f8d-11e7-946e-364d6bc1cd79.png">

**Comment by WoLpH** [comment]
I see. That information is irrelevant in this case as it's a universal wheel (notice the py2.py3 part of the filename). For most packages you should simply ignore that bit of information.

**Comment by wohali** [comment]
@WoLpH It'd be nice if the README itself explicitly stated support for Python 2 and 3. :)

**Comment by WoLpH** [comment]
I've tried to clarify it a little bit :)
