### ISSUE TITLE
Not an issue, just looking for an example

### ISSUE THREAD

**Issue by securisec** [WoLpH/python-progressbar#112]
Would you happen to have an example on how I can use progressbar to track the progress of a subprocess.Popen?

Thanks!

**Comment by WoLpH** [comment]
It would depend entirely on what the subprocess does. Are you reading lines of text from the subprocess? If so, it could look something like this:

```
import subprocess
import progressbar

# Replace this with your command
args = ['ls', '-l']

bar = progressbar.ProgressBar(redirect_stdout=True)
process = subprocess.Popen(args, stdout=subprocess.PIPE)
for line in bar(process.stdout):
    print('Got line from command: %s' % line.strip())
```

**Comment by securisec** [comment]
hmm.. i dont think thats quite what I am after. All that code is doing is printing out 'Got line from command ls output' .. i need something print a progress bar on a script or tool as it runs, but I may need to leverage multiprocessing to achieve that...

**Comment by WoLpH** [comment]
Generally multiprocessing works quite well for purposes such as these. A simple example:

```
import progressbar
import multiprocessing


def some_function(i):
    return i + 1


items = list(range(100))  # list() to make sure this code sample also works on Python 3
bar = progressbar.ProgressBar(max_value=len(items), redirect_stdout=True)

for i in pool.imap_unordered(some_function, items):
    print i
```
