### ISSUE TITLE
dynamic max value

### ISSUE THREAD

**Issue by DrRibosome** [WoLpH/python-progressbar#113]
For some kinds of jobs the max number of tasks may not be known at the start time (for instance, if a task starts more tasks). In cases like this it would be nice to be able to update the max value in a way similar to the current `update` call and have the bar/eta/etc adjust and redraw.

**Comment by WoLpH** [comment]
While there isn't a call for it, it's easy to do without a call:
```
import time
import progressbar


bar = progressbar.ProgressBar(max_value=10)
for i in bar(range(100)):
    bar.max_value = max(50, i * i)
    time.sleep(0.2)
```

**Comment by WoLpH** [comment]
Closed due to inactivity
