### ISSUE TITLE
eta repeatedly prints on newline above progressbar

### ISSUE THREAD

**Issue by jkarimi91** [WoLpH/python-progressbar#116]
#### Description

The eta is repeatedly printed above the progress bar. 

<img width="634" alt="screen shot 2017-05-25 at 5 05 46 pm" src="https://cloud.githubusercontent.com/assets/8411317/26475393/79e8a962-416c-11e7-9c54-516f9cc05c14.png">

#### Code

```python
import progressbar
from time import sleep

widgets = [
          'Test: ', progressbar.Percentage(),
          ' ', progressbar.Bar(),
          ' ', progressbar.ETA(),
          ' ', progressbar.FileTransferSpeed(),
      ]
bar = progressbar.ProgressBar(widgets=widgets, max_value=1000).start()
for i in range(100):
    # do something
    bar.update(10 * i + 1)
    sleep(1)
bar.finish()
```

#### Versions

- Python version: 2.7.13
- Python distribution/environment: Anaconda
- Operating System: El Capitan
- Package version: 3.20.1

**Comment by WoLpH** [comment]
Oops.. It seems the release today accidently kept a print statement inside

**Comment by WoLpH** [comment]
The new release is now on pypi. Thanks for letting me know!
