### ISSUE TITLE
ETA and AdaptiveETA widgets

### ISSUE THREAD

**Issue by Midnighter** [WoLpH/python-progressbar#12]
Hi, just wondering whether you are interested in changing the `ETA` and `AdapativeETA` widgets. At the moment their estimation is based on the mean processing time per item:

```
pbar.seconds_elapsed / pbar.currval
```

and

```
per_item = duration / items
```

respectively. However, the mean is very susceptible to outliers, i.e., a few tasks that took exceptionally long will lead to over estimation of the time needed, whereas a few very short tasks (due to handled exceptions, for example) will lead to gross underestimation of the ETA. I propose to use the median instead, which is statistically much more robust. If you're interested, I can look into making a pull request.

**Comment by WoLpH** [comment]
How do you like the current version? We could easily add a different calculation to it now :)
