### ISSUE TITLE
Can't print to stdout after calling finish unless calling it twice

### ISSUE THREAD

**Issue by Preston-Landers** [WoLpH/python-progressbar#120]
#### Description

When using `redirect_stdout=True`, attempts to `print()` after finishing or otherwise write to sys.stdout are lost (not printed to console), unless `finish()` is called twice. It seems only the second finish call actually restores the old stdout.

Doesn't matter whether using context wrapper or not. If using context wrapper, you must call `finish()` inside the context to get stdout restored.  If not using context wrapper, you must call `finish` twice.

Following example illustrates. Running this as is, you should see FINISH printed.  If you remove that second `p.finish()` call, you won't see FINISH printed.

#### Code
```python
import progressbar
import time
import sys

m = 24514315
p = progressbar.ProgressBar(
    widgets=[progressbar.Percentage(), progressbar.Bar()],
    max_value=m,
    redirect_stdout=True,
)

print("START")

for x in range(0, m, 8192):
    time.sleep(0.0001)
    p.update(x)

p.finish()
p.finish()   # why does it need another finish here?

# with progressbar.ProgressBar(
#         widgets=[progressbar.Percentage(), progressbar.Bar()],
#         max_value=m,
#         redirect_stdout=True) as p:
#     for x in range(0, m, 8192):
#         time.sleep(0.0001)
#         p.update(x)
#
#     p.finish()

print("FINISHED")
```

#### Versions

- Python version: 3.6.1 (x86-64)
- Python distribution/environment: CPython
- Operating System: Windows 10 x86-64
- Package version: 3.20.2

**Comment by WoLpH** [comment]
This might actually have been fixed already in #117, can you try version 3.30.0?

**Comment by WoLpH** [comment]
Thanks for the detailed bug report by the way! It's greatly appreciated :)

For what it's worth, 3.30.0 fixes this issue for me.

**Comment by Preston-Landers** [comment]
OK, yeah, 3.30.0 does seem to fix it. Sorry, I thought I was working with the latest version already - is that marked as a beta or preview release or something?

**Comment by WoLpH** [comment]
Not your mistake, I just released that version about an hour ago :)
Thanks for the help!

**Comment by Preston-Landers** [comment]
And thank you for this project, it really helps improve the usability of my database restore scripts.
