### ISSUE TITLE
Showing KiB/s when it should be MiB/s

### ISSUE THREAD

**Issue by meyersbs** [WoLpH/python-progressbar#124]
#### Description

I am downloading a very large (`8GB`) file using `urllib.request.urlretrieve`, but calls to `FileTransferSpeed()` are showing the speed in `KiB/s` throughout the entire download, when it clearly should be `MiB/s`.

![progress3](https://user-images.githubusercontent.com/4073851/27197229-73648e7e-51db-11e7-9f85-c28c352c9940.png)

**Note:** calls to `ETA()` _are_ showing the correct time.

#### Code

``` python
import progressbar as pb
from urllib.request import urlretrieve

def download_progress(blocks_read, block_size, total_size):
    if blocks_read == 0:
        widgets = [pb.Percentage(), ' ', pb.Bar(), ' ', pb.ETA(), ' ',
                   pb.FileTransferSpeed()]
        download_progress.progress_bar = pb.ProgressBar(widgets=widgets,
            maxval=(total_size/block_size) + 1).start()

    download_progress.progress_bar.update(blocks_read)

def _download(out_path, url):
    (_, headers) = urlretrieve(url, out_path, reporthook=download_progress)
```

#### Versions

- Python version: `3.5.3 (default, Jan 19 2017, 14:11:04) \n[GCC 6.3.0 20170118]`
- Operating System: `Ubuntu 17.04`
- Package version: `3.30.2`

**Comment by WoLpH** [comment]
I believe the error is actually in your code, you are passing along the `blocks_read` which needs to be multiplied by the `block_size` to get the progress in bytes instead of blocks.

Due to this blocksize the progressbar tends to go beyond the `total_size` however so we need to account for that. This code appears to do the trick just fine:

```python
import progressbar as pb

# Little Python 2 and 3 compatibility
try:
    from urllib.request import urlretrieve
except ImportError:
    from urllib import urlretrieve


def download_progress(blocks_read, block_size, total_size):
    # print(locals())
    if blocks_read == 0:
        widgets = [pb.Percentage(), ' ', pb.Bar(), ' ', pb.ETA(), ' ',
                   pb.FileTransferSpeed()]
        download_progress.progress_bar = pb.ProgressBar(
            widgets=widgets, maxval=total_size + block_size).start()

    download_progress.progress_bar.update(blocks_read * block_size)


def download(out_path, url):
    (_, headers) = urlretrieve(url, out_path, reporthook=download_progress)
    download_progress.progress_bar.finish()
```

**Comment by meyersbs** [comment]
Thank you for your explanation; that did the trick!
