### ISSUE TITLE
Feature request: Show current wall time instead of elapsed time

### ISSUE THREAD

**Issue by ChrisCummins** [WoLpH/python-progressbar#127]
#### Description

For long running jobs where individual tasks may take a long time or stall, `Elapsed Time` becomes hard to interpret. What would be more useful for me is a `Current Time` indicator. This would allow me, at a glance, to see if the jobs are still completing, or if they have stalled and haven't made progress in hours.

#### Code

One possible interface:
```py
for job in ProgressBar()(create_jobs(), current_time=True):
   ...
```

which would output:
```
...
  1% (177 of 10001) |              | Current Time: 16:39:23 ETA: 1 day, 12:25:58
  1% (178 of 10001) |              | Current Time: 16:39:23 ETA: 1 day, 12:13:50
  1% (179 of 10001) |              | Current Time: 16:39:49 ETA: 1 day, 12:25:10
```

**Comment by WoLpH** [comment]
I can see how this can be useful, I'll add it as soon as I have some time to work on this library again :)

However... I would personally recommend running the actual job in separate processes (multiprocessing for example:  https://github.com/WoLpH/python-progressbar/issues/112#issuecomment-294985286
Or threads :)

Simply have the main process run a `while True: bar.update(); time.sleep(1)` or something so the progressbar itself won't stall.

**Comment by ChrisCummins** [comment]
Cheers Rick! I use your library everyday, it's saved me so much time writing progress output boilerplate.

Multi{processing, threading} isn't enough for this particular use-case. Here's a minimal working example for the kind of case where `Current time` would come in handy:

```py
from time import sleep
from random import random
from progressbar import ProgressBar

def some_function():
    sleep(random() if random() > .01 else 1e4)

for i in ProgressBar()(list(range(10000))):
    some_function()
```

**Comment by ChrisCummins** [comment]
I may have a go at implementing this myself and sending over a PR. I have a couple of other features in mind. For example, given the following:

<img width="1049" alt="screen shot 2017-07-13 at 23 37 39" src="https://user-images.githubusercontent.com/1636663/28191043-fc4f619a-6825-11e7-97b3-6df3be784158.png">

Q: which of those three terminals is the one running `./foo.py`? An easy fix for this would be the ability to add a prefix text to ProgressBar's output, so that I could tell the separate jobs apart by seeing `foo.py 1% (177 of 10001)`.

**Comment by WoLpH** [comment]
You could easily do that actually :)

```python
import sys
import progressbar

bar = ProgressBar(widgets=[sys.argv[1], ' :: ', progressbar.ETA()])
```

**Comment by ChrisCummins** [comment]
Ah fantastic! I really should RTFM. Thank you for your help and code!

**Comment by WoLpH** [comment]
> Cheers Rick! I use your library everyday, it's saved me so much time writing progress output boilerplate.

You're welcome :) Glad you like it

> Multi{processing, threading} isn't enough for this particular use-case. Here's a minimal working example for the kind of case where `Current time` would come in handy:

I see your point and I agree rewriting the code can be tricky but I still think it's the better solution for your problem. Here's a (theoretically, untested) version of your code with threads:


```py
import threading
from time import sleep
from random import random
from progressbar import ProgressBar

def some_function():
    sleep(random() if random() > .01 else 1e4)

class Worker(threading.Thread):
    def __init__(self, n):
        self.n = n
        self.i = 0
        super(Worker, self).__init__()

    def run(self):
        for i in list(range(self.n)):
            some_function()

worker = Worker(10000)
bar = ProgressBar(max_value=worker.n)
worker.start()
while worker.is_alive():
    bar.update(worker.i)
    worker.join(0.1)
```

**Comment by ChrisCummins** [comment]
Sorry, I over-simplified. In reality, `some_function()` will be something time sensitive or resource-bound ([e.g.](https://github.com/ChrisCummins/clgen/blob/master/clgen/_model.py#L300)), hence why the calls can't be parallelised

**Comment by WoLpH** [comment]
I understand, but give the code a try. It might work for you :)
This code isn't really paralellising, it's simply splitting the user interface from the heavy calculations.
