### ISSUE TITLE
Tracebacks not shown

### ISSUE THREAD

**Issue by NicoHood** [WoLpH/python-progressbar#129]
#### Description

Tracebacks are not shown anymore when stderr gets redirected. If there is a solution to this, it should be added to the readme as well.

#### Code

```py
#!/usr/bin/env python3

import progressbar

progressbar.streams.wrap_stderr()

thisissanerror
```
#### Versions

- Python version: `python 3.6.1-1`
- Python distribution/environment: ???
- Operating System: ArchLinux
- Package version: `3.30.2`

**Comment by WoLpH** [comment]
That's indeed an unfortunate side-effect of the output wrapping, I believe I've found a fix for the issue by wrapping `sys.excepthook` as well

**Comment by NicoHood** [comment]
Thanks! Would you mind tagging a new release? Publishing a GPG signed release tarball would also be nice. If you need more help on this [click here](https://github.com/NicoHood/gpgit).
