### ISSUE TITLE
GPG signatures for source validation

### ISSUE THREAD

**Issue by NicoHood** [WoLpH/python-progressbar#131]
As we all know, today more than ever before, it is crucial to be able to trust
our computing environments. One of the main difficulties that package
maintainers of Linux distributions face, is the difficulty to verify the
authenticity and the integrity of the source code.

The Arch Linux team would appreciate it if you would provide us GPG signatures
in order to verify easily and quickly your source code releases.

**Overview of the required tasks:**
* Create and/or use a 4096-bit RSA keypair for the file signing.
* Keep your key secret, use a strong unique passphrase for the key.
* Upload the public key to a key server and publish the full fingerprint.
* Sign every new git commit and tag.
* Create signed compressed (xz --best) release archives
* Upload a strong message digest (sha512) of the archive
* Configure https for your download server

[GPGit](https://github.com/NicoHood/gpgit) is meant to bring GPG to the masses.
It is not only a shell script that automates the process of creating new signed
git releases with GPG but also comes with this step-by-step readme guide for
learning how to use GPG.

**Additional Information:**
* https://github.com/NicoHood/gpgit
* https://help.github.com/categories/gpg/
* https://wiki.archlinux.org/index.php/GnuPG
* https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
* https://www.qubes-os.org/doc/verifying-signatures/
* https://lkml.org/lkml/2016/8/15/445
* https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https
* https://www.enigmail.net/index.php/en/

Thanks in advance.

**Comment by WoLpH** [comment]
I suppose it's a good idea, I've been an avid GPG user in the past (https://pgp.mit.edu/pks/lookup?op=vindex&search=0xDB95009289C3EB3C) but I've stopped using it since I appeared to be one of the few that actually did...

For Git releases however it's definitely a good idea. I'll incorporate it in my git-flow-avh release process to auto-sign all releases in the future :)

**Comment by NicoHood** [comment]
@WoLpH Thanks! You definitely need to generate a new GPG key though. You are using DSA1024 which is considered (very) insecure nowadays. I suggest an RSA4096 key.

**Comment by WoLpH** [comment]
Yep... it's not safe by any standard anymore. I still have it though, so I can still sign the new key although I don't think anyone cares about that ;)

It was perfectly acceptable when I started using it though... how time flies. Somehow Git on my OS X machine doesn't want to sign yet so I'm still debugging a bit...
```
gpg: signing failed: Inappropriate ioctl for device
gpg: signing failed: Inappropriate ioctl for device
error: gpg failed to sign the data
error: unable to sign the tag
```

**Comment by WoLpH** [comment]
Apparently it was related to a few gpg versions colliding, it's fixed now and I've pushed a new release with a signed tag :)

Thanks for all the info!
We have a verified tag now: https://github.com/WoLpH/python-progressbar/tags

**Comment by NicoHood** [comment]
Thanks. Would you please also publish a signed source tarball? This is a) simpler to package and b) more secure than signed git tags, as you can [trick those too.](https://www.usenix.org/conference/usenixsecurity16/technical-sessions/presentation/torres-arias)

You should put the new full GPG fingerprint (40chars) somewhere on the project site if possible. (do `gpg -k <yourmail or name or short key>`

**Comment by WoLpH** [comment]
Oops... you're right, I forgot to sign the Pypi release well.

I've created a new signed release on pypi: https://pypi.python.org/pypi/progressbar2

**Comment by NicoHood** [comment]
Perfect! will try that out.

**Comment by NicoHood** [comment]
The website of this github repository can be set as https:
https://progressbar-2.readthedocs.io/en/latest/

**Comment by WoLpH** [comment]
Changed as well, and I've added a link to my gpg key in the readme

**Comment by NicoHood** [comment]
Thanks!
I assume you also say this one:
https://github.com/WoLpH/python-utils/issues/3

I am preparing everything to move to your version. It would be really important for the users who upgrade the dependency what is compatible and what not. :)

**Comment by WoLpH** [comment]
Yep, working on that one :)

**Comment by NicoHood** [comment]
Thanks for the fast fixes. Its all working fine.
Just let me know what I should tell the users before upgrading the package :)

**Comment by WoLpH** [comment]
I always add a commit message roughly detailing what changed in the release (part of the tags) but generally no backwards incompatible changes should occur.

The last backwards incompatible change was the version v3.7.x last year which dropped Python 2.6 support. Beyond that only features are added and bugs are (hopefully) fixed :)

The latest release made sure stacktraces are still visible when output capturing is enabled and it added a "wall time" widget.

For a full list of releases with the changes: https://github.com/WoLpH/python-progressbar/releases
Or commandline:
```cmd
# git tag -n

v2.3            Added nicer defaults
v2.6.1          v2.6.1
v2.6.2          v2.6.2 adaptive eta added
v3.0.1          Added Python 3.x support and thanks @tnestmeyer for adding AbsoluteETA widget
v3.1.0          Added full python 3.5 support
v3.10.0         Fixed output redirection with special ipython and jupyter notebook support
v3.10.1         Fixed resizing with nested progressbars
v3.12.0         Improved support for sequences with unknown length thanks to @WohthaN
v3.15.0         Large performance improvements. Dropped Pypy3 support in Travis tests. Improved output redirection (fixed several bugs). Showing N/A when no numbers are available. v3.15.0
v3.15.1         Made sure even really fast progressbars finish. Fixes #102 v3.15.1
v3.16.0         converted all strings to unicode v3.16.0
v3.16.1         preferring fixed size over incorrect size detection for jupyter v3.16.1
v3.17.0         Converted all strings to unicode
v3.17.1         fixed unicode issues on python 3 (fixes #104, fixes #105, #fixes 106) v3.17.1
v3.18.0         fixed 100% progressbar, relocated tests and improved several tests. fixes #108 v3.18.0
v3.18.1         Re-applied the Jupyter Notebook fixes by Matthew Wardrop v3.18.1
v3.2.0          New version packaged using cookiecutter template: https://github.com/WoLpH/cookiecutter-pypackage-pythonic
v3.20.0         Added global stdout/stderr redirection support so we can function with loggers as well. Fixes #101 v3.20.0
v3.20.1         Reaplying @matthewwardrop his pull request #103 v3.20.1
v3.20.2         removed print statement to fix #116 v3.20.2
v3.3.0          Fixes for UnknownLength handling
v3.3.1          Fixed silly inheritance bug with super()
v3.3.2          Set default start value to min_value
v3.3.3          fixed widgets to be fixed width
v3.30.0         Fixed several bugs thanks to @matthewwardrop and refactored requirements
v3.30.2         fixed bug #121 and #122 v3.30.2
v3.31.0         fixed stacktrace output when capturing output and implemented wall time widget v3.31.0
v3.31.1         bumping version to enable release signing v3.31.1
v3.32.0         fixed python 3.x tests and updated readme v3.32.0
v3.4.0          fixed docs and print order for output redirection v3.4.0
v3.4.1          fixed terminal size detection bugs v3.4.1
v3.4.2          Fixed auto width
v3.4.3          Removed debug statement
v3.5.0          Added size-dependent widgets
v3.5.1          removed debug code, the exception shouldnt raise v3.5.1
v3.5.2          Fixed documentation for resizing and made the progressbar a little faster in case of many updates. Thanks to @max-arnold for the patches!'
v3.6.0          Fixed progressbar on Windows consoles
v3.6.1          fixed jupyter notebook, last update and negative ETA bugs thanks to @zzzsochi v3.6.1
v3.7.0          added more widgets, dropped python 2.6 support and improved testing
v3.8.0          modernized the package and improved python 3 support
v3.8.1          Fixed strange git undo
v3.9.0          Finished ETA widgets
v3.9.1          improved test coverage v3.9.1
v3.9.3          Bumped version for pypi
v3.9.4          Fixed Linux integer overflow bug with ETA
```

**Comment by NicoHood** [comment]
Thanks. This sounds good. We dont support python 2.6 anyways, so it all should work fine.

https://www.archlinux.org/packages/community/any/python-utils/
https://www.archlinux.org/packages/community-testing/any/python-progressbar/

**Comment by WoLpH** [comment]
Awesome! Thanks for the great work :)
