### ISSUE TITLE
Error when supplying format to Counter

### ISSUE THREAD

**Issue by gauss256** [WoLpH/python-progressbar#133]
#### Description

When I specify a format string to Counter, I get the error "TypeError: %d format: a number is required, not dict"

#### Code

```
widgets = ['Aspect ratio: %d ' % ar, Counter(format=u'%5d'), ' ', 
    Bar(marker='#', left='[', right=']'), ' ', AdaptiveETA()]
with ProgressBar(
    fd=sys.stdout,
    widgets=widgets,
    max_value=num_images,
    redirect_stdout=True) as progress:
```

#### Versions

- Python version: 2.7.13
- Python distribution/environment: Anaconda
- Operating System: Linux
- Package version: 3.32.1

**Comment by WoLpH** [comment]
The value needs to be named since it gets passed all data.

Try this instead:
```python
import progressbar

counter = progressbar.Counter(format=u'%(value)5d')
```

**Comment by gauss256** [comment]
That works, thanks.

The syntax is a little obscure. Perhaps an example in the docs would help.

**Comment by WoLpH** [comment]
True, the docs could use a little upgrade in terms of usage but the example is available in the `Counter` arguments: http://progressbar-2.readthedocs.io/en/latest/progressbar.widgets.html?highlight=counter#progressbar.widgets.Counter

Additionally, the source is linked from the docs as well: http://progressbar-2.readthedocs.io/en/latest/_modules/progressbar/widgets.html#Counter

**Comment by gauss256** [comment]
Don't get me wrong, the docs are good and nicely cross-referenced with the source. But I had looked at both the items you mentioned and still was unclear. My suggestion is to add the usage of a customized format to one of the examples here http://progressbar-2.readthedocs.io/en/latest/examples.html

**Comment by WoLpH** [comment]
You're right, that might help a bit :)

I've added it to the examples
