### ISSUE TITLE
Minor visual instability 

### ISSUE THREAD

**Issue by gauss256** [WoLpH/python-progressbar#135]
#### Description

This is really nitpicky, but I value visual stability in progress bars. There is a space that appears in the progress bar while updating that disappears when it is finished.

It's definitely nice that the times are flush right at the ends, and I wouldn't want to lose that.

During update:
```
Aspect ratio: 1 5000 [##########################################] Time: 0:00:15
Aspect ratio: 2 3735 [################################           ] ETA: 0:00:01
                                                                ^ this space
```
After finishing:
```
Aspect ratio: 1 5000 [##########################################] Time: 0:00:15
Aspect ratio: 2 5000 [##########################################] Time: 0:00:15

```
#### Code

```
widgets = ['Aspect ratio: %d ' % ar, Counter(format=u'%(value)4d'), ' ', 
    Bar(marker='#', left='[', right=']'), ' ', AdaptiveETA()]
```
#### Versions

- Python version: 2.7.13
- Python distribution/environment: Anaconda
- Operating System: Linux
- Package version: 3.32.1

**Comment by WoLpH** [comment]
It seems the ETA widget didn't have the right spacing in all cases, can you check if the development branch works as expected now?

**Comment by gauss256** [comment]
Yes, that works. Thanks!

(Love the fast turnaround on these issues...)

**Comment by WoLpH** [comment]
You're mostly just lucky in that regard, my availability varies ;)
