### ISSUE TITLE
AdaptiveETA doesn't reset after restart

### ISSUE THREAD

**Issue by w4nderlust** [WoLpH/python-progressbar#136]
#### Description

If i finish and then restart a bar using AdaptiveETA, instead of showing the ETA the bar shows me the Time.

#### Code

```
import progressbar
import time

maximum = 50
widgets = [progressbar.FormatLabel('Bar'), "   ",
                       progressbar.Percentage(), " ",
                       progressbar.Bar(), " ",
                       progressbar.Timer(), " ",
                       progressbar.AdaptiveETA()]
bar = progressbar.ProgressBar(widgets=widgets,
                              max_value=maximum)

steps = 0
bar.start()
while steps < maximum:
	bar.update(steps)
	time.sleep(0.1)
	steps += 1
bar.finish()

time.sleep(0.2)

steps = 0
bar.start()
while steps < maximum:
	bar.update(steps)
	time.sleep(0.1)
	steps += 1
bar.finish()
```

#### Versions

- Python version: 3.5.2
- Python distribution/environment: Python
- Operating System:Ubuntu 16.4
- Package version: 3.30.2

**Comment by WoLpH** [comment]
Thanks for the bug report, I'm not 100% sure what would be the best way to solve it...

As a temporary workaround, the state can easily be reset with a: `bar.extra = dict()`.
For the actual solution I'm afraid that might cause unexpected side effects for people (ab)using that feature for custom data... I'll have to do a bit more research I guess.

**Comment by w4nderlust** [comment]
Thanks for the answer. I tried the workaround, placing `bar.extra = dict()` both after the first finish and after the second start but in both cases it didn't work. Another possible workaround is to create a totally new bar, but that doesn't seem to be the best solution memory wise.

**Comment by WoLpH** [comment]
No need to worry about that. Python will simply garbage collect the old bar and create a new one. Assuming you use the same variable of course :)

I've pushed a fix to the development branch for you to try, I believe it solves the issue and I'm hoping it won't cause issues for other users.

**Comment by w4nderlust** [comment]
Tested, it works just fine. Thank you really much for the super quick bugfix!

**Comment by NicoHood** [comment]
@WoLpH If you do not create a github "release" and only a tag, I do not get a notification on a package update. You can leave it like this, but it would be nice of you can email me on a new release. see contact.nicohood.de

**Comment by WoLpH** [comment]
@NicoHood I can make Travis automatically (and safely) execute some code as soon as I add a new tag. For both of our convenience, what would be the best way to automate this?

I think I can make Travis automatically upload a release to Github as well: https://docs.travis-ci.com/user/deployment/releases/

**Comment by NicoHood** [comment]
Or you could manually tag the release with gpgit and also add the signature via github releases (instead of pypi). Do as you wish, it shouldnt be too complicated, its just that we are on the latest version. You can also flag the package out of date on the archlinux page.

**Comment by WoLpH** [comment]
@NicoHood I tried gpgit after your initial request but it was a bit tricky to incorporate in my workflow which means that at some point or another I'll forget to use it and that would be bad ;)
I've made sure that travis automatically creates github releases whenever I create a tag so I believe that should solve the issue.
