### ISSUE TITLE
[bug] character width calculate error with unicode

### ISSUE THREAD

**Issue by gsw945** [WoLpH/python-progressbar#137]
#### Description
Chinese characters lead to line breaks or print repeatedly, because of the characters' width calculated error.

#### Code
1. use `FormatCustomText`:
    ```python
    import progressbar
    import time


    total = 12
    current = 0
    format_custom_text = progressbar.FormatCustomText(
        '%(progress)6s: ',
        dict(
            progress='进度'
        ),
    )
    bar = progressbar.ProgressBar(
        widgets=[
            format_custom_text,
            progressbar.Bar(),
            ' ',
            progressbar.Counter(),
            ' / {0}'.format(total)
        ],
        max_value=total,
        redirect_stdout=True
    )
    bar.start()
    bar.update(current)
    while current < total:
        current += 1
        bar.update(current)
        time.sleep(0.5)
    bar.finish()
    ```
    output:
    ![001](https://user-images.githubusercontent.com/6281968/28907801-a2dfae3e-7852-11e7-80f6-9437d2a48cd9.png)

2. use raw text:
    ```python
    import progressbar
    import time


    total = 12
    current = 0
    tip = '进度: '
    bar = progressbar.ProgressBar(
        widgets=[
            tip,
            progressbar.Bar(),
            ' ',
            progressbar.Counter(),
            ' / {0}'.format(total)
        ],
        max_value=total,
        redirect_stdout=True
    )
    bar.start()
    bar.update(current)
    while current < total:
        current += 1
        bar.update(current)
        time.sleep(0.5)
    bar.finish()
    ```
    output:
    ![002](https://user-images.githubusercontent.com/6281968/28907852-ed5039b6-7852-11e7-9cfa-e15754dd88f7.png)

3. fill length of str with 6(a chinese character's width is 2) by using `\0`
    ```python
    import progressbar
    import time


    total = 12
    current = 0
    tip = '进\0度\0: '
    bar = progressbar.ProgressBar(
        widgets=[
            tip,
            progressbar.Bar(),
            ' ',
            progressbar.Counter(),
            ' / {0}'.format(total)
        ],
        max_value=total,
        redirect_stdout=True
    )
    bar.start()
    bar.update(current)
    while current < total:
        current += 1
        bar.update(current)
        time.sleep(0.5)
    bar.finish()
    ```
    output:
    ![003](https://user-images.githubusercontent.com/6281968/28907863-f4b5f7b8-7852-11e7-9cd4-a326c153ffaf.png)

ps: **3** is the effect i expected.

#### Versions
- Python version: 3.5.2
- Python distribution/environment: CPython
- Operating System: Ubuntu 16.04 LTS
- Package version: 3.33.2

#### maybe helpful
[wcwidth](https://github.com/jquast/wcwidth) *Python library that measures the width of unicode strings rendered to a terminal*

**Comment by WoLpH** [comment]
Thanks for the very detailed bug report, it's greatly appreciated :)

I'll add support for a pluggable `len()` function so libraries such as `wcwidth` can be used. Since the width greatly depends on the font as well I imagine that even libraries such as `wcwidth` don't work correctly in all cases.

**Comment by WoLpH** [comment]
I've added support for a `custom_len` function to the progressbar. This makes it possible to specify your own custom length function, it seems the `wcwidth` library doesn't support these characters either so I've added an example to the readme to show at least one workaround.

```python
# vim: fileencoding=utf-8
import time
import progressbar


def custom_len(value):
    # These characters take up more space
    characters = {
        '进': 2,
        '度': 2,
    }

    total = 0
    for c in value:
        total += characters.get(c, 1)

    return total


bar = progressbar.ProgressBar(
    widgets=[
        '进度: ',
        progressbar.Bar(),
        ' ',
        progressbar.Counter(format='%(value)02d/%(max_value)d'),
    ],
    len_func=custom_len,
)
for i in bar(range(10)):
    time.sleep(0.1)
```
