### ISSUE TITLE
Increment progress by one instead of setting progress to the specified value

### ISSUE THREAD

**Issue by pbeza** [WoLpH/python-progressbar#138]
Why there is no `.increment()` or `.update()` parameterless method that would increment progress by 1 by default? This would be really handy, especially if `ProgressBar` object is passed to function handler (e.g. to `copy_function` in [`shutil.move`](https://docs.python.org/dev/library/shutil.html#shutil.move) function as I currently do).

I'd like to be able to update progress by one using `bar.update()` or `bar.increment()` instead of calling ugly `bar.update(bar.value + 1)` (or possibly `bar.__next__()`).

**Comment by WoLpH** [comment]
Sorry for the slow response, completely forgot about your question.

By default the `bar.__next__()` method actually does exactly what you're looking for: https://github.com/WoLpH/python-progressbar/blob/develop/progressbar/bar.py#L430-L440

```python
    def __next__(self):
        try:
            value = next(self._iterable)
            if self.start_time is None:
                self.start()
            else:
                self.update(self.value + 1)
            return value
        except StopIteration:
            self.finish()
            raise
```

For Python 2 compatibility (and your convenience in this case) you can also use `bar.next()`

**Comment by pbeza** [comment]
Calling `__next__()` explicitly [doesn't](https://stackoverflow.com/questions/8689964/why-do-some-functions-have-underscores-before-and-after-the-function-name) look good (I think that functions with leading and trailing underscores shouldn't be called explicitly in well designed application), but if calling `next()` does the same, it's OK for me. :-)

**Comment by WoLpH** [comment]
I agree :) The shorthand method is definitely the recommended option of the two
