### ISSUE TITLE
Bar collapsing 

### ISSUE THREAD

**Issue by lucabergamini** [WoLpH/python-progressbar#139]
#### Description

Under **Pycharm Community Edition 2017.1.2** the progress bar becomes smaller as DynamicMessages are appended, even with plenty of space on the right (see Figures below, where in the second one a new DynamicMessages is appended). Is it a bug or is it something intended?

![bar_1](https://user-images.githubusercontent.com/27865235/29527133-34675dea-8698-11e7-9610-6585d3020b62.png)

![bar](https://user-images.githubusercontent.com/27865235/29526940-917858f0-8697-11e7-98af-08cea6c93f2e.png)
 

#### Code

The Widgets setting for the second example is the following:
```
widgets = [

    'Batch: ', progressbar.Counter(),
        '/', progressbar.FormatCustomText('%(total)s',{"total":batch_number}),
        ' ', progressbar.Bar(marker="-", left='[', right=']'),
        ' ', progressbar.ETA(),
        ' ',
         progressbar.DynamicMessage('loss'),
        ' ',
        progressbar.DynamicMessage("accuracy"),' ',
    progressbar.DynamicMessage("epoch")
    ]
```

#### Versions

- Python version: 2.7.12 
- Python distribution/environment: VirtualEnv
- Operating System: Ubuntu 16.04
- Package version: 3.34.0

**Comment by WoLpH** [comment]
Sorry for the slow response, I didn't see your question earlier.

The problem here is that it's impossible (as far as I know) to detect the width of the PyCharm console. The fallback result is that the progressbar defaults to the "standard" console width of 79 characters.

You can work around it by manually specifying the terminal width:
```python
bar = progressbar.ProgressBar(
    widgets=widgets,
    term_width=120,
)
```

**Comment by lucabergamini** [comment]
That works like a charm! thank you!
