### ISSUE TITLE
Fails to build under Python 3 on non-UTF8 systems

### ISSUE THREAD

**Issue by lordmauve** [WoLpH/python-progressbar#140]
#### Description

When trying to build from an sdist on a containerised build host, setup.py crashes with this traceback:

```
Traceback (most recent call last):                                                                                                                                            
  File "setup.py", line 52, in <module>                                                                                                                                       
    readme = fh.read()
  File "dist/lib/python3.6/encodings/ascii.py", line 26, in decode                                                                                                                                                  
   return codecs.ascii_decode(input, self.errors)[0]                                                                                                                         
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 8625: ordinal not in range(128)                                                                          
```

The problem is that these containers do not set a UTF-8 locale, and in the `setup.py`, progressbar2 reads its README.rst without passing an `encoding=` argument.

In [the docs for open()](https://docs.python.org/3.6/library/functions.html#open), it says:

> In text mode, if encoding is not specified the encoding used is platform dependent: locale.getpreferredencoding(False) is called to get the current locale encoding.

This is ASCII on these hosts.

The fix is to change the line

```python
with open('README.rst') as fh:
```

to

```python
with open('README.rst', encoding='utf8') as fh:
```

#### Code

This can be reproduced on any host by running the command

```
   $ LANG=C python3 setup.py --help
```

#### Versions

- Python version: tested on 3.5 and 3.6, probably all 3.x
- Python distribution/environment: CPython
- Operating System: Linux
- Package version: 3.34.2

**Comment by lordmauve** [comment]
There are other open() calls in this file. Assuming all files in the distribution are UTF-8, a more robust fix might be to put this towards the top of the file:

```python
if sys.version_info > (3,):
    import functools
    open = partial(open, encoding='utf8')
```

**Comment by WoLpH** [comment]
Thanks for the detailed bug report and the proposed fix :)
Encoding issues are always annoying but that fix works nicely, I think I'll incorporate it in some of my other projects as well.

**Comment by lordmauve** [comment]
Thank you! It's so, so helpful to have such active maintainers.

**Comment by NicoHood** [comment]
The pypi version is missing. Could you please also upload there? Or as an alternative also publish the gpg signature on github?

**Comment by WoLpH** [comment]
Oops, forgot about that. I was waiting for the travis results yesterday (just to be certain) and didn't get back to that terminal. It's published now :)
