### ISSUE TITLE
Raising a ValueError when value > max_value an overkill?

### ISSUE THREAD

**Issue by centralniak** [WoLpH/python-progressbar#142]
#### Description

This ticket is more of a suggestion than a bug report, but I'm hoping to start the on discussion this issue.

I'm using `python-progressbar` when scanning our Redis database for offending keys. 

As I'm iterating over the keys using an iterator, it's possible that the result size (i.e. number of keys) changes between when the iterator was instantiated and when we reached `StopIteration`. 

There is a way to get the initial number of matching keys, and I was hoping I could pass that as `max_value`, and the progress bar would just either not reach 100% or just go slightly above 100% if the number of keys changed. However, in most cases, I would run into a `ValueError`, because `ProgressBar` does not allow `value > max_value`.

I think it's a bit of an overkill to raise an exception in this case and it should either be optional or just ignored altogether. The progressbar is really just the presentation layer and should not break the application logic even if the parameters passed don't make 100% sense.

#### Code

    bar = progressbar.ProgressBar()
    for full_key in bar(redis_client.scan_iter(), max_value=approximate_redis_key_count):
        pass

#### Versions

Irrelevant.

**Comment by WoLpH** [comment]
The check is at least somewhat needed because several of the calculations can break if it goes beyond the `max_value` (getting a progress bar that's wider than your screen for example). But it might be a good idea to allow updating the `max_value` if needed when updating.

For what it's worth, for the time being (and old versions) there is a simple workaround available. Simply override the `max_value` in the loop and you're done:

```python
bar = progressbar.ProgressBar(max_value=10)
bar.start()
for i in range(100):
    if i >= bar.max_value:
        bar.max_value = i
        bar.update(i)
```

Especially for iterators it would be logical if it would skip this check so that's definitely a good idea :)

**Comment by ChrisCummins** [comment]
Anecdotally, I too find the `ValueError` to be overkill. I usually end up guarding with something like `bar.update(min(value, max_value))`, but to bit honest it's a bit irritating, I'd much rather have the presentation layer just silently do whatever it wants. Negative ETAs, progress %s > 100... I don't mind, just don't crash the whole app :)

**Comment by WoLpH** [comment]
I'm releasing a new version now that allows for ignoring the `max_value` through the `max_error` parameter:
```python
import time
import progressbar


with progressbar.ProgressBar(max_value=10, max_error=False) as bar:
    for i in range(20):
        bar.update(i)
        time.sleep(0.1)
```

**Comment by ChrisCummins** [comment]
Great, thanks Rick!

**Comment by centralniak** [comment]
Wow. That's perfect. Thank you!
