### ISSUE TITLE
redirecting stdout unsafe if progress bar is deleted and not explicitly finished.

### ISSUE THREAD

**Issue by hardkrash** [WoLpH/python-progressbar#143]
#### Description

If finish is not called on a redirected output then stdout is not restored, and output will not work properly.  Please consider adding a `__del__` method to the redirected classes that will restore redirected output.

#### Versions

- Python version: 3.6.2
- Python distribution/environment: CPython
- Operating System: OS X 10.13
- Package version: 3.34.2

**Comment by WoLpH** [comment]
Indeed, this should be part of the code. I'll add it to the next release.

Thanks for the bug report!

**Comment by WoLpH** [comment]
It's fixed on the develop branch, I'll push out a release soon :)
