### ISSUE TITLE
Flickering tests on Windows

### ISSUE THREAD

**Issue by stuertz** [WoLpH/python-progressbar#146]
#### Description

The
* test_failure.py and
* test_time.py 

are failing from time to time.
The reason might be the lower resolution of time ticks on windows.

It could be easily fixed by adding a time sleep(0.1). But that's not the right solution IMHO.
A possible solution could be to use  timeit.default_timer() in bar.py, which has a finer resolution on windows.

#### Versions

* Python 2.7.14 / Python 3.6.3
* Anconda 
* Windows 10
* Progressbar: 3.34.4

**Comment by WoLpH** [comment]
In that case it might be something that would have to be monkeypatched with the tests. I've been burned by the performance impact of replacing the timer before.

Some people literally call the update millions of times in which case replacing the timer can make a huge difference.

**Comment by stuertz** [comment]
Agreed, performance is always an issue, but:

Windows:
python -m timeit -c "import timeit; timeit.default_timer()"
1000000 loops, best of 3: 0.478 usec per loop

python -m timeit -c "import time; time.time()"
1000000 loops, best of 3: 0.572 usec per loop

And on Linux the identical function to time.time() is called.
python -m timeit -c "import time; time.time()"
1000000 loops, best of 3: 0.236 usec per loop

python -m timeit -c "import timeit; timeit.default_timer()"
1000000 loops, best of 3: 0.23 usec per loop

So what was the issue then?

**Comment by WoLpH** [comment]
The problem is that it depends on both the windows/linux version and the python distribution (anaconda vs. regular) which makes it notoriously difficult to test for.

For example, read this blog post as well about a similar issue with Java: http://pzemtsov.github.io/2017/07/23/the-slow-currenttimemillis.html

**Comment by stuertz** [comment]
Thanks, interesting reading.
So it looks to me that it is accepted for performance reasons, to have a lower resolution on windows, which makes totally sense to me. The tests is somewhat testing the resolution of the timer and only works on systems with higher resolutions. So I would suggest skipping the test on Windows instead of pretending that the code would match the test, by mocking it.
