### ISSUE TITLE
Same package version from 2.7.3 to 3.4.1

### ISSUE THREAD

**Issue by jwnx** [WoLpH/python-progressbar#149]
#### Description

*Forever Young Bug*

In the 2.7.3 → 3.x transition, `__init__.py` was left containing a `__version__ = '2.7.3'` variable despite the new `__about__.py` file. This causes every `progressbar.__version__` to be 2.7.3 instead of the real version. This is fixed in 3.4.2, when `__init__.py` is rewritten. 

This breaks testing, debugging, etc.

#### Reproducing

````
pip install progressbar2==(2.7.3 ... 3.4.1)
python -c "import progressbar; print(progressbar.__version__)"
````

#### Code

https://github.com/WoLpH/python-progressbar/blob/v3.4.1/progressbar/__init__.py#L72
https://github.com/WoLpH/python-progressbar/blob/v3.4.0/progressbar/__init__.py#L72
https://github.com/WoLpH/python-progressbar/blob/v3.3.3/progressbar/__init__.py#L72
...
https://github.com/WoLpH/python-progressbar/blob/v3.0.1/progressbar/__init__.py#L71

#### Versions

- Python version: `3.6.3`
- Operating System: Linux

**Comment by WoLpH** [comment]
That should indeed b e changed, I'll fix it in the next release :)

**Comment by WoLpH** [comment]
Actually, upon further inspection this issue was fixed two years ago already: https://github.com/WoLpH/python-progressbar/commit/b9fa1ae528062889bfe55665257a28095fab835e

I think you simply need to update a little bit :)
