### ISSUE TITLE
process bar just keep rolling

### ISSUE THREAD

**Issue by Focke-Wulf** [WoLpH/python-progressbar#150]
#### Description

process bar just keep rolling like this.
I have already set redirect_stdout=True why it is not working?
 
![1](https://user-images.githubusercontent.com/26343300/34776764-dd4b47bc-f652-11e7-9404-f980ee5163b1.PNG)

![2](https://user-images.githubusercontent.com/26343300/34776767-df3e2242-f652-11e7-9968-5f905212921d.PNG)

#### Versions

- Python version: `import sys; print(sys.version)`
- Python distribution/environment: CPython/Anaconda/IPython/IDLE
- Operating System: Windows 10, Ubuntu Linux, etc.
- Package version: `import progressbar; print(progressbar.__version__)`

**Comment by WoLpH** [comment]
Judging from the screenshot, can I guess you're running this from PyCharm? If so... it's a known bug in PyCharm unfortunately :(

https://github.com/WoLpH/python-progressbar/issues/115

As a workaround you can use a single output stream instead. Writing both to stdout for example:
http://progressbar-2.readthedocs.io/en/latest/progressbar.bar.html?highlight=bar#progressbar.bar.DefaultFdMixin

```python
import sys

bar = progressbar.ProgressBar(redirect_stdout=True, fd=sys.stdout)
...
```
