### ISSUE TITLE
PyPI packages lacks test data

### ISSUE THREAD

**Issue by ashgillman** [WoLpH/python-progressbar#151]
Similar to here, which provides a possible solution:

https://github.com/trungdong/prov/issues/63

**Comment by WoLpH** [comment]
The only downside of this method is that it would include it with the current directory name (tests). I'm not sure if that's a good idea...

Renaming the directory might be an option though.

**Comment by ashgillman** [comment]
Why is that? Perhaps moving it to be a subdirectory of `/progressbar` is an option.

**Comment by WoLpH** [comment]
Because it would end up being called "tests" in your site-packages directory within your Python installation. That's far too generic and might conflict with other packages.

I personally find that moving test code within the code part of the package is a bit messy but it might be the best option

**Comment by ashgillman** [comment]
I may be wrong, but I don't believe that adding tests to the manifest will cause pip to propagate it to your site-packages upon installation

**Comment by WoLpH** [comment]
You're right, I confused the manifest with the package data :)

That should do the trick
