### ISSUE TITLE
Downloading bar even for smallest of sized downloads

### ISSUE THREAD

**Issue by tysondogerz** [WoLpH/python-progressbar#152]
How do I get around this?  I like the simplicity of this library, but is there a way to display loading bar even for small downloads or should I create a rule to only display bar if above a certain size?

**Comment by WoLpH** [comment]
It would depend on how you have the progress bar configured, it should display in most cases but definitely if you manually "finish" the progressbar.
```python
import time
import progressbar

bar = progressbar.ProgressBar(max_value=10)
bar.start()
for i in range(10):
    # do something
    sleep(0.1)
    bar.update(i + 1)
bar.finish()
```
