### ISSUE TITLE
Progress bar display does not update

### ISSUE THREAD

**Issue by durana** [WoLpH/python-progressbar#154]
#### Description

I found with the latest version on PyPI, 3.35.0, that a progress bar's display does not get updated until the end when it is finished.  I tested with the 3.34.3 version from PyPI, and this version updates the progress bar's display as expected.

#### Code

```python
#!/usr/bin/env python

import time
import progressbar

bar = progressbar.ProgressBar()
for i in bar(range(100)):
    time.sleep(0.02)
```

#### Versions

- Python version:
```
3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
```
- Python distribution/environment: Anaconda
- Operating System: macOS
- Package version: `3.35.0`

**Comment by JoeSc** [comment]
I have the same issue, simple example like
```
import time
import progressbar

bar = progressbar.ProgressBar()
for i in bar(range(100)):
    time.sleep(0.02)
```
does not update.  I bisected to 572854d7674c576bb744df586f842e563317bdb6

it appears the issue is with the update_delta near line 569 of bar.py

**Comment by WoLpH** [comment]
Thank you so much for tracking it down. I guess that change still has some
issues. I'll push out a new release tomorrow

**Comment by WoLpH** [comment]
Thanks for the help everyone, I've released a new version which fixes the issue

**Comment by JoeSc** [comment]
It seems there's still issues, Using this example code results in the progressbar from jumping from 20% to 100%.

```
import time
import progressbar

bar = progressbar.ProgressBar()
for i in bar(range(1000)):
    time.sleep(0.001)
```
See behavior here in this terminal recording
https://asciinema.org/a/qNiqvZyx85lwQUGAJ6titcLWk

The recording shows me running simple.py at the current HEAD and then reverting both e664f0481588cac7d2ee231a9aaba08110d21ec3 and 572854d7674c576bb744df586f842e563317bdb6.  After reverting it runs as expected with the progressbar progressing across the screen to 100%

**Comment by JoeSc** [comment]
I'm not quite sure how the underlying code works, but this change seems to fix the progressbar
https://gist.github.com/JoeSc/ef01c281318d99605ad4b49668f2b503

**Comment by WoLpH** [comment]
Thanks for the help guys, unfortunately this type of bug is hard to test for but I've put out a new release with the fixes similar to @JoeSc's changes :)
