### ISSUE TITLE
python2 with version 3.36.0 does not calculate ETA

### ISSUE THREAD

**Issue by JoeSc** [WoLpH/python-progressbar#157]
#### Description

using python2.7.6 and progressbar2-3.36.0 and the ETA is calculated as "N/A"

#### Code
```python
import time
import progressbar

bar = progressbar.ProgressBar()
for i in bar(range(100)):
    time.sleep(0.02)
```

#### Versions

- Python version:
>>> import sys; print(sys.version)
2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4]
&&
>>> import sys; print(sys.version)
2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010]

- Python distribution/environment: acquired via apt-get
- Operating System: Windows 10(bash) & Ubuntu Linux
- Package version: 3.36.0

**Comment by WoLpH** [comment]
Thanks for letting me know :)

I've extended the tests you provided to detect these issues as well.
