### ISSUE TITLE
No progressbar shown in 3.37.0

### ISSUE THREAD

**Issue by mattdowdell** [WoLpH/python-progressbar#165]
#### Description

An empty progressbar will be shown with N/A.

#### Code
```
from urllib.request import urlretrieve
from progressbar import ProgressBar, Percentage, Bar, Timer

pbar = ProgressBar(widgets=[Percentage(), Bar(), Timer()])

def dl_progress(count, block_size, total_size):
    pbar.update(int(count * block_size * 100 / total_size))

urlretrieve(uri, filepath, reporthook=dl_progress)
```

The code should download a file (`uri`) to the specified location (`filepath`). In this case I'm downloading an OVA file of 2.5GB

#### Versions

- Python version:
```
$ python3 -c "import sys; print(sys.version)"
3.4.5 (default, Dec 11 2017, 14:22:24) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```
- Python distribution/environment: CPython
- Operating System: CentOS 7 derivation (not publicly available, but CentOS7 should be close enough for the purposes of this).
- Package version: Happens on 3.37.0, not on 3.36.0.

**Comment by WoLpH** [comment]
The behaviour of the package has changed slightly between the two versions, the default maximum value of 100 makes little sense in most cases (even in your example you did a `* 100` to anticipate that) so it has been removed.

For your existing code the simplest fix is to specify `max_value=100` but I would suggest a slightly different solution with better output. You might want to change it a little to your needs but this should look nicer and shows the current average speed as well:
```python
from urllib.request import urlretrieve
from progressbar import ProgressBar, Percentage, Bar, Timer
import progressbar

pbar = ProgressBar(widgets=[
    progressbar.Timer(),
    ' ', progressbar.AdaptiveETA(),
    ' [', progressbar.Percentage(), '] ',
    progressbar.AdaptiveTransferSpeed(),
    ' ',
    progressbar.Bar(),
], min_value=0)


def dl_progress(count, block_size, total_size):
    # the max value only needs to be updated once, but it won't hurt
    # rewriting it and this is the first moment we can know its value
    pbar.max_value = total_size

    pbar.update(count * block_size)


uri = random.choice([
    'https://speed.hetzner.de/1GB.bin',
    'ftp://ftp.snt.utwente.nl/pub/test/1000M',
    'http://speedtest.xs4all.net/files/1GiB.bin',
])
filepath = '/dev/null'

urlretrieve(uri, filepath, reporthook=dl_progress)
```

**Comment by WoLpH** [comment]
Additionally, the `DataTransferBar` might offer a useful default for you :)
http://progressbar-2.readthedocs.io/en/latest/_modules/progressbar/bar.html#DataTransferBar
