### ISSUE TITLE
Examples script breaks at shortcut_example

### ISSUE THREAD

**Issue by XenonR** [WoLpH/python-progressbar#166]
#### Description

I'm unable to execute the provided example.py also `import progressbar; print(progressbar.__version__)` results in error (see section Versions below).
Already tried to reinstall from `progressbar2-3.37.1-py2.py3-none-any.whl` (was never working).
Additionally this was the first version installed.

#### Code
Copy&Paste from RAW:
https://github.com/WoLpH/python-progressbar/blob/develop/examples.py

#### Versions

- Python version: `3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]`
- Python distribution/environment: CPython
- Operating System: Debian 9 `4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64`
- Package version:
 ```# python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import progressbar; print(progressbar.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'progressbar' has no attribute '__version__'
```

#### pip3 list
- asn1crypto (0.23.0)
- bcrypt (3.1.4)
- beautifulsoup4 (4.5.3)
- bottle (0.12.13)
- cffi (1.9.1)
- chardet (2.3.0)
- colorama (0.3.7)
- cryptography (2.1.2)
- dnspython (1.15.0)
- elasticsearch (6.0.0)
- Glances (2.7.1)
- html5lib (0.999999999)
- httplib2 (0.9.2)
- idna (2.2)
- iotop (0.6)
- jabber-bot (0.1.1)
- jmespath (0.9.3)
- keyring (10.1)
- keyrings.alt (1.3)
- lxml (3.7.1)
- ntlm-auth (1.1.0)
- paramiko (2.3.1)
- pip (9.0.1)
- ply (3.9)
- progressbar2 (3.37.1)
- psutil (5.0.1)
- pyasn1 (0.3.7)
- pycparser (2.17)
- pycrypto (2.6.1)
- pycurl (7.43.0)
- pygobject (3.22.0)
- pykerberos (1.2.1)
- PyMySQL (0.7.11)
- PyNaCl (1.1.2)
- pyOpenSSL (16.2.0)
- pysnmp (4.3.2)
- python-apt (1.4.0b3)
- python-debian (0.1.30)
- python-debianbts (2.6.1)
- python-simplexml (0.1.5)
- python-utils (2.3.0)
- pyvmomi (6.5.0.2017.5.post1)
- pywinrm (0.3.0)
- pyxdg (0.25)
- PyYAML (3.12)
- reportbug (7.1.7)
- requests (2.12.4)
- requests-kerberos (0.12.0)
- requests-ntlm (1.1.0)
- SecretStorage (2.3.1)
- setuptools (33.1.1)
- six (1.10.0)
- urllib3 (1.22)
- webencodings (0.5)
- wheel (0.29.0)
- xmltodict (0.11.0)
- xmpppy (0.4.1)

Thanks.

**Comment by WoLpH** [comment]
You probably have some other file or library called `progressbar` which is conflicting.

Try this to find out what it's importing:

```python
import progressbar
print(progressbar)
```

**Comment by XenonR** [comment]
`<module 'progressbar' from '/opt/loc/progressbar.py'>`
*facepalm*
Thanks a lot, i feel stupid now.

**Comment by WoLpH** [comment]
I can't even tell you how often I've had similar issues, they're quite annoying ;)
