### ISSUE TITLE
Add easy way to label progressbar from iterator wrapper helper function

### ISSUE THREAD

**Issue by vaughnkoch** [WoLpH/python-progressbar#168]
I couldn't find a way to add a simple label to the progressbar, especially in the convenience function which greatly reduces code and thus makes it super easy to add a progressbar.

This is what the current default output is:
```
from progressbar import progressbar
for x in progressbar(range(100)):
    .. some code ..
# Outputs:
# 100% (100 of 100) |###################| Elapsed Time: 0:00:10 Time:  0:00:10
```
Is it possible to add something like this to add a default label?
```
for x progressbar(range(100), label='Foobar')
...
# Outputs:
# Foobar: 100% (100 of 100) |###################| Elapsed Time: 0:00:10 Time:  0:00:10
```
If this is already possible, please disregard - I looked and couldn't find a way to do this easily, including DynamicMessage.

My version: progressbar2==3.37.1, Python 3.6.4. 
P.S. I love this module, thanks for creating it.

**Comment by WoLpH** [comment]
You can work around it by manually specifying the widgets, but that doesn't help much I suppose so I've created a new version that allows for an optional prefix/suffix

```python
from progressbar import progressbar

for x in progressbar(range(100), prefix='Foobar: '):
    ...
```

**Comment by vaughnkoch** [comment]
Thanks!
