### ISSUE TITLE
math bugs with AdaptiveETA and AdaptiveTransferSpeed

### ISSUE THREAD

**Issue by UnsungHero97** [WoLpH/python-progressbar#17]
I'm writing a script for file transfers, and I'm seeing some math related exceptions being thrown when using AdaptiveETA and AdaptiveTransferSpeed. After looking into the code, I think these are the problems:

1. AdaptiveETA calculates `items = sample_vals[-1] - sample_vals[0]`, and then tries to do division with this value `per_item = duration / items`. In my testing, `items` turns out to be `0`, so the division fails since you can't do division by zero. Locally, I fixed the issue by doing this:

        if (items == 0):
          return ETA._eta(self, pbar)

2. AdaptiveTransferSpeed calculates `speed = items / duration`, and then tries to do some math `power = int(math.log(speed, 1000))`. In my testing, printing out the value `speed` prints  `-0.0`. Locally, I fixed the issue by doing this:

        if (speed <= 0):
          return FileTransferSpeed._speed(self, pbar)

Do these seem like reasonable solutions? If so, will these bugs be fixed sometime soon?

**Comment by WoLpH** [comment]
There's still another issue open from @Midnighter who planned to make some modifications to the ETA widgets: https://github.com/WoLpH/python-progressbar/issues/12

How can you have 0 items though? Can you explain how you call the progressbar?

**Comment by UnsungHero97** [comment]
Here's how I use it...

    theProgressBar = None
    WIDGETS = [
      ' ', Percentage(),
      ' ', FilesCounter(),
      ' ', Bar(marker='=', left='[', right=']'),
      ' ', AdaptiveETA(),
      ' ', FileTransferSpeed()
    ]
    ...
    theProgressBar = ProgressBar(
      maxval = fileSize, # in bytes
      widgets = WIDGETS,
    )
    theProgressBar.start()
    ...
    theProgressBar.update(bytesRead)
    ...
    theProgressBar.finish()

I copied over the AdaptiveETA class locally, and added some print statements. When I print out `sample_vals`, I see this:

    sample_vals: [8192, 16384, 24576, 32768, 40960, 46471, 8192]

Since the calculation is `items = sample_vals[-1] - sample_vals[0]`, it looks like it's doing `8192-8192=0`.

**Comment by WoLpH** [comment]
Good example, that's indeed pretty broken. I should have some time next week, I'll give the widgets a big overhaul and use some defensive programming :)

The entire project is originally not mine and is a bit of a patch on a patch on a patch... it's time for a major rewrite. Stay tuned :)

**Comment by UnsungHero97** [comment]
Awesome!

Just to be clear... referring back to my original post... both `AdaptiveETA` and `AdaptiveTransferSpeed` are giving me problems. I gave you an example for what `AdaptiveETA` is doing, but not for `AdaptiveTransferSpeed`. So I hope you fix both widgets :)

**Comment by WoLpH** [comment]
Yeah, I'll do a rewrite of all of the widgets :)

The entire widget architecture has issues, they all need a rewrite ;)

**Comment by WoLpH** [comment]
Still working on all of these within the full-rewrite branch (https://github.com/WoLpH/python-progressbar/tree/full-rewrite), but it's quite a bit of work :)

**Comment by WoLpH** [comment]
The new version should fix it all :)
