### ISSUE TITLE
Support for sub-progress widgets?

### ISSUE THREAD

**Issue by EricG-Personal** [WoLpH/python-progressbar#180]
#### Description

In my case, I need to download many large files. So, I can have a progress bar with an adaptive ETA tracking the ETA as each file completes. However, what I would like to be able to do is add a widget that tracks the percent compete of the files themselves.

An example of what this might look like is:

50% |######      |file: 10% | ETA: 2:24:00

So, what this bar would be telling me is that I have downloaded 50% of my files. The current file, which is downloading is 10% complete. To finish downloading all of the files will take another 2 hours and 24 minutes.

Is this possible?

I am not sure how I can send information to the file % widget and keep the data separate from the surrounding Progressbar.

If this is not possible, consider it a feature request.

**Comment by WoLpH** [comment]
Effectively it comes down to this issue: https://github.com/WoLpH/python-progressbar/issues/176

For the time being it's not supported yet, but it's on the todo list. I expect to have time to work on this in a few weeks. It shouldn't be that hard anymore, a reasonable example of how it can be done has been shown in kdschlosser's comment in that issue.

**Comment by WoLpH** [comment]
Closing in favour of #176
