### ISSUE TITLE
Make release with fix for WRAP_STDOUT/ERR

### ISSUE THREAD

**Issue by ikonst** [WoLpH/python-progressbar#181]
The issue is fixed here in master branch:
https://github.com/WoLpH/python-progressbar/commit/5df7e08edb1b6d0524ec82bf45ef929d343975cb
(not fixed on develop branch)

**Comment by WoLpH** [comment]
Sorry about that, I've had to deal with some work-related emergencies the last few weeks so I hadn't gotten to making another release. It's merged now and I'm creating a new release :)
