### ISSUE TITLE
Python 3.6.5 TypeError even when using example codes

### ISSUE THREAD

**Issue by Chadhendrixs** [WoLpH/python-progressbar#183]
#### Description

No matter what progressbar command is run in terminal (Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32) the same re-occurring error will appear when running any example codes, and/or copying example codes to terminal: 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable`

I have yet to find a solution to this issue, nor have I figured out how to solve it as it even occurs when running examples.py

#### Code

```
>>> for i in progressbar.progressbar(range(100)):
     time.sleep(0.02)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
```

---

```
>>> import time
>>> import progressbar
>>>
>>> widgets=[
     ' [', progressbar.Timer(), '] ',
     progressbar.Bar(),
     ' (', progressbar.ETA(), ') ',
 ]
>>> for i in progressbar.progressbar(range(20), widgets=widgets):
     time.sleep(0.1)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
```

---

Now either there's an easy solution and I'm just an idiot, or something's pretty broken.

#### Versions

- Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
- Python distribution/environment: Windows CMD (Pretty sure that's all the information given for this spot)
- Operating System: Windows 10
- Package version: 2.5

**Comment by WoLpH** [comment]
The easy solution is probably to run it from a python file instead of an python shell session. 

It does look like a bug though, I'll investigate.

**Comment by Chadhendrixs** [comment]
Running it in from a file also is displaying the same error, after further testing. I used an example script (adjusted it to print the error before crashing), and this was the output.

####Code:
```
import os
import time
import progressbar

try:
    for i in progressbar.progressbar(range(100)):
        time.sleep(0.02)
except Exception as e:
    print(e)

os.system('pause')
```
####Result:
```
'module' object is not callable
Press any key to continue . . .
```
---
Same version information as before.

**Comment by WoLpH** [comment]
I found the issue, you're not using this package but the badly maintained project this was forked from: https://pypi.org/project/progressbar/

To fix it, simply do `pip uninstall -y progressbar` followed by a `pip install progressbar2`

I'm not sure about the state of the other project, when I forked it back in 2012 it hadn't had any updates or responses on bug reports for over 2 years. It seems that the developer has given it a small spurt of activity but it appears dead once again.
