### ISSUE TITLE
Progressbar does not update

### ISSUE THREAD

**Issue by 1117x** [WoLpH/python-progressbar#185]
#### Description

update() does not update the progressbar when no Timer() (or ETA() etc.) widget is used. 

#### Code

    import progressbar, time
    widgets = [progressbar.Percentage(), progressbar.Bar()]
    bar = progressbar.ProgressBar(widgets=widgets, max_value=100).start()
    for i in range(100):
        time.sleep(0.5)
        bar.update(i)

Always shows

    N/A%|                                                                            |

If i use `bar.update(i, force=True)` it works as expected. If i change the second line to

    widgets = [progressbar.Percentage(), progressbar.Bar(), progressbar.Timer()]

it's also works as expected.

#### Versions

- Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
- Python distribution/environment: CPython
- Operating System: Ubuntu Linux
- Package version: 3.39.2

**Comment by WoLpH** [comment]
It appears that this was broken at some point and slipped through the tests because they mostly check timed variants. I've added an extra test and fixed the bug :)

I'll release a new version once travis is done

**Comment by 1117x** [comment]
Thank you very much! :)
