### ISSUE TITLE
Use collections.abc if available

### ISSUE THREAD

**Issue by llchan** [WoLpH/python-progressbar#186]
#### Description

Description of the problem
```
[...]/progressbar/bar.py:50: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working                                                                                                                                           
  class ProgressBarBase(collections.Iterable, ProgressBarMixinBase):
```

#### Versions

- Python version: 3.7.1
- Python distribution/environment: CPython
- Operating System: Linux
- Package version: 3.39.2

**Comment by WoLpH** [comment]
I've fixed it on dev :)

**Comment by mithro** [comment]
Hi @WoLpH,

Any idea when this will end up in a PyPi published version of progressbar2?

Thanks for your awesome work!

Tim '@mithro' Ansell

**Comment by WoLpH** [comment]
Sorry about that, it slipped my mind. I've created a new release :)

**Comment by WoLpH** [comment]
@mithro Sorry about that, it slipped my mind. I've created a new release :)
