### ISSUE TITLE
TypeError: progressbar() missing 1 required positional argument: 'iterator'

### ISSUE THREAD

**Issue by 50417** [WoLpH/python-progressbar#187]
#### Description

 I followed the file_transfer_example from the [examples](https://progressbar-2.readthedocs.io/en/latest/examples.html) and get the error 

> TypeError: progressbar() missing 1 required positional argument: 'iterator'

#### Code

If applicable, code to reproduce the issue and/or the stacktrace of the issue
```
import time
import progressbar

widgets=[
	' [', progressbar.Timer(), '] ',
	progressbar.Bar(),
	' (', progressbar.ETA(), ') ',
]
example_list=[1,2,3,4,5]
bar = progressbar.progressbar(max_value = len(example_list), widgets=widgets).start()
bar_counter =0 
for i in example_list:
	bar_counter+=1
	bar.update(bar_counter)
```
#### Versions

- Python version:3.6
- Python distribution/environment:Anaconda
- Operating System: Ubuntu Linux | Mac OSX
- Package version: 3.39.3

**Comment by WoLpH** [comment]
While the code is similar you've made a tiny mistake while copying. You're using the `progressbar.progressbar` shorthand instead of the `progressbar.ProgressBar` class :)

**Comment by 50417** [comment]
Thanks for looking into it. 
I thought so too. I got the following error: 
`AttributeError: module 'progressbar' has no attribute 'Progressbar'`

**Comment by WoLpH** [comment]
`ProgressBar` (note the capital `B`)

**Comment by 50417** [comment]
I should have copy pasted instead of typing. Sorry about this .
