### ISSUE TITLE
DynamicMessage can't handle strings

### ISSUE THREAD

**Issue by DarkRedman** [WoLpH/python-progressbar#193]
### Description

I prefered to use DynamicMessage instead of FormatCustomText because it's easier to set up.
so I added a DynamicMessage widget and update its value with a string, and I get an error that the g format code doesn't work with an str

`ValueError: Unknown format code 'g' for object of type 'str'`

#### Code

```python
import progressbar, time

widgets = [
    progressbar.Percentage(),
    progressbar.Bar(),
    progressbar.DynamicMessage('user'),
]
with progressbar.ProgressBar(max_value=100, widgets=widgets) as bar:
    for i in range(100):
        bar.update(i, user='me')
        time.sleep(0.2)`
```

#### Versions

- Python version: 3.7.3 (default, Mar 26 2019, 21:43:19) 
[GCC 8.2.1 20181127]
- Python distribution/environment: CPython
- Operating System: Antergos (Arch Linux)
- Package version: 3.39.3

### Solution

In order to fix it I changed the code of function __call__ of DynamicMessage like this

```python
def __call__(self, progress, data):
    val = data['dynamic_messages'][self.name]
    if val:
            if isinstance(val,str):
                return self.name + ': ' + '{:6s}'.format(val)
            else:
                return self.name + ': ' + '{:6.3g}'.format(val)
    else:
        return self.name + ': ' + 6 * '-'
```

**Comment by WoLpH** [comment]
I've released a new version that supports strings as well :)

https://github.com/WoLpH/python-progressbar/blob/7075248b3320270116028be08fc5866b3847771c/examples.py#L439-L455

**Comment by DarkRedman** [comment]
That's so cool, congratulations ! :+1:
