### ISSUE TITLE
Progressbar not updating in Docker

### ISSUE THREAD

**Issue by halfdanrump** [WoLpH/python-progressbar#197]
#### Description

Progressbar doesn't work as expected in Docker. Updates are not printed until the entire iterator wrapped in progressbar is finished. 

I'm using the stdlib logging module, and following the instructions [Progressbars with logging](https://pypi.org/project/progressbar2/). 

- calling `progressbar.streams.wrap_stderr()` before initializing `StreamHandler`
- setting env var `WRAP_STDERR=true`
- calling `progressbar.streams.flush()` at the very top of my script, and after each iteration in the iterator

The above doesn't seem to do the trick though. 

Progressbar works fine when running outside of Docker by the way

#### Code

Can post if needed.

#### Versions

- Python version: `3.7.3`
- Python distribution/environment: vanilla
- Operating System: OSX 10.13.6
- Package version:  `progressbar2==3.42.0`

**Comment by WoLpH** [comment]
I can't say I've ever tried to run it in a docker but it seems to be a common problem: https://stackoverflow.com/questions/39486327/stdout-being-buffered-in-docker-container

My guess after reading a little bit in the docker docs is that reducing the `max-buffer-size` could help a bit. But that will slow down your output. 

Additionally, to get a working progressbar it is important to run docker with the tty flag. So something like: `docker run -t ...`
