### ISSUE TITLE
Using AnimatedMarker as a Marker in a Progressbar

### ISSUE THREAD

**Issue by Xevion** [WoLpH/python-progressbar#199]
#### Description

The `progressbar.AnimatedMarker` widget does not display properly when used in `progressbar.Bar`.

I have tested in VS Code's terminal as well as a separate Windows Command Prompt.

The documentation is pretty sparce and code I've found online did not work for me.

What am I doing wrong?

#### Code

```python
import progressbar, time
widgets = [progressbar.Percentage(), ' ', progressbar.Bar(marker=progressbar.AnimatedMarker()),]
for i in progressbar.progressbar(range(50), widgets=widgets):
    time.sleep(0.1)
```

#### Versions

- Python version: `3.7.0`
- Python distribution/environment: `Anacoda (conda 4.7.10)`
- Operating System: `Windows 10`
- Package version: `3.42.0`

**Comment by WoLpH** [comment]
It depends on what you are expecting I think. What kind of progressbar are you looking for exactly? 

It appears to work for me, here's a screencast:
https://recordit.co/c41Q49ZQHA
![screencast](http://g.recordit.co/c41Q49ZQHA.gif)

It does appear that there is a bug with the animated markers at the moment so I'll have to investigate that. A few of the animated examples aren't actually animating anymore.

**Comment by Xevion** [comment]
I was hoping that the marker would move along and the rotating head would
stay at the end. Is there anything like that? The bar being filled and the
marker moving along to the end...

**Comment by WoLpH** [comment]
I've added support for that in the latest release :)

https://github.com/WoLpH/python-progressbar/blob/develop/examples.py#L195-L203

Once all of the tests have been run I'll push the version to PyPI

**Comment by Xevion** [comment]
Very cool, thanks. Progress bars are definitely coming along now.

**Comment by rsalmei** [comment]
Have you seen my progressbar?
I have very cool animations: https://github.com/rsalmei/alive-progress
