### ISSUE TITLE
3.43.1: test_monitor_progress.py unable to find progressbar module

### ISSUE THREAD

**Issue by dvzrv** [WoLpH/python-progressbar#201]
#### Description

Hi! I'm currently packaging python-progressbar for Arch Linux.
During packaging of 3.43.1 I'm attempting to run the tests using pytest, but I'm running into issues with the tests in `tests/test_monitor_progress.py`. I think they are happening, because those tests don't honor the `$PYTHONPATH` environment variable.

The build/ test output is here: 
[python-progressbar-3.43.1-check.log](https://github.com/WoLpH/python-progressbar/files/3547269/python-progressbar-3.43.1-check.log)

#### Code

```
rm -v pytest.ini
python setup.py build
export PYTHONPATH="${PWD}/build:${PYTHONPATH}"
py.test                            
```

Currently I have to disable a few tests because of this behavior, when running py.test:

```
py.test -k 'not test_non_timed \                                                                                                                                                            
                and not test_context_wrapper \
                and not test_rapid_updates \
                and not test_generator_example \
                and not test_list_example'
```

#### Versions

- Python version: 3.7.4
  - python-pytest: 5.1.1
  - python-freezegun: 0.3.12
  - python-utils: 2.3.0
  - python-sphinx: 2.2.0
  - python-six: 1.12.0
- Python distribution/environment: Python
- Operating System: Arch Linux
- Package version: 3.43.1

**Comment by WoLpH** [comment]
Those tests are integration tests, they're basically a failsafe for me just to make sure the actual output is still correct. Since it's highly unlikely to be broken only on arch and not the other Linux distros the package is tested on, I think you can safely skip it :)

I think you could simply do: `py.test --ignore tests/test_monitor_progress.py` instead

Having that said though, I would prefer to fix it properly. Can you tell me a bit about how the tests are being run? Normally they're run after a `pip install -e .` which should take care of these issues. But it wouldn't be impossible to append `sys.path` in the testscript. A `import sys; sys.path.append(...)` right here should do the trick: https://github.com/WoLpH/python-progressbar/blob/develop/tests/test_monitor_progress.py#L17

I'm trying to decide the least hacky option here :P

**Comment by WoLpH** [comment]
@dvzrv I've just added the progressbar path to the `sys.path`, can you check if that works for you?

**Comment by dvzrv** [comment]
@WoLpH I'll sure test it!
I just realized, that the last two releases are not on pypi (yet), which I use for checking for new releases of progressbar.
As soon as it's there, I'll test! :)

**Comment by WoLpH** [comment]
Sounds good. I'm finishing up on some new tests and I'm planning to release somewhere today.

The split Github releases are mostly for keeping the separate features split right now since they're rather large changesets. The (hopefully) fully tested ones make it to PyPI.

**Comment by WoLpH** [comment]
The new release is on PyPI :)

**Comment by dvzrv** [comment]
Works for me!
Only a couple of warnings:

```
=============================== warnings summary ===============================
/usr/lib/python3.7/site-packages/_pytest/mark/structures.py:324
  /usr/lib/python3.7/site-packages/_pytest/mark/structures.py:324: PytestUnknownMarkWarning: Unknown pytest.mark.no_freezegun - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html                                                                                                         
    PytestUnknownMarkWarning,                                         
                                                                                           
tests/test_progressbar.py::test_original_examples[wrapped0]   
tests/test_progressbar.py::test_original_examples[wrapped1]           
tests/test_progressbar.py::test_original_examples[wrapped2]                                                                                                                                                                                                                                                                                                                 
tests/test_progressbar.py::test_original_examples[wrapped3]                                                                                                                                                                                                                                                                                                                 
tests/test_progressbar.py::test_original_examples[wrapped4]                                                                                                                                                                                                                                                                                                                 
tests/test_progressbar.py::test_original_examples[wrapped5]                                                                                                                                                                                                                                                                                                                 
tests/test_progressbar.py::test_original_examples[wrapped8]
tests/test_progressbar.py::test_original_examples[wrapped18]                                                                                                                                                                                                                                                                                                                
tests/test_progressbar.py::test_original_examples[wrapped20]                    
  /build/python-progressbar/src/python-progressbar-3.46.0/progressbar/bar.py:295: DeprecationWarning: The usage of `maxval` is deprecated, please use `max_value` instead             
    '`max_value` instead', DeprecationWarning)                                                                                                                                        
                                                                                           
-- Docs: https://docs.pytest.org/en/latest/warnings.html                                   
======================= 200 passed, 10 warnings in 3.67s =======================                                                                   ```

Thanks for looking into this!

**Comment by WoLpH** [comment]
I've removed the first warning (leftover from writing new kinds of tests). The other ones are expected, they're the tests from the original progressbar library which used a slightly different syntax.

Nothing to worry about in either case :)
