### ISSUE TITLE
stderr is closed

### ISSUE THREAD

**Issue by artgoldberg** [WoLpH/python-progressbar#202]
#### Description

`progressbar` doesn't work with our testing system because it finds `stderr` closed

#### Code

Here, `SimulationProgressBar()` is just a simple wrapper around `ProgressBar`. I can share it with you.

    ___________________________________________ TestUtilities.test_progress ____________________________________________

    self = <test_utilities.TestUtilities testMethod=test_progress>

        @unittest.skipIf(sys.stderr.closed, 'progress tests fail if stderr is closed')
        def test_progress(self):
            unused_bar = SimulationProgressBar()
            self.assertEqual(unused_bar.start(1), None)
            self.assertEqual(unused_bar.progress(2), None)
            self.assertEqual(unused_bar.end(), None)
    
            used_bar = SimulationProgressBar(True)
            with CaptureOutput(relay=False) as capturer:
                duration = 20
    >           self.assertEqual(used_bar.start(duration), None)

    tests/test_utilities.py:53: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    de_sim/utilities.py:52: in start
        self.bar = ProgressBar(max_value=end_time).start()
    /usr/local/lib/python3.6/site-packages/progressbar/bar.py:661: in start
        self.update(self.min_value, force=True)
    /usr/local/lib/python3.6/site-packages/progressbar/bar.py:594: in update
        StdRedirectMixin.update(self, value=value)
    /usr/local/lib/python3.6/site-packages/progressbar/bar.py:147: in update
        self.fd.write('\r' + ' ' * self.term_width + '\r')
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    self = <_pytest.capture.EncodedFile object at 0x7f468d6edba8>
    obj = b'\r                                                                                                                    \r'

        def write(self, obj):
            if isinstance(obj, six.text_type):
                obj = obj.encode(self.encoding, "replace")
            elif _PY3:
                raise TypeError(
                    "write() argument must be str, not {}".format(type(obj).__name__)
                )
    >       self.buffer.write(obj)
    E       ValueError: I/O operation on closed file

#### Versions

- Python version: `3.6.8`
- Python distribution/environment: CPython, I think
- Operating System: Ubuntu Linux
- Package version: `3.43.1`

**Comment by artgoldberg** [comment]
The problem may be in this code:

    class DefaultFdMixin(ProgressBarMixinBase):

        def __init__(self, fd=sys.stderr, **kwargs):

which sets `fd` once at compile time, and never changes it afterwards unless `__init__` is called with a new value for `fd`. I can check on it.

Arthur

**Comment by WoLpH** [comment]
By default it actually references `progressbar.utils.streams.original_stderr`. 

https://github.com/WoLpH/python-progressbar/blob/86a28c9d01c731c04687b43b11f042ca2bd11403/progressbar/bar.py#L59-L66

Looking at your code I'm guessing it _might_ (not sure) work if you move `used_bar = ...` within the `with CaptureOutput(...)` block. If that doesn't work either, you can always replace `fd` by doing `bar.fd = sys.stderr` (or any other writable object).

**Comment by artgoldberg** [comment]
Hi Rick

Thanks for your quick reply. These changes to `DefaultFdMixin` enable my code to work:

     from . import utils
    -
    +from .utils import StreamWrapper
 
     logger = logging.getLogger(__name__)
 
    @@ -56,12 +56,14 @@ class ProgressBarBase(abc.Iterable, ProgressBarMixinBase):
 
     class DefaultFdMixin(ProgressBarMixinBase):
 
    -    def __init__(self, fd=sys.stderr, **kwargs):
    +    def __init__(self, fd=None, **kwargs):
    +        fd = sys.stderr if fd is None else fd
    +        streams = StreamWrapper()
             if fd is sys.stdout:
    -            fd = utils.streams.original_stdout
    +            fd = streams.original_stdout
 
             elif fd is sys.stderr:
    -            fd = utils.streams.original_stderr
    +            fd = streams.original_stderr
 
             self.fd = fd
             ProgressBarMixinBase.__init__(self, **kwargs)

However, they make some of your tests fail, so they're not a solution.

My idea is that `progressbar` and other programs that use it may all manipulate `stderr` and `stdout`. `progressbar` could minimize its conflicts with these other programs by grabbing the current `stderr` and `stdout` from `sys` as late as possible -- when a `ProgressBar` or other type of bar is instantiated -- rather than before that.

E.g., I made a similar change to `progress` with this [commit](https://github.com/KarrLab/progress/commit/e249fd6c8d1fecf6a5262a71aeec62b074f909fa) which works with our testing framework and does not harm `progress`. But your progress bar has more functionality because it simultaneously shows progress toward the final value (I'm running simulations) and the ETA for completion.

Unfortunately, I don't have time to develop this further, but would gladly test any solutions you offer.

Regards
Arthur

the conflicts between it and

**Comment by WoLpH** [comment]
The problem is that progressbar needs to grab them really soon to be able to work together with logging. That's the reason for grabbing it so early.

Perhaps a recapture method could help here, but I can see very few use cases where this is beneficial. Capturing and replacing the output to work together with regular output is one of the more useful features of this progressbar.

**Comment by artgoldberg** [comment]
Thanks Rick. I had presumed that `progressbar` deliberately grabbed and held onto `stderr` for a long time. For now I'll simply catch and ignore `I/O operation on closed file` exceptions that occur during testing.
