### ISSUE TITLE
Elapsed time starts at 3:00:00

### ISSUE THREAD

**Issue by paulo-raca** [WoLpH/python-progressbar#209]
#### Description

Elapsed time is offset by 3 hours.

I wonder if my timezone (UTC-3) is related to this bug.

I traced this to f6ad27fff3e6c

#### Code

Just running examples.py:

```
$ python3 ~/Workspace/python-progressbar/examples.py 
Running: shortcut_example
100% (10 of 10) |###########| Elapsed Time: 3:00:01 Time:  3:00:01

Running: prefixed_shortcut_example
Hi: 100% (10 of 10) |#######| Elapsed Time: 3:00:01 Time:  3:00:01

Running: templated_shortcut_example
100% (10 of 10) |######| Elapsed Time: 3:00:01 Time:  3:00:011e+00

Running: with_example_stdout_redirection
Some print statement 0
Some print statement 3                                            
Some print statement 6                                            
Some print statement 9                                            
100% (10 of 10) |###########| Elapsed Time: 3:00:01 Time:  3:00:01
```

#### Versions

- Python version: 3.7.3 (default, Aug 20 2019, 17:04:43) [GCC 8.3.0]
- Python distribution/environment: OS distribution
- Operating System: Ubuntu 19.04
- Package version: 3.46.0

**Comment by WoLpH** [comment]
Yeah, it's definitely related. I had something similar while testing and I thought I had fixed it... apparently not. I'll revert that fix.

**Comment by WoLpH** [comment]
It's fixed :)

Turns out that the issue I noticed is related to [freezegun](https://github.com/spulec/freezegun). It fixed some tests for me (locally) but it broke other stuff obviously :)

**Comment by paulo-raca** [comment]
Thanks!

**Comment by WoLpH** [comment]
I've opened an issue upstream but I don't expect a fix from freezegun any time soon. The developer seems to be busy with other stuff
https://github.com/spulec/freezegun/issues/309
