### ISSUE TITLE
progressbar is printed multipletimes in Jupyter notebook 

### ISSUE THREAD

**Issue by vvvlc** [WoLpH/python-progressbar#211]
#### Description
Progressbar is printed multiple times in jupyter notebook
![Snímek obrazovky pořízený 2019-09-30 07-26-57](https://user-images.githubusercontent.com/15854496/65851666-090b3c00-e354-11e9-9dda-aec9fcc06443.png)

#### Code
```python
import time
import progressbar
import sys

print(progressbar.__version__)
sys.stdout.flush()
for i in progressbar.progressbar(range(100)):
    time.sleep(0.02)
```

#### Versions

- Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
- Python distribution/environment: CPython/Anaconda/IPython/IDLE
- Operating System: Ubuntu Linux
- Package version: 3.46.1
  - 3.43.1 works fine, 
  - 3.45.1 introduces this problem (installed via pip)

**Comment by WoLpH** [comment]
Thanks for letting me know :)
I was worried this would happen at some places with the terminal detection patch, but luckily jupyter is simple enough to test for.

Can you verify that the dev release works for you again?

**Comment by vvvlc** [comment]
I tested https://github.com/WoLpH/python-progressbar/releases/tag/vv3.47.0 it issue is gone, thx for your fix.
