### ISSUE TITLE
Empty lines in jupyter lab / notebook

### ISSUE THREAD

**Issue by kallewesterling** [WoLpH/python-progressbar#213]
#### Description

When iterating over many tweets in my own package, using `progressbar`, it generates a number of empty lines in the `jupyter lab` notebook. Picture here:

<img width="452" alt="Screen Shot 2019-11-02 at 2 45 47 PM" src="https://user-images.githubusercontent.com/7298727/68075551-79f0aa00-fd7f-11e9-9f32-49b5a37bc52b.png">

#### Code

```python
class TweetSet():
    def __init__(self, ids=[], suppress_warnings=False):
        self.suppress_warnings = suppress_warnings
        self.ids = ids
        self.tweets = []
        
        bar = progressbar.ProgressBar(max_value=len(self.ids)).start()
        for i, id in enumerate(ids):
            bar.update(i)
            tweet = Tweet(id, suppress_warnings=self.suppress_warnings)
            self.tweets.append(tweet)
        bar.finish()
```

#### Versions

- Python version: 3.7.1 (default, Nov 15 2018, 16:13:06) [Clang 10.0.0 (clang-1000.11.45.5)]
- Python distribution/environment: IPython
- Operating System: Mac OS X 10.15
- Package version: 3.38.0

**Comment by WoLpH** [comment]
Are you sure that nothing in your code is printing/logging those?
It's not impossible for this to happen but I can't reproduce it myself.

Also, you've got a fairly old version, you might want to upgrade to the latest release :)
