### ISSUE TITLE
Bar stops being drawn at 98%~

### ISSUE THREAD

**Issue by danielocdh** [WoLpH/python-progressbar#216]
#### Description

Bar stops being drawn at 98%~ when using it without iterator/context, but it works fine if I pass a value to the `term_width` parameter

#### Code
```python
amount = 200
bar = progressbar.ProgressBar(min_value=0, max_value=amount)
for i in range(amount):
    time.sleep(0.01)
    bar.update(i)
```
It works fine if I change the `bar` line to
```python
bar = progressbar.ProgressBar(min_value=0, max_value=amount, term_width=119)
```

#### Versions

- Python version: 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
- Python distribution/environment: conda 4.7.12/Python 3.7.5
- Operating System: Windows 10
- Package version: 3.47.0

**Comment by WoLpH** [comment]
The problem is that you're not actually finishing the bar currently. You've specified the `max_value` to be `200` but you're only sending up to `199`.

The `range` method doesn't include the last number, a `range(5)` returns `[0, 1, 2, 3, 4]` which doesn't include `5` :)

**Comment by danielocdh** [comment]
> The problem is that you're not actually finishing the bar currently. You've specified the `max_value` to be `200` but you're only sending up to `199`.
> 
> The `range` method doesn't include the last number, a `range(5)` returns `[0, 1, 2, 3, 4]` which doesn't include `5` :)

Silly me(still learning), still, my original example gets stuck at 98% (197 of 200) but it reaches "(200 of 200)" when only adding `term_width=119`. I believe the pause being too short is causing the issue. I used `bar.finish()` on my real code and it works fine (for the 197 of 200 case).

After further examination I think there is at least 1 bug. I add some examples with their resulting bar:

```
#prints 200 of 200 but, should stop on 150?
import progressbar
import time

amount = 200
bar = progressbar.ProgressBar(min_value=0, max_value=amount, term_width=119)
for i in range(amount + 1 - 50):
    time.sleep(0.01)
    bar.update(i)
100% (200 of 200) |##############################################################| Elapsed Time: 0:00:01 Time:  0:00:01
```
```
#my guess is that bar.finish() has to be used for "fast" loops, not sure
import progressbar
import time

amount = 200
bar = progressbar.ProgressBar(min_value=0, max_value=amount)
for i in range(amount + 1):
    time.sleep(0.01)
    bar.update(i)
 98% (197 of 200) |############################################################# | Elapsed Time: 0:00:02 ETA:   0:00:00
```
```
#working fine on a slower loop
import progressbar
import time

amount = 200
bar = progressbar.ProgressBar(min_value=0, max_value=amount)
for i in range(amount + 1):
    time.sleep(0.1)
    bar.update(i)
100% (200 of 200) |##############################################################| Elapsed Time: 0:00:20 ETA:  00:00:00
```

**Comment by WoLpH** [comment]
You're right, that looks wrong.
For performance reasons we try to avoid updating in all cases (for example, when using it as a download progressbar a 1 gigabyte file will give you 1 billion updates). But it should always finish when it reaches the end.

I'll investigate :)

**Comment by WoLpH** [comment]
I've done a bit more research and it's not a bug, it's a feature... yes, really ;)
The "bug" was introduced when the hard `max_value` limit was removed: https://github.com/WoLpH/python-progressbar/issues/142

The "proper" solution here is to either call `bar.finish()` once you're done. Or pass the iterator as an argument to the progressbar:
```
#my guess is that bar.finish() has to be used for "fast" loops, not sure
import progressbar
import time

amount = 200
bar = progressbar.ProgressBar(min_value=0, max_value=amount)
for i in bar(range(amount)):
    time.sleep(0.01)
```
