### ISSUE TITLE
Is the code in this repo the most recent code?

### ISSUE THREAD

**Issue by kikones34** [WoLpH/python-progressbar#217]
If you install the package from pypi, the version in `__about__.py` is `3.47.0`, however, in this repo the version is `3.46.1`.
I wanted to make a small contribution, but it worries me that this might not be the newest version of the code.

**Comment by WoLpH** [comment]
Yes, it's the most recent version except for a git snafu. No worries

**Comment by kikones34** [comment]
Oh, alright, thanks for clarifying!
