### ISSUE TITLE
progress bar updates too fast

### ISSUE THREAD

**Issue by UnsungHero97** [WoLpH/python-progressbar#22]
I'm using the progress bar to show progress for a file transfer. The progress bar works just fine, but it's updating too fast. In the image, the estimated time and estimated transfer speed are being updated really quickly, which causes a flickering effect.

![screen shot 2015-01-22 at 11 58 02 pm](https://cloud.githubusercontent.com/assets/440299/5871458/a347c980-a292-11e4-995b-b97a71497163.png)

Is there a way to get it to update at a fixed interval, or at least less frequently?

**Comment by WoLpH** [comment]
For time sensitive widgets such as the ETA you can increase the `poll=0.1` parameter for the progressbar (https://github.com/WoLpH/python-progressbar/blob/master/progressbar/__init__.py#L132).

If you are not using time sensitive widgets you can use the `update_interval` property instead: https://github.com/WoLpH/python-progressbar/blob/master/progressbar/__init__.py#L169

**Comment by UnsungHero97** [comment]
Thanks!
