### ISSUE TITLE
Progress bar prints unwanted characters to the console

### ISSUE THREAD

**Issue by Klavionik** [WoLpH/python-progressbar#220]
First of all, thanks for the great lib! 
I'm getting a small problem. I know that the subject sounds rather vague, I'll try my best to explain.
I'm kind of new to Python, so maybe this has more relation with Python in general, than just with the library.

#### Description

I took an example of the filling animated progress bar from the official docs and tried to modify it a bit to make it colorful using ANSI escape characters. Here is my code:

```def progress_bar(text):
    """
    Displays a fancy progress bar.

    :param text: Progress bar text
    :return: Progress bar object
    """
    V = '\033[38;5;31m'
    END = '\033[0m'
    bar = \
        progressbar.ProgressBar(widgets=[f'{V}{text}{END}', progressbar.Percentage(),
        progressbar.Bar(marker=progressbar.AnimatedMarker(fill=f'{V}#{END}'))])
    return bar
```

But when I do that, I observe a weird side-effect. I took a short screencast to make it easier to understand: https://youtu.be/p_YpkbJrTa8

At **0:05** you can see that the cursor leaves a few blue ```|``` characters in the console when updating the bar and the animation after the hash sign is bugged. However, if I keep the hash sign colorless, everything looks just fine (see **0:35**).

You can also see, that in the first case the cursor jumps to the hast sign every time it updates and in the second case it stays at the rightmost position.

So, is there a way to fix that, so that the hash sign stays colorful and animated, but there are no unwanted ```|``` characters in the console?

I was able to kinda fix that, wrapping the markers which constitute the animation with the same ANSI color codes.
``` 
   V = '\033[38;5;31m'
   END = '\033[0m'
   bar = \
        progressbar.ProgressBar(widgets=[f'{V}{text}{END}', progressbar.Percentage(),
        progressbar.Bar(marker=progressbar.AnimatedMarker(markers=f'{V}|/-\\{END}', 
                                                          fill=f'{V}#{END}'))])
    return bar
```

Now the ```|``` character stays at the rightmost position, where it belongs, but the animation is still kind of broken. I made another screencast to demonstrate that: https://youtu.be/t2YwlBQxcN0

Looks like the hyphen character is missing and sometimes the animated marker becomes colorless (see **0:09** and especially **0:21**).

#### Versions

- Python version: 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]
- Python distribution/environment: CPython
- Operating System: Windows 10
- Package version: 3.47.0

**Comment by WoLpH** [comment]
My guess is that you're experiencing the reverse of what happens with multi-byte (such as Chinese) characters: https://github.com/WoLpH/python-progressbar#bar-with-wide-chinese-or-other-multibyte-characters
Those characters have double the width from regular characters which cause the width calculation to be wrong. The ANSI escapes have a width of 0 so they should be ignored instead. In any case, I'll test a bit to see if changes like that can help :)

**Comment by Klavionik** [comment]
Great, thanks for that! Yet I assumed that the ANSI escapes characters are already being ignored when calculating the width, aren't they? I thought that the `len_color` function from the utils module does exactly that, returning the length of the marker without the ANSI escapes. But you should know better, of course. :)

**Comment by WoLpH** [comment]
You're right. I forgot that was in there :P

**Comment by WoLpH** [comment]
Looking at it a bit better I understand what's happening. It's not due to the width calculation but both the marker and the fill are expected to be "rotated".

If your fill would be `'abcd'` your fill would result in: `abcdabcdabcdab` and so on. So what you need is something to wrap the fill/marker result.

For the future I'm working on adding a `marker_wrap` and `fill_wrap` parameter to the `AnimatedMarker`, but I don't have it working yet and my time is a tad limited.

An easy workaround would be to make `fill` a function that automatically wraps the output after calculating the size. But this might still cause problems due to the width calculation... I'm not a 100% sure about that

**Comment by Klavionik** [comment]
Thanks again for drawing your attention to the issue. So, probably it's not a feature one can't live without, but it would be cool to have it. I'll be patient. :)

**Comment by WoLpH** [comment]
You can try the current develop branch. It should do the trick when using it something like this:

```python
progressbar.Bar(marker=progressbar.AnimatedMarker(
    fill='#',
    fill_wrap=(
        '\033[38;5;31m',
        '\033[0m',
    ),
    marker_wrap=(
        '\033[34;5;31m',
        '\033[0m',
    ),
))
```

**Comment by Klavionik** [comment]
Yes, it does work perfectly! I didn't test it against many cases, but in my case, everything is how it is supposed to be. Thank you, sir.

**Comment by WoLpH** [comment]
I've released a new version that fixes this :)
