### ISSUE TITLE
prefix is concatenating the values

### ISSUE THREAD

**Issue by marcelotrevisani** [WoLpH/python-progressbar#221]
#### Description

I was trying to use the ``ProgressBar`` with a prefix. However, every time which I use it again the prefix is added to the old prefix.

#### Code

```python
from time import sleep

import progressbar


WIDGET_BAR_DOWNLOAD = [
    progressbar.Percentage(),
    " ",
    progressbar.ETA(format="%(eta)8s"),
    " ",
    progressbar.AdaptiveTransferSpeed(),
    progressbar.Bar(),
]

total_size=10
with progressbar.ProgressBar(widgets=WIDGET_BAR_DOWNLOAD, max_value=total_size, prefix=f"1_prefix ") as bar:
    for i in range(total_size):
        bar.update(i)
        sleep(0.2)

with progressbar.ProgressBar(widgets=WIDGET_BAR_DOWNLOAD, max_value=total_size, prefix=f"2_prefix ") as bar:
    for i in range(total_size):
        bar.update(i)
        sleep(0.2)
```

Workaround: If I ``deepcopy`` the ``WIDGET_BAR_DOWNLOAD`` it will work as expected. However, I think the ``progressbar`` should not modify the widget passed as a parameter, shouldn't it?

#### Result:

**Current result:**
```
1_prefix 100% Time:  0:00:02   5.0 B/s|###########################################|

2_prefix 1_prefix 100% Time:  0:00:02   5.0 B/s|###########################################|

```

**Expected result:**
```
1_prefix 100% Time:  0:00:02   5.0 B/s|###########################################|

2_prefix 100% Time:  0:00:02   5.0 B/s|###########################################|
```

#### Versions

- Python version: 3.8.1
- Python distribution/environment: Anaconda
- Operating System: Ubuntu Linux
- Package version: 3.47.0

**Comment by WoLpH** [comment]
Thank you for the elaborate bug report. Reuse of a bar was not part of the original design so I'm not surprised that bugs still exist in that code.

I'll push out a new release today

**Comment by WoLpH** [comment]
I've released a new version with your fix. Thank you so much for the help!

**Comment by marcelotrevisani** [comment]
Thank you very much!
