### ISSUE TITLE
3.50.0 regression

### ISSUE THREAD

**Issue by Sugarbear187** [WoLpH/python-progressbar#224]
#### Description

3.50.0 breaks cmd wiindow on windows 10.

#### Code

Simple test code:

from    time import sleep
import  progressbar 

def main():
    
    bar = progressbar.ProgressBar(max_value=100)
    for i in range(100):
        bar.update(i)
        sleep(.5)

    bar.finsh()

if __name__ == "__main__":
    main()

ProgressBar2 3.47.0 produces:
 11% (11 of 100) |######################            | Elapsed Time: 0:00:05 ETA:   0:00:44

ProgressBar 2 3.50.0 produces:
N/A% (0 of 100) |                                                                | Elapsed Time: 0:00:00 ETA:  --:--:--
  1% (1 of 100) |                                                                | Elapsed Time: 0:00:00 ETA:   0:00:49
  2% (2 of 100) |#                                                               | Elapsed Time: 0:00:01 ETA:   0:00:49
  3% (3 of 100) |#                                                               | Elapsed Time: 0:00:01 ETA:   0:00:48
  4% (4 of 100) |##                                                              | Elapsed Time: 0:00:02 ETA:   0:00:48
  5% (5 of 100) |###                                                             | Elapsed Time: 0:00:02 ETA:   0:00:47

#### Versions
cmd window: c:\> python test.py 

Python 3.82
Windows 10 all latest updates, etc.

**Comment by WoLpH** [comment]
Thanks for the detailed bug report!

I'm creating a new release that fixes it.
