### ISSUE TITLE
Example format_custom_text does not update eggs

### ISSUE THREAD

**Issue by JimWinters** [WoLpH/python-progressbar#228]
#### Description

In the project file examples.py, in function format_custom_text, it seems that the code is changing the variable "eggs", with "format_custom_text.update_mapping(eggs=i*2)", but the value displayed in the progress bar never changes from the original value, "3".

Thank you for a very nice package!

FormatCustomText looked like just what I needed for my application, but the output wasn't showing changes to my variables.  After struggling for a few days to figure out what was wrong with my code, I went back and ran the example again and noticed it has the same problem.

I worked around this problem by basing my code on examples.py: user_variables instead.

#### Code

python3 ./examples.py format_custom_text

#### Versions

- Python version:

 $ python3
Python 3.5.2 (default, Apr 16 2020, 17:47:17) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.version)
3.5.2 (default, Apr 16 2020, 17:47:17) 
[GCC 5.4.0 20160609]

- Python distribution/environment:

I don't know, but I found this online:

  CPython: this is the default, and what you should be using if you have no idea.

So I think I am using CPython.

- Operating System:

Linux Mint 18.3 Sylvia, Cinnamon 64 bit

 $ uname -a
Linux rayna 4.15.0-96-generic #97~16.04.1-Ubuntu SMP Wed Apr 1 03:03:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Package version:

3.51.0

**Comment by WoLpH** [comment]
It seems that a recent update broke this: https://github.com/WoLpH/python-progressbar/issues/221

It's not that it doesn't work at all but the `deepcopy` makes you lose the reference to the correct formatter...

**Comment by WoLpH** [comment]
Release 3.51.1 has a fix :)

**Comment by JimWinters** [comment]
I see that 3.51.1 does indeed fix it.  Thanks!
