### ISSUE TITLE
Telling progressbar and progressbar2 apart from within Python

### ISSUE THREAD

**Issue by lczech** [WoLpH/python-progressbar#234]
Hi there,

thanks for this awesome tool! 

It seems that many systems by default have the old `progressbar` installed, which to an unsuspecting user gives errors such as [this one](https://github.com/luka1199/geo-heatmap/issues/9). That does not tell what is going on without googling that error message.

Now, I'd like to check this properly, from within Python, and give a proper error message if needed. I have played around with 

    print(progressbar.__version__)

which gives me `3.51.4` for my `progressbar2` version, which does not really help. Is there a way to test this properly?

Thanks!

**Comment by WoLpH** [comment]
Checking for version is an option, the original progressbar is currently at 2.5 so there's a bit of difference. But perhaps checking for the `__author__` variable might be more useful:
```
>>> progressbar.__author__
'Rick van Hattem (Wolph)'
```
Also, I use an `__about__` file to store all info about the package so you could check for `progressbar.__about__` as well.

Or you could do feature testing. There's a whole range of methods and widgets that have been added:
```
AbsoluteETA
AdaptiveTransferSpeed
CurrentTime
DataSize
DataTransferBar
DynamicMessage
FormatCustomText
MultiProgressBar
MultiRangeBar
NullBar
Variable
VariableMixin
bar
base
date
len_color
shortcuts
streams
utils
```

Most of those should be stable. But I would suggest checking one of the first two options :)

**Comment by lczech** [comment]
Thanks! I used the `__author__` info, works like a charm, and should be sufficient, given that this is simply meant as a better warning for unsuspecting users ;-)
