### ISSUE TITLE
Very strange incompatibility with pandas and another library

### ISSUE THREAD

**Issue by xmatthias** [WoLpH/python-progressbar#235]
#### Description
I'm encountering a very strange issue - i'm not even sure it's an issue with this library - but  i'm looking for help here as i'm kinda clueless where to look at next.

Running the below code (requires external dependencies - as listed below) works just fine, the output beeing 

```
> python testfile.py

ERROR:root:hello world
testtest after
```

However - when running the command while piping stdout to grep - then stdout is not shown anymore (the same happens when redirecting with `... 1>file.txt`.

```
python testfile.py  | grep test
ERROR:root:hello world
```

Now the strange thing is - if i remove EITHER the pandas import, or the ccxt import (or both) - then the above code prints out both lines again (hello world because its in stderr, "testtest after" because of the grep).

Now i'm clueless as to what could cause this - as obviously it's not one library alone - but the combination of the 2 that seems to have this effect.

Using the debugger, i could see no difference in `progressbar.streams` - but i'm not that experienced debugging this library / with this library.

I've got the example drilled down as much as possible, so it's not doing much anymore other than print and log (my usecase is a lot complexer and DOES involve the progressbar - but actually showing the progressbar seems irrelevant in this case).

#### Code

```
pip install ccxt==1.34.7 pandas==1.1.1
```

```python
import sys
import time
import logging
import progressbar

# Removing either of the following 2 imports will make the example work
import pandas as pd
import ccxt.async_support


progressbar.streams.wrap_stderr()
progressbar.streams.wrap_stdout()
logging.basicConfig()


logging.error("hello world")
print("testtest after")
# sys.exit()

```

#### Versions

- Python version: 3.8.2 (default, Apr 26 2020, 13:27:05)
- Python distribution/environment: CPython
- Operating System: Linux
- Package version: 3.52.1

**Comment by WoLpH** [comment]
You could try an explicit flush to rule out if this library is responsible:
```
progressbar.streams.flush()
```

It might also be related to Python buffering which can be disabled by setting the environment variable `PYTHONUNBUFFERED=1`

Beyond that... not entirely sure if it's not one of those.

**Comment by xmatthias** [comment]
interresting, the `PYTHONUNBUFFERED=1` seems to do the trick, thanks for this!

i do however not fully understand why this would appear only when both other libraries are included, but not when only one of the 2 is included.

As said above, i doubt it's the fault of progressbar - but of "something else" - just figuring out "what else" - is the difficult part.

**Comment by WoLpH** [comment]
In that case my guess would be that your application isn't exiting cleanly. When Python crashes the buffers can get lost.

**Comment by xmatthias** [comment]
In theory, i would agree - but i don't see how this might be happening with ONLY the above script.

Also, the text IS visible on screen - it's just not properly passed to stdout - not sure if python buffering can induce that.

**Comment by WoLpH** [comment]
I've been testing a bit and I'm still not sure what's happening honestly...

If I disable `import ccxt.async_support` it works
And if I add this at the end of the file it works too: `progressbar.streams.unwrap(True, True)`

But I really don't see how that makes sense. As far as I can see the `ccxt` library isn't touching `stdout` at all.

**Comment by WoLpH** [comment]
Here's the weirdest bit. After disabling the wrapping in the code and using the environment variables instead, it works if only stdout wrapping is enabled, it works if only stderr wrapping is enabled, but it's broken when both stdout and stderr wrapping are enabled.

```
# WRAP_STDOUT=true python pandas_test.py | grep test
testtest after
# WRAP_STDERR=true python pandas_test.py | grep test
testtest after
# WRAP_STDOUT=true WRAP_STDERR=true python pandas_test.py | grep test
# WRAP_STDOUT=true WRAP_STDERR=true python pandas_test.py 2>&1 | grep test
```

**Comment by WoLpH** [comment]
I found the issue :)

When stdout/stderr wrapping is enabled but capturing is not enabled, the write behaviour is slightly different. Normally a stdout/stderr stream would flush when a newline is present, that behaviour wasn't in this library.

I've pushed a new release which fixes the issue.

**Comment by xmatthias** [comment]
Oh very nice, and a fix is available already! 


can confirm, this solves this! Thanks a lot for your great support!
