### ISSUE TITLE
Missing Changelog

### ISSUE THREAD

**Issue by encukou** [WoLpH/python-progressbar#236]
#### Description

[CHANGES.rst](https://github.com/WoLpH/python-progressbar/blob/develop/CHANGES.rst) links to [the GitHub release page](https://github.com/WoLpH/python-progressbar/releases), which, for the past few releases, only says "Created with GPGit 1.3.1".

Is the changelog available somewhere else?
It's not a big problem to look through the commits directly, but the link does create some false expectations :)

**Comment by WoLpH** [comment]
It looks like gpgit is overwriting the git release information... that's quite annoying
You can still view them when you go to tags and expand the commit message: https://github.com/WoLpH/python-progressbar/tags
![image](https://user-images.githubusercontent.com/270571/92601195-cfa1b700-f2ac-11ea-8d8f-a2c803834474.png)

I've attempted to fix this in my local settings but I'm not a 100% sure it works properly now. I'll take a look at the next release :)
