### ISSUE TITLE
No Colors in Progressbar (Windows)

### ISSUE THREAD

**Issue by Askadelion** [WoLpH/python-progressbar#237]
#### Description

I have use your Progressbar Example but this show not the color its only white, i using Colorama to formate linux colors in windows this but only your progressbar dont show this.

How can I Fix this? Or does that not work under Windows?

#### Code

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
from __future__ import with_statement

import functools
import random
import sys
import time

import progressbar
from colorama import Fore, Back, Style, init

def color_bar_example():
    widgets = [
        '\x1b[33m Colorful example: \x1b[39m',
        progressbar.Percentage(),
        progressbar.Bar(marker='\x1b[32m█\x1b[39m'),
    ]
    bar = progressbar.ProgressBar(widgets=widgets, max_value=10).start()
    for i in range(10):
        # do something
        time.sleep(0.1)
        bar.update(i + 1)
    bar.finish()

if __name__ == '__main__':
	init();
	print(f'\x1b[32m Colorful example: \x1b[39m\n')
	color_bar_example()
	print('\n')
```

#### Versions

- Python version: python 3.7.7
- Python distribution/environment: None only in CMD
- Operating System: Windows 10
- Package version: progressbar2 3.53.1

### Demo Image
![cmd_jlWMAvKw2e](https://user-images.githubusercontent.com/41443013/97294256-0bd5aa80-184e-11eb-99f6-93a41efc74f0.png)

**Comment by Askadelion** [comment]
Ok i have find out, with a little trick. 
How i use in the windows console color.

![cmd_2PY2oZ6ATX](https://user-images.githubusercontent.com/41443013/97559858-42dac600-19de-11eb-8271-d5be354a624f.png)

**Comment by WoLpH** [comment]
Oddly enough, it partially works out of the box for me on Python 3.7.7:
![image](https://user-images.githubusercontent.com/270571/97602817-0c1ba480-1a0c-11eb-8782-85c8ba2467c0.png)

Can you share what trick helped for you?

**Comment by Askadelion** [comment]
My tricky is simple,
i have for convert the ANSI escape codes,
insert follow lines bevor i import the progressbar.
![sublime_text_NGbI6AnlVp](https://user-images.githubusercontent.com/41443013/97637958-e1494480-1a3b-11eb-8e1f-77a48900c0ca.png)

**For windows CMD i use Colorama for show the colors.
but it works the same with other methods, bsp: os.system("") & '\033[32m' ... **

And then i have aktivate the PYCHARM ANSITERM from the Progressbar2 modul:
(so I did not have to tamper with the progressbar module)
![ss (2020-10-29 at 11 16 49)](https://user-images.githubusercontent.com/41443013/97638487-ea86e100-1a3c-11eb-8929-33bb8a48ca8b.png)

**`with:  os.environ['PYCHARM_HOSTED'] = '1'`**

![sublime_text_p0kNJnPLHT](https://user-images.githubusercontent.com/41443013/97638368-b14e7100-1a3c-11eb-92aa-5c13d8acf1a5.png)

After this i can use the Colors in the progressbar2
![rTm4FFCPUn](https://user-images.githubusercontent.com/41443013/97639660-4bafb400-1a3f-11eb-87d8-6476dff7935f.gif)

If you find a better solution just give it to me.
Otherwise it works without this simple change only in pyCharm or in Linux (VM) but not in the Windows 10 console (CMD).
I have used Colorama under python 2.7.x before, so I still use it.
So there is no special reason why I use it.

**Comment by WoLpH** [comment]
Great! Thank you for the explanation. I'll keep this issue open so I can natively incorporate it in the future somehow :)

**Comment by Askadelion** [comment]
No problem, I have been looking for a good progress bar for a very long time. And this one had all my wishes so I wanted it in color xD. Even if it didn't work in the beginning I tried to find something to make it work, even if I had to do some tricks.

I hope that it is or will be helpful.
