### ISSUE TITLE
Switch to pytest-flake8

### ISSUE THREAD

**Issue by sternenseemann** [WoLpH/python-progressbar#241]
Switching tests to pytest-flake8 instead of pytest-pep8 would be great: The package is no longer maintained and the upstream bitbucket project is gone.

**Comment by WoLpH** [comment]
I guess I haven't gotten to this package yet. I've migrated several of my other packages already :)

**Comment by sternenseemann** [comment]
Still relevant.

**Comment by WoLpH** [comment]
Yes it is :)

Just haven't gotten to putting out a new release yet. Soon I hope

**Comment by WoLpH** [comment]
I fixed this about 1.5 months ago but forgot  to close the issue. We're fully dependent on flake8 now instead of the pytest modules
