### ISSUE TITLE
Progressbar appears after the end of the script

### ISSUE THREAD

**Issue by dkoao** [WoLpH/python-progressbar#242]
Hello, so this is more of a question than an actual issue.

I have a bar that's setup like this:
```
widgets = [
' [', progressbar.ETA(), '] ',
progressbar.Percentage(), f"{cyan}", progressbar.Bar(), f"{nc}",
]
bar = progressbar.ProgressBar(max_value=100, widgets=widgets)
```

It works fine, it looks like this:
`[ETA:  00:00:00] 100%|############################################################################|`

But the problem is that at the end of the script, I get this bar:

`[Time:  0:00:24] 100%|############################################################################|`

I think that it's outputting the time it took for the previous bar to finish. How do I make it stop doing this?

**Comment by WoLpH** [comment]
This happens because the bar was not finished properly. You can either call `bar.finish()` or use the progress bar using a with statement so it is closed automatically.

**Comment by dkoao** [comment]
That solved it. Thank you very much for the quick response!
