### ISSUE TITLE
Padding the bar

### ISSUE THREAD

**Issue by dkoao** [WoLpH/python-progressbar#243]
Hello again, so this is (like the last time) more of a question than an actual issue.

I have a progress bar with variables that are constantly changing. The bar works fine, but there are a couple of issues:

- It looks kinda weird because the bar keeps changing its scale to match the variables' changes.

- When there are other bars, the terminal window starts looking inconsistent because some bars finish in a different position than others.

So my question is: Is there a way to pad the progress bar with a certain amount of spaces so that changes in the variables don't end up changing the bar's scale?

Thanks in advance and sorry if this is a stupid question.

**Comment by WoLpH** [comment]
It depends on how you are adding the variables, but with basic string formatting you can already add padding :)

```python
import time
import progressbar

your_variable = 'Hi :)'
pad_length = 10

widgets=[
    '{:{pad}}'.format(your_variable, pad=pad),
    ' [', progressbar.Timer(), '] ',
    progressbar.Bar(),
    ' (', progressbar.ETA(), ') ',
]
for i in progressbar.progressbar(range(20), widgets=widgets):
    time.sleep(0.1)
```

**Comment by dkoao** [comment]
Nice. Thank you!
