### ISSUE TITLE
Estimated progress based on trackable variable

### ISSUE THREAD

**Issue by MRCWirtz** [WoLpH/python-progressbar#244]
I often experience the situation where I do not know the length of my loop beforehand, but I stop when a certain variable reaches a threshold value. In this cases one could still log more information on the progress than just a simple progress animation.

My idea would be to initialize the ProgressBar class with a 'target_value' and pass the tracked variable to the .update() function within the loop. Without specifying an assumed model the ProgressBar could then for instance log a linear interpolation for the ETA based on the target_value and the tracked ones. 

I have this implemented in a private project where my class inherits from the ProgressBar from this repository. If this could be something worth to consider as feature in the progressbar2 module, I could prepare a corresponding pull request in the upcoming days.

Or do you eventually know about another project where something like this is already implemeted?

Cheers!

**Comment by WoLpH** [comment]
It sounds somewhat similar to the AdaptiveETA where you update `bar.max_value` regularly. But I'm not sure if that's 100% what you're looking for.

If it's different from how you've implemented it, I'm always interested in additions to the project and pull requests are greatly appreciated :)

**Comment by MRCWirtz** [comment]
Okay, I will need to have a look inside the AdaptiveETA. Indeed I also update the `max_value` attribute in my solution, so probably it will be similar in the end :) Anyways, thanks for the prompt reply and I will create a pull request based on whether or not I consider it as beneficial!
