### ISSUE TITLE
Please make it clear what the difference is to other progressbar project

### ISSUE THREAD

**Issue by normanius** [WoLpH/python-progressbar#245]
#### Description

The package has the same name as another package [progressbar](https://pypi.org/project/progressbar/). Could you please make it clear in what way (if at all) those two projects are related. This would be useful, because as for now, the packages overshadow each other. One cannot use both at the same time.

The name suggests that progressbar2 is somehow the successor of progressbar, which I doubt this is the case.

Please add a comment about this in the introduction. Just to make it clear :)

See [PEP-423](https://www.python.org/dev/peps/pep-0423/#overview) for some conventions related to package names. I think it is recommended to use a [single name](https://www.python.org/dev/peps/pep-0423/#use-a-single-name) for project and package. So maybe you should use progressbar2 as package name, not progressbar. (=> `import progressbar2 as progressbar`)

**Comment by WoLpH** [comment]
The package started as a fork for the completely abandoned progressbar package. The original developer hadn't responded for years (not to email either) and the package had multiple bugs and issues so I decided to fix them myself.

In all those years I have maintained full backwards compatibility with the old package so you can safely uninstall that one and install this one instead without having your code break.

All in all, for all intents and purposes this package can be seen as the successor of progressbar :)

I'm aware of PEP432 but as this is meant to be a drop-in replacement I had to keep the name the same. Additionally, back when I forked the package there was no way to take over an abandoned package with PyPI so renaming it was my only option.

**Comment by normanius** [comment]
Sorry for jumping to conclusions too quickly. If your package is a drop-in replacement for the former project, that makes perfect sense.

A small note in the project description would help the confused users. It may also help others to convince themselves that your project is the right choice :)

Thanks for your work!

**Comment by WoLpH** [comment]
Honestly... I'm pretty sure I had some notes about that at some point but I think they've been lost to time. I've added a little explanation to the readme :)
