### ISSUE TITLE
Feature request: delay before displaying

### ISSUE THREAD

**Issue by wvzytlyn** [WoLpH/python-progressbar#246]
#### Description

The same loop inside a function may have different orders of magnitude of duration, depending on the function arguments. I would like the option of a delay in displaying the progressbar, which has the effect that the bar is never shown if it reaches 100% before the delay, of e.g. 0.5 seconds.

#### Code

Currently:
```python
for i in progressbar.progressbar(range(N)):
    pass
```

Desired:
```python
for i in progressbar.progressbar(range(N), delay = 0.5):
    pass
```

**Comment by WoLpH** [comment]
That could be an interesting feature but I fear it could cause many issues...

I've had a little time to think about it and I've got an idea for a solution that should do the trick. If we create a custom `sys.stderr` with initially delayed writing that should do the trick. After the initial delay it can simply play back everything it stored in the mean time.

From the top of my head I would assume something like this:
```python
import time


class DelayedOutput:
    def __init__(self, stream, delay):
        self.stream = stream
        self.delay = delay + time.time()
        self.buffer = []

    def write(self, value):
        if self.delay > time.time():
            if self.buffer:
                map(self.stream.write, self.buffer)
                self.buffer = []
            else:
                self.buffer.append(value)

    def flush(self):
          self.stream.flush()
```

**Comment by wvzytlyn** [comment]
Awesome, that looks like a great solution. I think it should be `if self.delay < time.time():`, right?

How would I pass this DelayedOutput to a progressbar constructor?

**Comment by WoLpH** [comment]
The progressbar takes an `fd` argument by default: https://progressbar-2.readthedocs.io/en/latest/progressbar.bar.html#progressbar.bar.DefaultFdMixin

So you could do:
```
import sys
import progressbar

bar = progressbar.ProgressBar(fd=DelayedOutput(sys.stderr, 5))
```

As for the comparison, `delay` consists of `delay + time.time()` so it is correct. It should write to the output stream if `time() + delay < time`, and to the buffer if it's not (the `else`).

**Comment by wvzytlyn** [comment]
Thanks for the solution. The following does exactly what I want, based on your suggestion (some minor modifications), no progressbar ever appears if the loop finished before the delay, and otherwise it will appear as usual:

```python
import progressbar as realpbar

import time

import sys


class DelayedOutput:
    def __init__(self, stream = sys.stderr, delay = 0.5):
        self.stream = stream
        self.delay = delay + time.time()
        self.buffer = []

    def write(self, value):
        if time.time() < self.delay:
            self.buffer.append(value)
        else:
            if self.buffer is not None:
                map(self.stream.write, self.buffer)
                self.buffer = None
            self.stream.write(value)

    def flush(self):
        self.stream.flush()


def progressbar(
                *args,
                delay = 0.3,
                stream = sys.stderr,
                line_breaks = False,
                **kwargs
                ):

    return realpbar.progressbar(*args,
                                **kwargs,
                                fd = DelayedOutput(
                                    stream=stream,
                                    delay=delay),
                                line_breaks = line_breaks,
                                )
```
