### ISSUE TITLE
prefix and suffix not working

### ISSUE THREAD

**Issue by 08walkersj** [WoLpH/python-progressbar#247]
When the following code is run no prefix appears, the same if I use the suffix argument too
```
for i in progressbar.progressbar(range(10), prefix='Hi: ', max_value=10):
    time.sleep(0.1)
```

**Comment by WoLpH** [comment]
Can you check which version of the library you are running?

It should look like this:
```
>>> import progressbar
>>> progressbar.__version__
'3.53.1'
```

**Comment by 08walkersj** [comment]
3.37.1

**Comment by WoLpH** [comment]
That makes sense :)
https://github.com/WoLpH/python-progressbar/releases

The prefix/suffix was introduced in 3.51.2

**Comment by 08walkersj** [comment]
Thank you for your help
