### ISSUE TITLE
Opening a discussion page on github page for questions like tqdm has

### ISSUE THREAD

**Issue by brando90** [WoLpH/python-progressbar#248]
Hi,

I really like your library and would love to be able to see question about it in one place - perhaps to encourage more use! Are you guys open to it? :)

**Comment by WoLpH** [comment]
Yeah, sounds like a good idea :)

The big issue is that besides the occasional pull-request, this entire project is just me. And I'm pretty limited in time.
In any case, I've enabled the discussions feature so that could help at least a little ;)
