### ISSUE TITLE
Inverse FileTransferSpeed

### ISSUE THREAD

**Issue by chausies** [WoLpH/python-progressbar#25]
For many slow-moving loops, the transfer speed would be something like .01 B/s or .00 B/s, which is highly uninformative. Is there a way you could show s/B for these cases? 175 s/B is much more descriptive and helpful. Also, do you have a workaround I could use for now? Because seeing .00 B/s doesn't tell me much about how fast I'm looping.

**Comment by WoLpH** [comment]
Wow... except for stalling transfers I've never had anything in that range... luckily it's not all that hard to fix :)

I have added a working version to the develop branch but it's not completely done for a release yet (still some code left untested and not working right now) but most of it should work already. Can you give it a try?


Out of curiosity though, what is your use case?

**Comment by WoLpH** [comment]
This has been released with the latest version :)

Please git v3.0.1 a try
