### ISSUE TITLE
Exposing isatty method in WrappingIO

### ISSUE THREAD

**Issue by piotrbartman** [WoLpH/python-progressbar#254]
#### Description

If the use of [click](https://click.palletsprojects.com/en/8.0.x/) wrapping on stdout causes click to not recognize standard output as a terminal and all formatting (ANSI codes) is discarded.

#### Code

```Python
import click
import progressbar

progressbar.streams.wrap_stdout()
click.secho("text", fg="red")
# white text
```

It can be fixed by:

```Python
sys.stdout.isatty = progressbar.streams.original_stdout.isatty
```

I think it can be fixed by expose in `WrappingIO` class `isatty` method of target.

#### Versions

- Python version: 3.9.2
- Python distribution/environment: CPython/Anaconda/IPython/IDLE
- Operating System: Debian
- Package version: 3.53.1

**Comment by WoLpH** [comment]
Thank you for the report and the suggested fix :)

It appears to be working great for me now so I've pushed a new release
