### ISSUE TITLE
2.53.2: no valid/verifiable PGP signature

### ISSUE THREAD

**Issue by dvzrv** [WoLpH/python-progressbar#255]
#### Description

Hi! I'm maintaining this package for Arch Linux.
Unfortunately I am unable to update to [3.53.2](https://github.com/WoLpH/python-progressbar/releases/tag/v3.53.2), because the new key ID `9912898DD1AEBD0E` used for the release is neither verified for the user @WoLpH nor am I able to retrieve the PGP public key of that key ID (from github or any keyserver).

For the 3.53.1 release the key ID `149325FD15904E9C4EB89E95E81444E9CE1F695D` has been used to create a detached signature for the sdist tarball on pypi.org. Please provide a cross-signature that allows me to validate the trust path from `149325FD15904E9C4EB89E95E81444E9CE1F695D` to `9912898DD1AEBD0E`.

#### Code

```
$ curl -O https://github.com/wolph.gpg
$ cat wolph.gpg
-----BEGIN PGP PUBLIC KEY BLOCK-----
Note: The keys with the following IDs couldn't be exported and need to be reuploaded E81444E9CE1F695D, DB95009289C3EB3C


=twTO
```

#### Versions

- Python version: `3.9.7`
- Python distribution/environment: system
- Operating System: Arch Linux
- Package version: `3.53.2`

**Comment by WoLpH** [comment]
It looks like I accidently signed the release with my old GPG key. It has been revoked for a few years but it should still exist on the keyservers.

I've pushed a new release with the proper key now

**Comment by FelixSchwarz** [comment]
It seems like the pypi releases still use the outdated gpg key, right?

**Comment by WoLpH** [comment]
@FelixSchwarz I don't believe so. I've just verified the files and they look ok:

```
# curl -O https://files.pythonhosted.org/packages/7f/06/a50145aefa5a31e79eb1409617d3cf0a3f85b4fb8e6472ed9a485354cd9c/progressbar2-3.53.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  235k  100  235k    0     0  2304k      0 --:--:-- --:--:-- --:--:-- 2304k
# curl -O https://files.pythonhosted.org/packages/7f/06/a50145aefa5a31e79eb1409617d3cf0a3f85b4fb8e6472ed9a485354cd9c/progressbar2-3.53.3.tar.gz.asc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   833  100   833    0     0  15716      0 --:--:-- --:--:-- --:--:-- 15716
# gpg --verify progressbar2-3.53.3.tar.gz{.asc,}
gpg: Signature made Wed Sep 15 00:43:24 2021 CEST
gpg:                using RSA key 149325FD15904E9C4EB89E95E81444E9CE1F695D
gpg: Good signature from "Rick van Hattem <wolph@wol.ph>" [ultimate]
gpg:                 aka "[jpeg image of size 9662]" [ultimate]
```

**Comment by FelixSchwarz** [comment]
This is how it looks for me:

    $ gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 0xE81444E9CE1F695D 
    gpg: key E81444E9CE1F695D: "Rick van Hattem <wolph@wol.ph>" not changed
    gpg: Total number processed: 1
    gpg:              unchanged: 1

    $ gpg --list-key 0xE81444E9CE1F695D
    pub   rsa4096 2017-07-23 [SC] [expired: 2021-07-23]
          149325FD15904E9C4EB89E95E81444E9CE1F695D
    uid           [ expired] Rick van Hattem <wolph@wol.ph>
    uid           [ expired] [jpeg image of size 9662]

Am I doing something wrong here?

**Comment by WoLpH** [comment]
No, that is actually the current one. And it should be valid until 2023-07-31 :P

![image](https://user-images.githubusercontent.com/270571/135099805-81b36b02-f044-490a-bd07-9c40e7c5c24f.png)

```
# gpg --list-key 149325FD15904E9C4EB89E95E81444E9CE1F695D
pub   rsa4096 2017-07-23 [SC] [expires: 2023-07-31]
      149325FD15904E9C4EB89E95E81444E9CE1F695D
uid           [ultimate] Rick van Hattem <wolph@wol.ph>
uid           [ultimate] [jpeg image of size 9662]
sub   rsa4096 2017-07-23 [E] [expires: 2023-07-31]

# gpg --list-key 0xE81444E9CE1F695D
pub   rsa4096 2017-07-23 [SC] [expires: 2023-07-31]
      149325FD15904E9C4EB89E95E81444E9CE1F695D
uid           [ultimate] Rick van Hattem <wolph@wol.ph>
uid           [ultimate] [jpeg image of size 9662]
sub   rsa4096 2017-07-23 [E] [expires: 2023-07-31]
```

I'll re-push the key to the keyserver to be sure but I'm not getting what's wrong here.

**Comment by WoLpH** [comment]
It seems that the key was somehow corrupted within Github. I have no clue why but I had to reupload it to Github for this url to work again: https://github.com/wolph.gpg

Perhaps some issues with the Microsoft takeover of Github? I haven't touched the key myself since I created it...

**Comment by FelixSchwarz** [comment]
> It seems that the key was somehow corrupted within Github. I have no clue why but I had to reupload it to Github for this url to work again: https://github.com/wolph.gpg

Okay, that URL works. Thank you and sorry for bothering you.

**Comment by WoLpH** [comment]
Thank you for letting me know. Apparently the file was corrupted somehow :)
