### ISSUE TITLE
PyPi Versio newer than github

### ISSUE THREAD

**Issue by NicoHood** [WoLpH/python-progressbar#261]
Why is 3.55 available on pypi but not on github?
https://pypi.org/project/progressbar2/

**Comment by WoLpH** [comment]
I'm not sure... perhaps some issue with the deploy script. I'm reworking that anyhow so that will change soon.
The tag is online but github only shows releases unfortunately: https://github.com/WoLpH/python-progressbar/tags

**Comment by WoLpH** [comment]
I've released a new version including Github release so this issue has been fixed :)
