### ISSUE TITLE
Not sure how to go about doing this

### ISSUE THREAD

**Issue by kdschlosser** [wolph/python-progressbar#274]
OK I want to create a progress bar that looks like the following

```
SomeFileName.cpp [13/45] |####################                               | 54% [FT 00:01:00][TT: 00:02:30][ETR: 00:05:40]
```

I need to be able to change `SomeFileName.cpp` And I would also like to have the ability to update the progress bar to have the TT (Total Time) and FT (File Time) update even if I am not incrementing the value at all. The FT time would need to be able to be reset back to zero when the SomeFileName.cpp changes.

**Comment by kdschlosser** [comment]
I am not actually tracking the compiling of each individual file. I know when the compiling of a file starts but I want the timers to update while a file is compiling. So if say one file takes 30 seconds to compile the timers the user sees will continue to update during that 30 seconds. I have the ability to update the timers from the main thread so I would need the ability to call update blindly from the main thread without being able to pass i the variables.

**Comment by wolph** [comment]
I think that's even easier :)
```python
import random
import time
import functools
from datetime import datetime, timedelta

import progressbar

STEPS_PER_FILE = 20

fmt = functools.partial(progressbar.FormatLabel, new_style=True)


class TimeSince(progressbar.Timer):

    def __init__(self, variable, format='{elapsed}'):
        super().__init__()
        self.variable = variable
        self.format = format

    def __call__(self, progress, data):
        elapsed = datetime.now() - data['variables'][self.variable]
        # Strip the microseconds
        # elapsed -= timedelta(microseconds=elapsed.microseconds)
        return self.format.format(elapsed=elapsed)


widgets = [
    # Note, we're using a custom widget with fileno instead of value here
    # because we want progress within a single filename
    fmt('{variables.filename:20} '),
    fmt('[{variables.fileno:02d}/{max_value}] '),
    progressbar.Bar(),
    ' ',
    progressbar.Percentage(),
    TimeSince('filetime', format=' [FT {elapsed}]'),
    fmt('[TT {elapsed}]'),
    progressbar.AdaptiveETA(
        format=' [ETR: %(eta)s]',
        format_not_started=' [ETR: ?]',
        format_finished='Time: %(elapsed)8s',
        format_zero='ETR: 00:00:00',
    ),
]

files = [f'File_{i}.cpp' for i in range(10)]

bar = progressbar.ProgressBar(
    # prefix='{variables.filename} ',
    widgets=widgets,
    variables=dict(
        filename='Unknown',
        fileno=0,
        filetime=datetime.min,
    ),
    max_value=len(files),
)

with bar:
    for i, filename in enumerate(files, 1):
        bar.update(filename=filename, filetime=datetime.now(), fileno=i)

        for i in range(random.randint(5, 20)):
            bar.update()
            time.sleep(0.1)
```

**Comment by kdschlosser** [comment]
sweet.

Now to see if it works with the multi threading update I made. Problem is my machine compiles the program to damned fast LOL. That's what happens when you have this going on.

![image](https://user-images.githubusercontent.com/10932297/199552929-956e6209-ae5e-45f0-9aef-45fa03a23f0a.png)


LOL.
