### ISSUE TITLE
ETA does not honor empty `format_finished`

### ISSUE THREAD

**Issue by SimonLammer** [WoLpH/python-progressbar#278]
#### Description

`progressbar.ETA` does not honor the argument `format_finished=""`.
https://asciinema.org/a/bZdEriaO3amm4NItGPJ8svFPt

#### Code

```
import progressbar
for value in progressbar.progressbar(
    [1],
    widgets=[
        progressbar.ETA(
            format_finished="",
        ),
    ],
):
    pass
```

**Actual (final) output**:
`ETA:      None`

**Expected (final) output**:
`` (0 characters)

#### Versions

- Python version: 3.11.0 (main, Dec 10 2022, 23:05:43) [GCC 9.4.0]
- Python distribution/environment: CPython
- Operating System: Linux Mint
- Package version: 4.3b.0

#### Workaround

The expected behaviour can be accomplished by using `format_finished="%(eta).0s"` instead of `format_finished=""` .

**Comment by wolph** [comment]
That is intended behaviour to be honest :)

The reason for always requiring a formatstring is consistency in spacing. With an empty formatstring it would move the other stuff in the progressbar around.

You can work around it by using a space `' '` or an invisible character such as `'\uFEFF'`

**Comment by SimonLammer** [comment]
@wolph I'm not sure I understand. Could you give an example where an empty-string result of ETA would "move the other stuff in the progress bar around"?

**Comment by wolph** [comment]
Just take a look at this code:
```
import time
import progressbar


bar = progressbar.ProgressBar(widgets=[
    progressbar.ETA(format_finished=' '),
    ' Some text here ',
    progressbar.Bar(),
])

for i in bar(range(5)):
    bar.update(i)
    time.sleep(0.1)

time.sleep(1.00)
```

The output looks something like this:
```ETA:  --:--:-- Some text here |                                               |
ETA:   0:00:00 Some text here |#########                                      |
ETA:   0:00:00 Some text here |##################                             |
ETA:   0:00:00 Some text here |############################                   |
ETA:   0:00:00 Some text here |#####################################          |
  Some text here |############################################################|
```

As you can see, the text moves and the bar becomes much wider suddenly. That can be a bit confusing :)

**Comment by SimonLammer** [comment]
I see.
However, this also happens when setting `format_finished-' '` which you suggested previously.

```
import progressbar
for value in progressbar.progressbar(
    [1],
    widgets=[
        "Foo",
        progressbar.ETA(
            format_finished=" ",
        ),
        "Bar",
    ],
):
    print()
```
```
FooETA:  --:--:--Bar
Foo Bar
```

Similarly, the invisible character you suggested also does not preserve ETA's output length (`format_finished="\x00"`):
```
FooETA:  --:--:--Bar
FooBar
```

This behaviour may look subpar, but that's a subjective notion. Some users may want to have it that way, some may not.
If those two options you suggested don't preserve the output length of ETA, why should explicitly setting `format_string=""`?

**Comment by wolph** [comment]
Oops... didn't notice your reply.

It actually does work in your example, in both cases :)
The reason that it doesn't appear to work is because you're not seeing the `format_finished` here but the `format_not_started`. The progressbar overwrites the **current** line and with the `print()` statement you're creating a new line so the old line won't be overwritten.

If you want to use print statements in your code I would suggest enabling output redirection: https://github.com/wolph/python-progressbar#combining-progressbars-with-print-output
