### ISSUE TITLE
Syntax Error in latest release

### ISSUE THREAD

**Issue by ld-cd** [wolph/python-progressbar#299]
#### Description

The latest version on pypi has a dangling colon in [widgets.py](https://github.com/wolph/python-progressbar/blame/develop/progressbar/widgets.py#L563C1-L563C2)

#### Code
```python
  File "/home/runner/work/MKIDPipeline/MKIDPipeline/mkidpipeline/steps/wavecal.py", line 9, in <module>
    import progressbar as pb
  File "/home/runner/work/MKIDPipeline/MKIDPipeline/.venv/lib/python3.12/site-packages/progressbar/__init__.py", line 9, in <module>
    from .bar import DataTransferBar, NullBar, ProgressBar
  File "/home/runner/work/MKIDPipeline/MKIDPipeline/.venv/lib/python3.12/site-packages/progressbar/bar.py", line 22, in <module>
    from . import (
  File "/home/runner/work/MKIDPipeline/MKIDPipeline/.venv/lib/python3.12/site-packages/progressbar/widgets.py", line 563
    :
    ^
SyntaxError: invalid syntax
```

We caught this in our CI environment you can view the run here:
https://github.com/MazinLab/MKIDPipeline/actions/runs/10517983894/job/29143058919?pr=101

#### Versions

- Python version: 3.10,3.11,3.12
- Python distribution/environment: CPython
- Operating System: Ubuntu
- Package version: 4.4.3

**Comment by beaglebay** [comment]
This is breaking every single aws Glue jobs we have, since awswrangler automatically pick up this error version

**Comment by wolph** [comment]
Something must have gone wrong, I've yanked the release from PyPI for now. I'll try and get the CI pipeline fully working again before the next release.

**Comment by eli-schwartz** [comment]
Nothing went wrong, it was caught by CI in #298 and also caught in manual review and then still merged seemingly against the wishes of @jdykstra?

**Comment by wolph** [comment]
> Nothing went wrong, it was caught by CI in #298 and also caught in manual review and then still merged seemingly against the wishes of @jdykstra?

I had merged in the changes from that PR, manually fixed the issue and ran pytest locally and proceeded to merge dev back in and that's where it went wrong. It's certainly stupidity on my part ... I ran the tests before merging dev back in and forgot to run the tests after.

**Comment by dvzrv** [comment]
@wolph can you cut a new release with a fix for this please? :sweat_smile:

**Comment by wolph** [comment]
@dvzrv I'm working on it while implementing more rigorous testing and type verification, but it's been quite a lot of work: https://github.com/wolph/python-progressbar/compare/master...develop

I'm almost done however :)

**Comment by wolph** [comment]
I've also done a post-mortem in the mean time. It seems that the fix for the syntax error was stashed... I'm not sure if it was git-up or something vscode did but the fix didn't end up in the final version somehow.

In any case, I've updated my build and deploy script to run ruff on the built version of the wheels and source packages before pushing them to pypi so this should never happen again in the future.

The new version has been published :)
