### ISSUE TITLE
broken import

### ISSUE THREAD

**Issue by firebird631** [WoLpH/python-progressbar#300]
Install progressbar2 package.

Trying the simplest sample. 

```TypeError: 'module' object is not callable```

I find a shortcut module but everything goes wrong.
And possible conflict name (progressbar as module name and as an helper function...).

**Comment by wolph** [comment]
Perhaps you've named your file progressbar or maybe you have a conflicting module?

Try doing `import progressbar; print(progressbar) `

That should show the source of what you're importing

**Comment by firebird631** [comment]
I install pip install progressbar2 (tried with progressbar and progressbar3 too)
I did nothing special (very basic test), just using ipython3, copy and past the simplest sample. progressbar is a module object and not a function. python version 3.11.6.

**Comment by firebird631** [comment]
Ok it seems there was a conflit with a python3-progressbar system package installed.
Removing it and using progressbar2 in place worked.
It seems there is a difference too between python3-progressbar2 (debian) package that install a package named progressbar2 (with the 2 => import progressbar2) and the pip install progressbar2 that have the progressbar module name (import progressbar).
I am not sure, it will need more investigation. It is a bit confusing.
Thanks for your work.
