### ISSUE TITLE
rST description not rendered on PyPI

### ISSUE THREAD

**Issue by takluyver** [WoLpH/python-progressbar#31]
I noticed that the [PyPI package page](https://pypi.python.org/pypi/progressbar2) has the rst readme in plain text. Using the [readme package](https://pypi.python.org/pypi/readme) to check it, I found that the changelog markup in `CHANGES.rst` is causing the problems.

We could:

1. Take the change log out of the package's long description. I prefer this, because the change log makes the PyPI page very long as more releases happen.
2. Manually change the `changelog` and `change` directives back to plain rst. The Sphinx docs would presumably lose something from this.
3. Have some code that tries to convert the rich rst into plain rst when `setup.py` runs. This would be fragile, and could easily get out of date.

**Comment by WoLpH** [comment]
Hmm, indeed. I have to agree with your assessment. Option 1 is imho the best, I've never been one for keeping changelogs anyhow. Looking at the github issues (or more detailed, commit log) seems more useful to me than changelogs as I'll always try to maintain backwards compatibility anyhow.

I've disabled this part of the code in the `setup.py` and manually updated the pypi page for now.

**Comment by takluyver** [comment]
And I see there's a new release out already - thanks!

**Comment by WoLpH** [comment]
Yes, luckily I still have some time before my flight leaves :)

**Comment by takluyver** [comment]
Have a good trip!
