### ISSUE TITLE
If nonzero min_value used, ProgressBar.start() fails

### ISSUE THREAD

**Issue by otakucode** [WoLpH/python-progressbar#35]
ProgressBar.start() always calls ProgressBar.update(0).  When a ProgressBar is create with a nonzero min_value parameter, this call results in a ValueError exception due to 0 being outside the range of permissible values.

**Comment by WoLpH** [comment]
That's a fair point, I've just updated the code to start at `min_value` instead. I believe that should fix it properly :)
