### ISSUE TITLE
Version is wrong in __init__.py

### ISSUE THREAD

**Issue by pganssle** [WoLpH/python-progressbar#38]
In [`__init__.py`](https://github.com/WoLpH/python-progressbar/blob/develop/progressbar/__init__.py#L72), the `__version__` variable is set to `2.7.3` instead of 3.4.1. See:

```python
>>> import progressbar
>>> progressbar.__version__
'2.7.3'
```

I suspect this may be where the documentation is pulling its version number from, too, as the docs page is titled "Welcome to ProgressBar Version 2.7.3!"

**Comment by WoLpH** [comment]
You're completely right... that's quite silly, I forgot to change those when I moved to a single file containing all metadata.

**Comment by WoLpH** [comment]
That's fixed in the current dev. I'll push an update soon.

**Comment by WoLpH** [comment]
I've just released a new version, can you give it a try?
