### ISSUE TITLE
Simpler API to customize output?

### ISSUE THREAD

**Issue by yohanboniface** [WoLpH/python-progressbar#40]
I wanted to just change the fill character of the default ProgressBar behaviour (using █ instead of #), and found myself needing to override all the `default_widgets`.
Maybe I'm missing something, but what about some default widget that would behave like [progress](https://github.com/verigak/progress/) API, i.e. passing just a string that will be then formatted.
That would look like:

``` python
# Only change the the fill character:
bar = ProgressBar(fill="█")
# Change the whole line format:
bar = ProgressBar(fill="█", template='{percent} ({progress}/{total}) {bar} Elapsed Time: {elapsed} Eta: {eta}')
```

Using string.Formatter it may be straits forward instantiating only the needed widgets (this needs a map between format variables and widgets indeed).
One may eventually override some widget by doing something like:

``` python
# Override widget to use for "percent" variable substitution
mybar.register_widget('percent', MyCustomPercentWidget)
# Register a new variable
mybar.register_widget('foo', MyFooWidget)
```

Thoughts?

**Comment by WoLpH** [comment]
Can you test the simple_api branch? (https://github.com/WoLpH/python-progressbar/tree/feature/simpler_api)

I've added support for adding arguments to the default widgets through the progressbar. It does use a separate dictionary so there is no namespace pollution with other parts of the progress bar... not sure if that's the best solution but this should be along the lines of what you're looking for.

Tested with:
```
import time
import progressbar

bar = progressbar.ProgressBar(widget_kwargs=dict(fill='█'))
for i in bar(range(200)):
    time.sleep(0.1)
```

As for the 2nd example, changing the entire line format. That's not a bad idea either, would allow for a bit more customisation as well I suppose. But it's quite a bit more work than I have time for right now. I'll keep this issue open for when I will have some time to take care of it :)

**Comment by WoLpH** [comment]
@yohanboniface PING

**Comment by yohanboniface** [comment]
@WoLpH sorry, missed time :(

I had a quick look on the "simple_api" branch: while this make easier to override widgets, I found it still a bit too much verbose. That's a personal point of view. Roughly, passing dicts as kwargs seems to me an antipattern that generally is a symptom of a need of rethinking *imho*.

Now, talking is easy, and I'd better create a PR with an alternative suggestion, but I'm missing time right now :( I'll try to keep that somewhere on my radar, unless you'll be faster than me on that way (or another ;)) :).

**Comment by WoLpH** [comment]
The big problem is creating a flexible solution while maintaining backwards compatibility. A generator might be an option of course. Something along the lines of `bar = progressbar.ProgressBar.create(fill='#')`

**Comment by yohanboniface** [comment]
Yes; having a new entry point for this API may be a first step. `.create` sounds good.

**Comment by yohanboniface** [comment]
@WoLpH I've been travelling in the last days, so with a bit of time offline and with free mind, so I've played around a bit and made this experiment: https://github.com/yohanboniface/progresso/pull/1/files

It's more or less what I had in mind. Very simple, but the first bits sound promising to me :)

I'd love your feedback! :)

**Comment by WoLpH** [comment]
That looks quite good, I'll give it a proper review soon (2 week-ish) as I'm a bit busy at the moment :)

**Comment by WoLpH** [comment]
The first version of the simpler API is now in the development release. Do you mind if I copy some more of your ideas/implementation as well? It looks like a great improvement for most people :)

**Comment by yohanboniface** [comment]
`license='WTFPL'`

Seems the bar is open :)

**Comment by WoLpH** [comment]
I know, but I prefer to ask before I take :)

Thanks!

**Comment by WoLpH** [comment]
Notice: this issue has been closed because it has been inactive for 304 days. You may reopen this issue if it has been closed in error.
