### ISSUE TITLE
update() is slow

### ISSUE THREAD

**Issue by max-arnold** [WoLpH/python-progressbar#41]
My colleague tried to replace old progressbar with progressbar2 in django-cities-light (see this branch https://github.com/greenday2/django-cities-light/commits/feature/progressbar2) and noticed that data import became much slower (~2 hours instead of ~20 minutes). This also results in one CPU core being busy with iTerm only (probably related to frequent terminal redrawing) We worked around this issue by introducing `divisor` variable and less frequent calls to update().

I think it is worth informing you about the fact that there is serious performance degradation in your fork, so you may want either to fix the cause, or to introduce some laziness in update(), for example update the progressbar only if input variable has changed enough to draw the next character. You can use our divisor trick (and probably replace 100 with utils.get_terminal_size())

**Comment by WoLpH** [comment]
It depends on the type of progressbar you are using, but there is actually support for a similar feature. Try passing along the `poll_interval` setting to the progressbar, if you set it to 1 it will only update once per second.

**Comment by max-arnold** [comment]
`poll_interval` seems to have no effect on update interval (it looks like `self.value > self.next_update` is always `True`):

```
    def _needs_update(self):
        'Returns whether the ProgressBar should redraw the line.'
        if self.value > self.next_update or self.end_time:
            return True

        elif self.poll_interval:
            print "Poll interval"
            delta = datetime.now() - self.last_update_time
            return delta > self.poll_interval
```

**Comment by max-arnold** [comment]
Below is the (hacky) solution I came up with for django-cities-light:

```
class LazyProgressBar(progressbar.ProgressBar):
    """
    Less CPU-intensive progressbar with lazy update.

    Performs update() only if value increment is large enough to add more bars
    to progressbar according to current terminal width.
    """
    def update(self, value=None):
        if None not in (value, self.previous_value):
            if self.max_value is not progressbar.base.UnknownLength:
                divisor = self.max_value // self.term_width or 1
                if (value - self.previous_value) // divisor == 0:
                    return
        super(LazyProgressBar, self).update(value=value)
```

**Comment by max-arnold** [comment]
Below is the (hacky) solution I came up with for django-cities-light:

```
class LazyProgressBar(progressbar.ProgressBar):
    """
    Less CPU-intensive progressbar with lazy update.

    Performs update() only if value increment is large enough to add more bars
    to progressbar according to current terminal width.
    """
    def update(self, value=None):
        if None not in (value, self.previous_value):
            if self.max_value is not progressbar.base.UnknownLength:
                divisor = self.max_value // self.term_width or 1
                if (value - self.previous_value) // divisor == 0:
                    return
        super(LazyProgressBar, self).update(value=value)
```

**Comment by WoLpH** [comment]
You're right, didn't think about that but if you update very frequently (a lot of data) it indeed won't work.
It only works for cases such as this:
```python
bar.update(10)
bar.update(10)
...
```
Which is a scenario that could easily happen, but generally only if you're using a dedicated frontend thread which updates at a regular/fixed interval.

Your fix definitely looks like the right idea. The only part I'm not a fan of is the dynamic divisor calculation, ideally that would only happen when the `term_width` or `max_value` updates where the latter is not really a likely scenario.

Is there any chance you would be able to create a pull request? I'm incredibly busy at the moment and can't put in too much time right now.

**Comment by max-arnold** [comment]
The first reason for dynamic divisor calculation is possible resize of terminal window, and the second one is a lot of different possible terminal window sizes on modern displays.

If you do not have any objections, I'd like to fix utils.get_terminal_size() issue first (I described it here https://github.com/WoLpH/python-progressbar/commit/91cef8860638cee700cce5f34b92a86387b98bbd#commitcomment-14778360).

**Comment by WoLpH** [comment]
That's not what I meant, I don't oppose the division calculation, I just think that it would be better to integrate it with the terminal resize code so the divisor only updates if the screen actually changes size.

That way it wouldn't be needed to recalculate for every `update()`. Although it probably won't matter that much in the end I guess...

Either way, no objections from me. Thanks a lot for the help :)

**Comment by WoLpH** [comment]
The new release is online. Thanks again for all the help @max-arnold :)
