### ISSUE TITLE
tput: No value for $TERM and no -T specified?

### ISSUE THREAD

**Issue by Anjum48** [WoLpH/python-progressbar#44]
Hi,

When I run this:

```python
from progressbar import ProgressBar, Percentage, AbsoluteETA, ETA, Bar
import time

widgets = ['Test: ', Percentage(), ' | ', ETA(), ' | ', AbsoluteETA()]
pbar = ProgressBar(widgets=widgets, maxval=500).start()
for i in range(500):
    time.sleep(0.01)
    pbar.update(i+1)
pbar.finish()
```

I get this output:
```
/usr/bin/python3.4 /home/anjum/Python/pbar_test.py
tput: No value for $TERM and no -T specified
Test: 100% | Time: 0:00:05 | Finished at: 2015/12/08 23:57:28    
```

Does anyone know what the cause of the `tput: No value for $TERM and no -T specified` is?

**Comment by WoLpH** [comment]
The `tput` command is used as a last resort to detect the size of your terminal size but apparently that doesn't work in your case either. The warning can safely be ignored but it should have been caught already. The problem has been fixed in the develop branch.
