### ISSUE TITLE
Keeps printing new lines

### ISSUE THREAD

**Issue by Fentus** [WoLpH/python-progressbar#45]
```
  3% ( 17 of 480) |                        | Elapsed Time: 0:01:25 ETA:  0:41:17
  3% ( 17 of 480) |                        | Elapsed Time: 0:01:25 ETA:  0:41:16
  3% ( 18 of 480) |                        | Elapsed Time: 0:01:30 ETA:  0:41:11
  3% ( 18 of 480) |                        | Elapsed Time: 0:01:30 ETA:  0:41:11
  3% ( 19 of 480) |                        | Elapsed Time: 0:01:36 ETA:  0:41:05
  3% ( 19 of 480) |                        | Elapsed Time: 0:01:36 ETA:  0:41:05
  4% ( 20 of 480) |#                       | Elapsed Time: 0:01:41 ETA:  0:41:02
  4% ( 20 of 480) |#                       | Elapsed Time: 0:01:41 ETA:  0:41:02
```
Python - 3.5.1 - 2015-12-07

I am using your examples same issue

**Comment by WoLpH** [comment]
This is usually caused by having print statements or similar in your code. You can try it with output redirection enabled:
```
bar = progressbar.ProgressBar(redirect_stdout=True, redirect_stderr=True)
```

**Comment by Fentus** [comment]
Humm,

I am not sure whats up this is my code:

import time
import progressbar
bar = progressbar.ProgressBar(redirect_stdout=True, redirect_stderr=True, widgets=[' [', progressbar.Timer(), '] ', progressbar.Bar(), ' (', progressbar.ETA(), ') ', ])
for i in bar(range(20)):
    time.sleep(0.1)

and this is my output:
 [Elapsed Time: 0:00:00] |#                                   | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:00] |#                                   | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:00] |###                                 | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:00] |###                                 | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:00] |#####                               | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:00] |#####                               | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:00] |#######                             | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:00] |#######                             | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:00] |#########                           | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:00] |#########                           | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:00] |##########                          | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:00] |##########                          | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:00] |############                        | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:00] |############                        | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:00] |##############                      | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:00] |##############                      | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:00] |################                    | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:00] |################                    | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:01] |##################                  | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:01] |##################                  | (ETA:  0:00:01) 
 [Elapsed Time: 0:00:01] |###################                 | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |###################                 | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |#####################               | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |#####################               | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |#######################             | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |#######################             | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |#########################           | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |#########################           | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |###########################         | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |###########################         | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |############################        | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |############################        | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |##############################      | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |##############################      | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |################################    | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |################################    | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |##################################  | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |##################################  | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:02] |####################################| (Time: 0:00:02) 
 [Elapsed Time: 0:00:02] |####################################| (Time: 0:00:02) 

I copied it form here just to test: 
http://progressbar-2.readthedocs.org/en/latest/usage.html#bar-with-custom-widgets

That is a perfect copy of the console output. I have tried it with both "redirect_stdout=True, redirect_stderr=True, " and without.

**Comment by WoLpH** [comment]
That's very strange. Which python version and operating system are you
using? Any other software which could have effect? E.g. Cugwin, tmux,
screen

**Comment by Fentus** [comment]
Python 3.5.1 : 2015-12-07
Windows 7

- I've ruled out Eclipse's console by running the program in an admin console.
- I've also ruled out Miniconda3 by installing a 3.5.1 from the official website.

Downloads I used:
- python 3.5.1 - https://www.python.org/downloads/
- progressbar2/3.5.1 - https://pypi.python.org/pypi/progressbar2/3.5.1

**Comment by WoLpH** [comment]
Well, I finally got hold of a Windows system and I can indeed confirm that it's somehow broken... Having that said, I have no good explanation yet why it's broken but I'm trying to find out :)

**Comment by WoLpH** [comment]
I think I've found the problem, can you give the current develop release a try? It's working for me on both python 2.7 and 3.4 on Windows.

**Comment by Fentus** [comment]
Awesome!, Works great in console. (2.7 and 3.5)
Output:
python testprogressbar.py
 [Elapsed Time: 0:00:02] |###################################| (Time: 0:00:02) 



Sadly it dose not work in Eclipse/PyDev console. (2.7 and 3.5)
Output:
 [Elapsed Time: 0:00:01] |######################             | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |########################           | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |##########################         | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |############################       | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |#############################      | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |###############################    | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:01] |#################################  | (ETA:  0:00:00) 
 [Elapsed Time: 0:00:02] |###################################| (Time: 0:00:02)

Thank you so much!

**Comment by Fentus** [comment]
If you plan on fixing Eclipse/PyDev let me know otherwise I will close the issue.
Again thanks a bunch!

**Comment by WoLpH** [comment]
That part seems impossible unfortunately: http://stackoverflow.com/questions/8875938/eclipse-console-window-that-respects-cursor-position-calls-allowing-a-progress-b

The Eclipse console doesn't support it.
