### ISSUE TITLE
regressions in appearance in Jupyter notebooks

### ISSUE THREAD

**Issue by jwkvam** [WoLpH/python-progressbar#46]
Hello, the appearance of the progress bars in Jupyter notebooks has degraded in recent versions. I'm using jupyter notebook 4.0 on osx with chrome. For now I'm sticking with 3.4.0, but I can try to debug the later versions as well.

The last version that looked good was 3.4.0

![image](https://cloud.githubusercontent.com/assets/86304/12183625/d48f7464-b544-11e5-8e06-32bb187d1cbf.png)

In 3.4.1, the progress bars span multiple lines.

![image](https://cloud.githubusercontent.com/assets/86304/12183682/3b76dc4e-b545-11e5-87fb-d36268c2b983.png)

Same behavior in 3.5.2,

![image](https://cloud.githubusercontent.com/assets/86304/12183712/6240036e-b545-11e5-93b2-005b22978629.png)

In 3.6.0, the progress bar doesn't show up until it's actually finished. Below is while it's still looping.

![image](https://cloud.githubusercontent.com/assets/86304/12183751/9f7b5dc8-b545-11e5-827d-fe018607a5c2.png)

Here it has finished.

![image](https://cloud.githubusercontent.com/assets/86304/12183754/a771668a-b545-11e5-8279-8c2537e346a7.png)

**Comment by WoLpH** [comment]
The width detection is obviously wrong in this case, but I'm not entirely certain this is easily fixable...
It seems that jupyter doesn't transmit the notebook width which means that the progressbar is falling back to the terminal width. It appears that your terminal is a lot wider than the notebook in this case ;)

Try this in a notebook to check:
```
import shutil
shutil.get_terminal_size()
```

There are several workarounds:
1. Specify the width of your notebook manually using the `term_width` parameter: `pbar = ProgressBar(term_width=60)`
2. Make the console in which you have jupyter running smaller

The proper solution would be getting the width from the notebook but I don't think it's available

**Comment by mmagnuski** [comment]
I have the same problem. 
Running `shutil.get_terminal_size()` gives me:
```
os.terminal_size(columns=80, lines=25)
```
So the number of columns seems to be correct. But in my case only the invisibility is problematic - once the bar appears (when it is completed) it looks good. 
If I use `term_width=40` the problem persists - the progress bar is invisible until after it is completed.

**Comment by WoLpH** [comment]
That actually indicates it's not correct for you either, 80x25 is the default size of a Windows terminal.

As for the progressbar not showing the progress immediately, it seems that Jupyter handles the print statements slightly different. Luckily that was easily fixable :)
Version 3.6.1 should solve those issues, the width detection is something I can't really fix unfortunately, that depends on the calling terminal session

**Comment by mmagnuski** [comment]
Thanks!
