### ISSUE TITLE
ETA for unknown exactly size

### ISSUE THREAD

**Issue by pohmelie** [WoLpH/python-progressbar#49]
I have «average» max value and can't use it directly, since progress bar will raise exception. But I like ETA and want something like normal progressbar before max_value and UnknownLength after. If this can be done right now by some checks and changing type of progress bar «on the fly» I will be just happy.

**Comment by WoLpH** [comment]
To calculate an ETA you will need a maximum value of course, but that doesn't have to be a fixed number. Depending on the progress bar you can just set a default maximum value and adjust it while using the progress bar to rescale it.

For example:
```
import time
import progressbar

bar = progressbar.ProgressBar()
bar.max_value = 100
for i in range(200):
    bar.update(i)
    bar.max_value = 100 + (i / 2)
    time.sleep(0.1)
```

**Comment by pohmelie** [comment]
@WoLpH, thanks! That is what I exactly expect :wink:
