### ISSUE TITLE
Shows nothing while processing

### ISSUE THREAD

**Issue by FaBay89** [WoLpH/python-progressbar#50]
I just get the finished bar after the process, but there is nothing to see while processing.

Tried some of the examples, but always the same: displays nothing until finish.

Do you or someone have an idea for this issue?

Python 3.4.3 on Win 8.1 and PyCharm IDE

**Comment by FaBay89** [comment]
progressbar version 3.6.1 works fine

**Comment by WoLpH** [comment]
Glad to hear it was fixed already :)
