### ISSUE TITLE
redirect_stdout=True hangs IPython

### ISSUE THREAD

**Issue by miedzinski** [WoLpH/python-progressbar#51]
Hey,
I'm on py 2.7 with progressbar 3.6.1. Example from documentation

```
import time
import progressbar

bar = progressbar.ProgressBar(redirect_stdout=True)
for i in range(100):
    print 'Some text', i
    time.sleep(0.1)
    bar.update(i)
```

works, but after finishing loop, I don't see IPython prompt (although interpreter itself works). Deleting `bar` object doesn't help.

edit:
What's better, using `ProgressBar` as context manager doesn't break IPython. Consider this

```
import time
import progressbar

with progressbar.ProgressBar(redirect_stdout=True) as bar:
    for i in range(20):
        print 'Some text', i
        time.sleep(0.1)
        bar.update(i)
```

**Comment by WoLpH** [comment]
It appears that stdout redirection indeed kills IPython, if you do need output redirection I would suggest to do it towards stderr instead.

```
import sys
import time
import progressbar

bar = progressbar.ProgressBar(redirect_stderr=True)
for i in range(100):
    print >>sys.stderr, 'Some text', i
    time.sleep(0.1)
    bar.update(i)
```

**Comment by WoLpH** [comment]
@miedzinski: does that help with your issue?

**Comment by miedzinski** [comment]
Well, I have solved this by using workaround shown in first post. I don't need the library anymore, so there aren't any problems. If you don't consider this a bug, feel free to close it.

**Comment by WoLpH** [comment]
It's certainly a bug not unfortunately it's one that should be fixed upstream (ipython) instead... I've had a look and it appears there is no proper way to catch this from the progressbar.
