### ISSUE TITLE
dynamic customer message

### ISSUE THREAD

**Issue by raingo** [WoLpH/python-progressbar#53]
Currently, only a single value is used as dynamic message, i.e., the iteration index. It would be helpful to include dynamic customer message in the progress bar. 

For example,
```
bar = ProgressBar(widgets=[Percentage(), DynamicMessage('loss'), max_value=100)
for i in range(100):
  bar.update(i, loss=random.random())
```

Then the bar will output something like
```
9% ( 78 of 100) | loss = 0.55
```

**Comment by WoLpH** [comment]
That could be a useful addition indeed but I'm not entirely sure what would be the best way to implement it... one danger would be to accidently overwrite existing values although that might be something you want.

**Comment by fvisin** [comment]
I wrote a widget to print custom text. It could probably be done in a more clever way, but I am currently using it in my code and it's working fine.

I just created a PR with it: #59

**Comment by joe-antognini** [comment]
I wrote another widget to do this (PR #66).  It modifies the update function to accept arbitrary keyword arguments (as long as the user has created a corresponding DynamicMessage widget) and add them to the progress bar like @raingo wants.  @raingo's example would work with no modification.

**Comment by WoLpH** [comment]
It's merged and released now :)

Thanks for all the help!

**Comment by fvisin** [comment]
Great! :)

**Comment by raingo** [comment]
Great. Thanks!
