### ISSUE TITLE
progressbar deos not finish correctly

### ISSUE THREAD

**Issue by nescioz** [WoLpH/python-progressbar#54]
sometimes even if updating the progressbar with the max_value, the progressbar does not finish with 100%. 

This is due to the following logic in `_needs_update` method:

        if self.poll_interval:
            delta = datetime.now() - self.last_update_time
            poll_status = delta > self.poll_interval

        # Do not update if value increment is not large enough to
        # add more bars to progressbar (according to current
        # terminal width)
        try:
            divisor = self.max_value / self.term_width  # float division
            if self.value // divisor == self.previous_value // divisor:
                if self.poll_interval:
                    return poll_status
                return False
        except:
            # ignore any division errors
            pass

        if self.value > self.next_update or self.end_time:
            return True
        elif self.poll_interval:
            return poll_status

even if updating with max_value, the method still returns False if the increment is not large enough.
suggest add the logic that returns True when max_value is reached.

**Comment by liuyug** [comment]
Do not force redrew when call finish.  

Test: 
```
import progressbar

m = 24514315
p = progressbar.ProgressBar(
    widgets=[progressbar.Percentage(), progressbar.Bar()],
    max_value=m
)

for x in range(0, m, 8192):
    p.update(x)
p.finish()
```
