### ISSUE TITLE
Allow ETA, AbsoluteETA, etc to change the string prefixes

### ISSUE THREAD

**Issue by jtbraun** [WoLpH/python-progressbar#60]
`AbsoluteETA` currently prepends a long string "Estimated finish time: " before the date.  The base `Timer` object allows the `format` kwarg to modify the text printed.  `AbsoluteETA` and `ETA` should allow something similar, rather than hardcode the prefix string(s).

**Comment by WoLpH** [comment]
Good idea, I'll add it in the next update :)

**Comment by WoLpH** [comment]
They are editable in the development release. The new version should be release soon :)
