### ISSUE TITLE
maxval and max_value

### ISSUE THREAD

**Issue by lobachevzky** [WoLpH/python-progressbar#62]
I'm trying to use ProgressBar with a data file that I'm iterating through. My code is:
`        with open(filepath(RATINGS_FILE)) as data, ProgressBar(max_value=600) as bar:`
This throws
`TypeError: __init__() got an unexpected keyword argument 'max_value'`

Also, 
`        with open(filepath(RATINGS_FILE)) as data, ProgressBar(maxval=600) as bar:`
simply throws
`AttributeError: __exit__`

**Comment by WoLpH** [comment]
I can't reproduce that in the current version so I think you might have an older version of the module installed.

Can you tell me which version you have installed?
```
import progressbar
print(progressbar.__version__)
```

**Comment by lobachevzky** [comment]
I have 2.3.

**Comment by WoLpH** [comment]
That has to be the problem in that case, that is the original version this package was forked from.

I would recommend uninstalling that version and installing this one:
```
pip unininstall -y progressbar
pip install -y progressbar2
```

Although it does appear that the original version is alive again after no maintenance for about 5 years.

**Comment by lobachevzky** [comment]
Ah. Thank you.
