### ISSUE TITLE
Progress bar is not plotting when progress is equal to 0

### ISSUE THREAD

**Issue by aaamourao** [WoLpH/python-progressbar#63]
Considering the following code,
```python
from progressbar import ProgressBar
import time

with ProgressBar(max_value=10) as pbar:
    for i in range(10):
        # long, loooong wait
        sleep(10000000)
        pbar.update(i)
```

Running that, it will take a long time for the process bar get printed. It does not print 0% progress, what is useful for iterations that requires long time to run.

I found the bug both on `progressbar2==3.6.2` and `git+https://github.com/WoLpH/python-progressbar.git@develop`

**Comment by cbrnr** [comment]
I can reproduce this behavior (although in your example, the last line should be `pbar.update(i + 1)`). Here's a slightly modified example:

```Python
from progressbar import ProgressBar
import time

pbar = ProgressBar(max_value=10).start()

for i in range(10):
    time.sleep(2)
    pbar.update(i + 1)
```

However, when I debug this example, it works as expected (the bar is shown at 0%). The `start` method calls `update`, but I don't know why this only works when debugging. Maybe a timing issue?
