### ISSUE TITLE
NullBar ?

### ISSUE THREAD

**Issue by stuaxo** [WoLpH/python-progressbar#65]
It would be useful to have a bar that does nothing at all.

Rational - I have a bunch of functions that can take a bar, and it would be nice to not have to check for None -

```python
def myfunc(bar=Nullbar()):
    with bar:
         bar.update()
```

or

```python
def myfunc(bar=None):
    bar = bar or Nullbar()
    with bar:
         bar.update()
```

**Comment by WoLpH** [comment]
I see how this could be useful indeed, I've just added it to the current development release :)

**Comment by stuaxo** [comment]
Awesome, cheers :)
