### ISSUE TITLE
Silencing stdout for use in frozen apps

### ISSUE THREAD

**Issue by lifeofdave** [WoLpH/python-progressbar#69]
I'm using progress bar for the speed and eta widgets, however I'm displaying the output using qt instead of stdout. This works well but when using it in a frozen app I'm finding that py2exe tries to write the stdout from progress bar to a logfile which is causing me some issues. 

Is there a simple way to 'silence' the output from progressbar?

**Comment by WoLpH** [comment]
I've thought about this for a bit and I think the easiest method might be to simply write to a different output stream. Currently that's not really supported though... I'll see if I can create a setting/global flag to configure.

**Comment by lifeofdave** [comment]
Sounds good, let me know if I can help by testing etc.

**Comment by WoLpH** [comment]
Since implementing a global setting might be a bit messy, is it possible for you to add an argument to the progressbar? All of the standard progress bars support a `fd` parameter. Setting that to a null-fd should do the trick.

```
import os
import time
import progressbar


null = open(os.devnull, 'w')

bar = progressbar.ProgressBar(fd=null)
for i in bar(range(100)):
    time.sleep(0.1)
```

**Comment by WoLpH** [comment]
If the solution doesn't work for you and needs a different fix, feel free to let me know so I can reopen :)

**Comment by lifeofdave** [comment]
Thanks Rick, this worked great. Hope this reply doesn't reopen the issue.

On 23 June 2016 at 17:37, Rick van Hattem <notifications@github.com> wrote:

> If the solution doesn't work for you and needs a different fix, feel free
> to let me know so I can reopen :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/WoLpH/python-progressbar/issues/69#issuecomment-228108166>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABHAJTqA8KZCL5RABkRCbDG1fqjRU5qnks5qOrZCgaJpZM4I0kkU>
> .
>



-- 

David Sinclair

**Comment by WoLpH** [comment]
Good to hear :)

And reopening is a manual process so no worries
