### ISSUE TITLE
io.UnsupportedOperation with redirect_stdout=True

### ISSUE THREAD

**Issue by saveman71** [WoLpH/python-progressbar#75]
Hello there,

I'd like to print as my progress bar gets updated, and if I understood correctly, the `redirect_stdout` option would be the correct option to activate.

However, I'm facing the following issue, and Google searches reveals infructuous.

Minimal failing code:

```python
import time
import progressbar

bar = progressbar.ProgressBar(redirect_stdout=True)
for i in range(100):
    print('Some text', i)
    time.sleep(0.1)
    bar.update(i)
```

Which yields the following:
```
Some text 0
Traceback (most recent call last):
  File "./test_progress.py", line 8, in <module>
    bar.update(i)
  File "/tmp/env/lib/python3.5/site-packages/progressbar/bar.py", line 465, in update
    self.start()
  File "/tmp/env/lib/python3.5/site-packages/progressbar/bar.py", line 539, in start
    self.update(self.min_value, force=True)
  File "/tmp/env/lib/python3.5/site-packages/progressbar/bar.py", line 496, in update
    StdRedirectMixin.update(self, value=value)
  File "/tmp/env/lib/python3.5/site-packages/progressbar/bar.py", line 119, in update
    if self.redirect_stdout and sys.stdout.tell():
io.UnsupportedOperation: underlying stream is not seekable
```

Executed as:
```bash
python ./test_progress.py
```

I'm using python 3.5.1 inside virtualenv, with python-progressbar2 installed with pip.

The environment is ArchLinux, latest kernel, can reproduce with and without tmux.

**Comment by WoLpH** [comment]
That's very odd. I've tested it on a Ubuntu Linux machine and it works just fine for me with Python 3.5.1.

Can you show me what your stdout looks like?
```
import sys
print(sys.stdout)
print(repr(sys.stdout))
print(type(sys.stdout))
```

For me it looks something like this:
```
>>> import sys
>>> print(sys.stdout)
<_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
print(repr(sys.stdout))
print(type(sys.stdout))>>> print(repr(sys.stdout))
<_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
print(type(sys.stdout))>>> print(type(sys.stdout))
<class '_io.TextIOWrapper'>
```

**Comment by saveman71** [comment]
```
>>> import sys
>>> print(sys.stdout)
<_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
>>> print(repr(sys.stdout))
<_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
>>> print(type(sys.stdout))
<class '_io.TextIOWrapper'>
```

Not so much of a difference here.

**Comment by WoLpH** [comment]
For some reason it appears that pypi still had an old version. Can you try updating? to the latest version?
```
pip install 'progressbar2==3.9.3'
```

**Comment by saveman71** [comment]
Solved the problem :D :+1:

I'll leave the issue open, if you want to have a reminder to update the PyPi version, feel free to close it

**Comment by WoLpH** [comment]
It's on pypi, otherwise you couldn't have updated :)

Thanks for the heads up!

**Comment by saveman71** [comment]
Ah yes my bad, I'm not very familiar with pip/pypi ;)
