### ISSUE TITLE
Double elapsed time, and no ETA

### ISSUE THREAD

**Issue by petercombs** [WoLpH/python-progressbar#77]
Working on Python 3.5.1 with version 3.9.3 of progressbar on an Arch linux system, when I run a progress bar, the ETA first appears empty, then 0, then gets replaced with the elapsed time again. 
```
import progressbar as pb
import time
print(pb.__version__)
for i in pb.ProgressBar()(list(range(100))):
    time.sleep(3)
```
gives something like the following (I've snipped whitespace for conciseness) 
```  
3.9.3
0% (  0 of 100) |                                    | Elapsed Time: 0:00:00 ETA:  --:--:--
1% (  1 of 100) |#                                   | Elapsed Time: 0:00:20 ETA:  0:00:00
2% (  2 of 100) |##                                  | Elapsed Time: 0:00:40 Elapsed Time: 0:00:40
```

**Comment by WoLpH** [comment]
For some reason the previous release was heavily broken... it mixed old and newer versions together resulting in something partially broken. Just upgrade to version 3.9.4 and you should be good again :)

```
pip install 'progressbar2>=3.9.4'
