### ISSUE TITLE
Error in examples.py: io.UnsupportedOperation (progressbar2 v3.9.4)

### ISSUE THREAD

**Issue by bastelflp** [WoLpH/python-progressbar#78]
### Description
In a new [Anaconda](https://www.continuum.io/downloads) environment on Win7_x64 and after `pip install progressbar2` I got the following error executing ` python examples.py` from the command line (status of the repo was [b58bb8](https://github.com/WoLpH/python-progressbar/blob/b58bb8e4288a5d1717565b3700f0af3784c7e161/examples.py), but the `examples.py` was copied to another folder):

```python
Running: with_example
100% (10 of 10) |###################################################| Elapsed Time: 0:00:01 Time: 0:00:01

Running: with_example_stdout_redirection
Traceback (most recent call last):
  File "examples.py", line 492, in <module>
    test(*sys.argv[1:])
  File "examples.py", line 486, in test
    example()
  File "examples.py", line 33, in wrapped
    fn()
  File "examples.py", line 55, in with_example_stdout_redirection
    with progressbar.ProgressBar(max_value=10, redirect_stdout=True) as p:
  File "C:\Users\usr\Anaconda\envs\test\lib\site-packages\progressbar\bar.py", line 388, in __enter__
    return self.start()
  File "C:\Users\usr\Anaconda\envs\test\lib\site-packages\progressbar\bar.py", line 539, in start
    self.update(self.min_value, force=True)
  File "C:\Users\usr\Anaconda\envs\test\lib\site-packages\progressbar\bar.py", line 496, in update
    StdRedirectMixin.update(self, value=value)
  File "C:\Users\usr\Anaconda\envs\test\lib\site-packages\progressbar\bar.py", line 119, in update
    if self.redirect_stdout and sys.stdout.tell():
io.UnsupportedOperation: underlying stream is not seekable
```

### Used versions
The used Python version is:
>Python 3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32

`pip show progressbar2` tells version `3.9.4`

```
Metadata-Version: 2.0
Name: progressbar2
Version: 3.9.4
[...]
```

### Other behavior with PyCharm
Interestingly, the error does **not** occur, when executed via [PyCharm](https://www.jetbrains.com/pycharm/), **but** the wrapper for the printed name of the example is missing (e.g. `Running: basic_widget_example`) after the example which produced the error above:

```
Running: with_example
100% (10 of 10) |#########################| Elapsed Time: 0:00:01 Time: 0:00:01
  0% ( 0 of 10) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--
Running: with_example_stdout_redirection
100% (10 of 10) |#########################| Elapsed Time: 0:00:01 Time: 0:00:01
100%|#########################################################################|
Test: 100% ||                                       | Time: 0:00:00  54.3 KiB/s
 69.7 KiB/s <<<|########################################|>>> 100% Time: 0:00:00
|>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>| Time: 0:00:01 |<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<|
Test: 100% [000000000000000000000000000000000000000000] Time: 0:00:00 555.5 B/s
[...]
```

### No error with v3.9.3
This is related to #75 and after installing version `3.9.3` directly via `pip install progressbar2==3.9.3` the examples did not show any error and PyCharm printed all examples.

**Comment by WoLpH** [comment]
Hmm... that's a bit unfortunate. I'll see what we can do :)

And I'll try adding anaconda as a testing platform. It seems that should be possible too.

**Comment by WoLpH** [comment]
I've pushed a possible fix for the problem, can you try the latest development release?

Also, thank you for the very detailed bug report. It's greatly appreciated!

**Comment by bastelflp** [comment]
I tested the current code from the `develop` branch and the error is now caught.

Running `python examples.py` from the command line with the same environment as above (but uninstalled progressbar2 to really use the sources from the git repos) yields:

```
python examples.py
Running: with_example
100% (10 of 10) |########################| Elapsed Time: 0:00:01 Time: 0:00:01

Running: with_example_stdout_redirection
Disabling stdout redirection, <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp850'> is not seekable
100% (10 of 10) |########################| Elapsed Time: 0:00:01 Time: 0:00:01

Running: basic_widget_example
100%|########################################################################|

Running: file_transfer_example
Test: 100% ||                                      | Time: 0:00:00  32.6 KiB/s

Running: custom_file_transfer_example
 51.4 KiB/s <<<|#######################################|>>> 100% Time: 0:00:00

Running: double_bar_example
|>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>| Time: 0:00:01 |<<<<<<<<<<<<<<<<<<<<<<<<<<<<<|

Running: basic_file_transfer
Test: 100% [00000000000000000000000000000000000000000] Time: 0:00:00 553.1 B/s

Running: simple_progress
17 of 17
```

with the `Disabling stdout redirection...` log message.

----

Interestingly while executing `examples.py` inside PyCharm, the error does not occur (at least no log message is printed), but the console output of the wrapper is skipped / missing as described in the initial entry. I never had this divergent behavior before. But nevertheless: Both cases work without breaking.

**Comment by WoLpH** [comment]
PyCharm most likely does it's own type of output redirection which makes this slightly less trivial. An easier method to do both might be by printing to stderr and writing the progressbar to stdout (or vice versa). But that's a theoretical solution, I'll test a bit to see what works.

The way I do output redirection changed slightly in the latest version. Where I recreated the stdout/stderr output stream on flushing earlier I keep reusing the same one now. It seems I'll need to improve the code to automatically switch between the two depending on the environment.

Between python 2, python 3, anaconda, ipython, idle and pycharm output redirection is not that easy. All of them use slightly different approaches which results in fixing 1 and breaking another...

**Comment by matthewwardrop** [comment]
@WoLpH: This fix (using stderr.tell()) breaks progressbar2 on Jupyter Notebooks which uses and OutStream object for stderr which does not have a `.tell` method.

**Comment by WoLpH** [comment]
I've created a new and better fix which should work in all cases or degrade gracefully so I think the problem is properly solved now.

Can you test the 3.10.0 release to be sure? :)

**Comment by bastelflp** [comment]
In a new Anaconda environment with the following Python version

> Python 3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32

and after installing 3.10.0 from the current develop branch (53f8ebb) via `python setup.py install` I got no errors running `python examples.py` from the command line.

The same is true for executing `examples.py` in **PyCharm** in this environment: no errors and all example names printed.

After installing the current release via `pip install progressbar2` (version `3.10.0`) in another new Anaconda environment, executing `python examples.py` yields no errors as well.

**Comment by WoLpH** [comment]
Awesome! Thanks for testing :)
