### ISSUE TITLE
Add anaconda testing

### ISSUE THREAD

**Issue by WoLpH** [WoLpH/python-progressbar#79]
Howto: http://conda.pydata.org/docs/travis.html

This should fix issues such as #78

**Comment by bastelflp** [comment]
That's great, but I didn't find a progressbar2 package in the conda packages and installed progressbar2 via pip despite being in a conda environment.

**Comment by WoLpH** [comment]
True, I haven't created one yet. Perhaps I'll create one

**Comment by WoLpH** [comment]
Unfortunately it seems less than trivial to get travis to auto-test the code... perhaps I'll add this at a later point.

As for a pure conda release, is there any benefit to doing that as opposed to a pip release? It seems there's currently no easy way to deploy to both pypi and conda at the same time which probably means that I'll forget...

**Comment by bastelflp** [comment]
> Unfortunately it seems less than trivial to get travis to auto-test the code... perhaps I'll add this at a later point.

Probably *more* than trivial as I understand your changes.

Concerning the conda release: It integrates easier with conda environments and [environment.yml](http://conda.pydata.org/docs/using/envs.html#share-an-environment) to share an environment, but it is still possible to use pip [in general](http://conda.pydata.org/docs/using/pkgs.html#install-non-conda-packages) or even use [pip packages in environment.yml](http://stackoverflow.com/a/35245610/5276734), so this is nice to have but not absolutely essential.

**Comment by WoLpH** [comment]
Ah, yes indeed :)

For the time being I'll hold off the creation of Conda packages until supports it.
Upstream issue: https://github.com/travis-ci/travis-ci/issues/4884

**Comment by jakirkham** [comment]
If you want to create a conda package, I would recommend doing it via [conda-forge]( https://conda-forge.github.io/ ). Happy to help answer question/guide you through the process if you are interested.

**Comment by WoLpH** [comment]
If #86 is ever fixed this can be fixed as well
