### ISSUE TITLE
key_word problem

### ISSUE THREAD

**Issue by ztt1024** [WoLpH/python-progressbar#80]
#### Description
I just ran the example code, and it displayed 
`_init__() got an unexpected keyword argument 'max_value'`

#### Code

```
import time
import progressbar

with progressbar.ProgressBar(max_value=10) as bar:
    for i in range(10):
        time.sleep(0.1)
        bar.update(i)
```

#### Versions

- Python version: `import sys; print(sys.version)`
- Python distribution/environment: CPython/Anaconda/IPython/IDLE
- Operating System: Windows 10, Ubuntu Linux, etc.   
- Package version: `import progressbar; print(progressbar.__version__)`  

python version:2.7.6
python environment:anaconda
operating system: Ubuntu
package version:3.9.4

**Comment by WoLpH** [comment]
This is a very strange problem and the only way I can explain how this is happening if for some reason the code is importing a different progressbar class. To make debugging a bit easier can you show the output of this code (place it right before the `with progressbar.ProgressBar...` statement)

```
print 'progressbar', progressbar
print 'Progressbar', progressbar.ProgressBar
```

**Comment by ztt1024** [comment]
Hi,
Thanks for your reply.
I just write the codes and the output as follows
print 'progressbar', progressbar
progressbar <module 'progressbar' from '/usr/local/lib/python2.7/dist-packages/progressbar2-3.9.4-py2.7.egg/progressbar/__init__.pyc'>


print 'Progressbar', progressbar.ProgressBar
Progressbar <class 'progressbar.bar.ProgressBar'>

**Comment by WoLpH** [comment]
Ok, that was not the output I expected. Let's try it again with a `repr()`:

```
print repr(progressbar)
print repr(progressbar.ProgressBar)
```

**Comment by ztt1024** [comment]
The output should be :

print repr(progressbar)
<module 'progressbar' from '/usr/local/lib/python2.7/dist-packages/progressbar2-3.9.4-py2.7.egg/progressbar/__init__.pyc'>
 print repr(progressbar.ProgressBar)
<class 'progressbar.bar.ProgressBar'>

**Comment by WoLpH** [comment]
That output is all as expected, I have to say that I'm stumped... I can't think of a single reason why you would get these results so I would recommend removing the progressbar directory completely and reinstalling it.

First uninstall progressbar2 and after that remove the directory so you can reinstall it again:
```
pip uninstall progressbar2 -y
rm -rf /usr/local/lib/python2.7/dist-packages/progressbar2*
pip install -y progressbar2
```

**Comment by WoLpH** [comment]
Please let me know if you still have this problem. I'll close this issue for the time being.
