### ISSUE TITLE
Does not work Jupyter Notebooks (as of recent update)

### ISSUE THREAD

**Issue by matthewwardrop** [WoLpH/python-progressbar#82]
#### Description

Jupyter notebooks use an OutStream object as stderr, and progressbar2 uses stderr.tell(), which is not a valid method of OutStream, consequently breaking code. I'm not sure why this worked until recently, but it did. My guess is that the change to using OutStream is recent.

#### Code

The call that breaks Jupyter happens on line 108 of progressbar/bar.py .

#### Versions

jupyter 1.0.0, jupyter-client 4.3.0, ipython 5.0.0, notebook 4.2.1, python *
Progress bar 3.9.4 (not sure exactly which version introduced the dependence on tell).

**Comment by matthewwardrop** [comment]
Hmm... on second glance, this looks like it might have been a recent change in jupyter/ipython

**Comment by WoLpH** [comment]
This is similar to #78 

Unfortunately there is no simple way to function in all environments it seems. I'll see if I can work around the problem :)

Thanks for the heads up!

**Comment by matthewwardrop** [comment]
Hey! I like this solution. Thanks Wolph!

**Comment by WoLpH** [comment]
It's not a 100% yet, I'm still testing but I should have a new release within a few hours :)

**Comment by WoLpH** [comment]
I believe it's fully working now and I have special jupyter notebook detection (so the screen size is at least a fixed size instead of taken from the parent console).

Can you test the 3.10.0 release to be sure? :)

**Comment by matthewwardrop** [comment]
Progressbar2 3.10.0 works great in Jupyter; and I appreciate better detection of the console output size :). I used your method elsewhere, so now I get improved performance for free! Thanks WoLpH.
