### ISSUE TITLE
update() is very slow

### ISSUE THREAD

**Issue by Aex12** [WoLpH/python-progressbar#83]
I am using a progressbar with maxval of 2000000. I am testing my code perfomance and it can run the whole loop in 5 seconds more or less. When I use this progressbar the total time increases to 45seconds.

Is there any parameter to make it more efficient with large amounts of updates?

**Comment by WoLpH** [comment]
You are probably updating quite often. When using many different values I would recommend updating less often.

For example:

```
import progressbar

bar = progressbar.ProgressBar()
for i in range(10000000):
    if i % 100 == 0:
        bar.update(i)
```

That only updates once every 100 values. The update method does quite a lot of operations so if you know that you'll do many updates this might help a bit.

**Comment by Aex12** [comment]
I set it up to update it only every 50.000 registers and now it has a much better perfomance, the difference without it is only of one second. Worth it. TH
