### ISSUE TITLE
conda-forge recipe

### ISSUE THREAD

**Issue by maartenbreddels** [WoLpH/python-progressbar#86]
Related to #79, I'd like to have progressbar2 in the conda-forge channel for conda, it's pretty easy to do, check out:
https://conda-forge.github.io/#add_recipe
Great package btw 👍 , I'm using it for [vaex](https://github.com/maartenbreddels/vaex)

**Comment by WoLpH** [comment]
Creating the conda package is not that hard but keeping it up to date is the issue. I don't have conda installed everywhere and I'll probably forget to push it to conda when I release a new pypi package. I'm currently hoping for conda support in travis to take care of this: https://github.com/travis-ci/travis-ci/issues/4884

With that the deploy will be done fully automatic by travis so I don't need to worry about forgetting it. Similar to how releases get automatically created right now: https://github.com/WoLpH/python-progressbar/releases

**Comment by maartenbreddels** [comment]
(You don't need conda in travis, you can simply download it, as I do for instance:
https://github.com/maartenbreddels/vaex/blob/master/.travis.yml)
But you don't need to build yourself, in conda-forge, everything is build for you on win,osx,linux and for a few Python version.

**Comment by WoLpH** [comment]
Ah, so that code automatically updates the package on conda? Cause that's the only thing stopping me right now :)

I'll give it a go

**Comment by maartenbreddels** [comment]
yes that is at least how I understand it. You do have to update the recipe though after a new release, but that can be scripted, wget from pypi, calculate hash, put the new version and hash in the recipe and push the changes.

**Comment by WoLpH** [comment]
One snag seems to be that you are required to create a pull request towards https://github.com/conda-forge/staged-recipes every time you push a new release. But, it's not impossible it seems so I'll keep it on my to-do for the time being :)

**Comment by maartenbreddels** [comment]
Do you mind if I create one, and also mark you as maintainer?

**Comment by WoLpH** [comment]
Not at all, that would be great. I have made zero experience with Conda so
it will take me far more time to figure it out.

Thanks for the help

**Comment by WoLpH** [comment]
Notice: this issue has been closed because it has been inactive for 172 days. You may reopen this issue if it has been closed in error.
