### ISSUE TITLE
Jupyter notebook issues

### ISSUE THREAD

**Issue by gauss256** [WoLpH/python-progressbar#87]
#### Description

The progressbar writes to stderr. This causes its output to be displayed on a red background. More seriously, if you print something after the progress operation is finished, stderr is not flushed automatically so the display of the progressbar usually gets split up by the print statement.

#### Code

```
with ProgressBar(max_value=100) as progress:
    for i in range(100):
        sleep(0.01)
        progress.update(i + 1)
sys.stderr.flush()  # if you comment out this line, the display is wrecked by the following print()
print("That's all folks!")
```

#### Versions

- Python 3.5
- Anaconda distribution
- Ubuntu 14.04
- Package version: 3.10.0

**Comment by WoLpH** [comment]
You're right, perhaps a forced flush is in order :)
Can you try the latest develop branch to see if that solves the issue?

Note that if you prefer stdout instead of stderr you can simply specify the stream like this:
````
import sys

ProgressBar(fd=sys.stdout)
```

**Comment by gauss256** [comment]
I missed the option for `ProgressBar(fd=sys.stdout)`. That may be the best solution for me anyway.

But I'll try the latest develop branch and will let you know.

**Comment by WoLpH** [comment]
Additionally, if you're planning on mixing the progressbar with print statements make sure to try the output redirection flags :)

**Comment by gauss256** [comment]
1. The new flush feature works great
2. I don't quite get the output redirection. Looked for some docs and couldn't find them. I experimented with them to see what they do, but I ended up getting the notebook into a state where the print statements didn't output anything in subsequent cells. If I can reproduce that I'll let you know.

**Comment by gauss256** [comment]
If I use `fd=sys.stdout` then `redirect_stdout=True` works fine. But if the progressbar's output is going to stderr, then the redirect makes a mess. I'm not what I would really expect it to do in that case, so I'm not really complaining.

**Comment by WoLpH** [comment]
The output redirection documentation is not that extensive: http://progressbar-2.readthedocs.io/en/latest/usage.html#combining-progressbars-with-print-output

It comes down to capturing stdout/stderr output and making sure the progressbar won't overwrite it. With Jupyter it's all a bit dodgy however as it wraps the output.

**Comment by gauss256** [comment]
Got it. It was a pleasant surprise that progressbar worked with Jupyter at all. :) And now it is working really well. Thanks for your help and for a great library!
