### ISSUE TITLE
Mistaken FileTransferSpeed with maxval=0

### ISSUE THREAD

**Issue by ARF1** [WoLpH/python-progressbar#89]
#### Description

If one initialises a progressbar with `maxvalue=0` (because maybe the potential task is already completed), the FileTransferSpeed is calculated to non-null value even though no transfer has taken place. (See value of 8.3 B/s in example below.)

#### Code

```
In [5]: from progressbar import (AnimatedMarker, Bar, ETA, AdaptiveETA,
   ...:                          FileTransferSpeed, Percentage, ProgressBar,
   ...:                          RotatingMarker)
   ...: 

In [7]: widgets = ['Downloading files: ', Percentage(), ' ', Bar(), ' ', 
   ...:            AdaptiveETA(), ' ', FileTransferSpeed()]
   ...: 
   ...: pbar = ProgressBar(widgets=widgets,
   ...:                    maxval=0,
   ...:                    ).start()
   ...: 

Downloading files:   0% |                            | ETA:  --:--:--   0.0 s/B

In [8]: pbar.finish()

Downloading files: 100% |#############################| Time: 0:00:11   8.3 B/s

```
#### Versions

- Python version: `3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:45:57) [MSC v.1900 32 bit (Intel)]`
- Python distribution/environment: Anaconda/IPython
- Operating System: Windows 8
- Package version: `3.11.0`

**Comment by WoLpH** [comment]
The reason `maxval=0` is allowed is that there are a few cases where negative values can occur so that part is expected.

And if there's any time between creating the progressbar and finishing it, it would still calculate the estimate of that near-zero time with a non-zero value to prevent zero-division errors.

So the question is now, what kind of output would you expect? The 11 seconds you can see are the difference between the `start()` and `finish()` call and that time has to be attributed to something.

**Comment by ARF1** [comment]
@WoLpH Just to be clear, I have no issue with `maxval=0` being allowed. I think it is a useful option, even then `maxval=0`, because it allows removing flow logic to handle such corner cases from the user's code and delegating handling of them to the progressbar.

What king of output would I expect?

Well if `pbar.min_value = 0` and `pbar.value = 0` when `pbar.finish()` is called and `pbar.value` is assumed to be in bytes for use of the FileTransferSpeed widget, then transfer speed should be:

`(pbar.value - pbar.min_value) / seconds_elapsed = 0` in bytes/second. Certainly not `8.3 B/s` unless my math is mistaken. I would also accept a value of `-.- B/s` as a valid option since no update has ever taken place which could be taken to imply that no data was transferred.

I realise that this is a purely optical issue and a corner case. - But `progressbar2` is all about optics, is it not?

**Comment by WoLpH** [comment]
I found the problem, it's because you're using the deprecated `maxval` parameter instead of `max_value`. If you use `max_value` it should work properly :)
