### ISSUE TITLE
No newline after progressbar

### ISSUE THREAD

**Issue by landergate** [WoLpH/python-progressbar#91]
Experienced the same issue as described in #32

Package: 3.12.0
Python: 3.4.3

**Comment by WoLpH** [comment]
What kind of terminal (windows cmd, linux xterm, ipython notebook, etc.) are you running it in? I'm not able to reproduce the problem using the test code mentioned in #32.

**Comment by landergate** [comment]
@WoLpH 
Linux xterm through win SSH-client Kitty 0.67.1.3 (Putty's fork).

Lack of `\n` is happening when doing `bar.update()` outside of the progressbar's context wrappers:

``` python
#!/usr/bin/env python3
import time
import progressbar

len = 40

bar = progressbar.ProgressBar(max_value=len)

i = 0
for i in range(len):
    time.sleep(0.1)
    i += 1
    bar.update(i)

print('Hello World')
```

```
# ./progressbar_test.py
100% (40 of 40) |#########################| Elapsed Time: 0:00:03 ETA:  0:00:00Hello World
```

**Comment by WoLpH** [comment]
In that case it's actually expected. The `bar.finish()` method takes care of the newline. If you're not wrapping it you'll have to call it yourself. 

Here's an exerpt from the docs: http://pythonhosted.org/progressbar2/progressbar.bar.html#progressbar.bar.ProgressBar

> ```
> >>> progress = ProgressBar().start()
> >>> for i in range(100):
> ...     progress.update(i+1)
> ...     # do something
> ...
> >>> progress.finish()
> ```
> You can also use a ProgressBar as an iterator:
> ```
> >>> progress = ProgressBar()
> >>> some_iterable = range(100)
> >>> for i in progress(some_iterable):
> ...     # do something
> ...     pass
> ...
> ```

**Comment by landergate** [comment]
@WoLpH
You're right, overlooked that.
Thanks for your time, and have some happy holidays =)

**Comment by WoLpH** [comment]
Happy holidays to you as well :)
