### ISSUE TITLE
Progressbar printed 2 times

### ISSUE THREAD

**Issue by tboquet** [WoLpH/python-progressbar#92]
#### Description

Hello, 2 progress bars are printed in my jupyter notebook.
If I use a simple example I get this:

#### Code

```python
bar = progressbar.ProgressBar()
for i in bar(range(100)):
    time.sleep(0.02)
```

```
100% (100 of 100) |##########################################################################################################################| Elapsed Time: 0:00:02 Time: 0:00:02  1% (1 of 100) |#                                                                                                                           | Elapsed Time: 0:00:00 ETA:  0:00:00
```

#### Versions

I'm using Ubuntu 14.04.5 LTS
and python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
progressbar2==3.12.0
ipykernel==4.5.2
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.1

**Comment by WoLpH** [comment]
Very odd, I can't reproduce it yet but I'll try on a few other platforms as well

**Comment by WoLpH** [comment]
So far I've had no luck replicating this behaviour. I have a feeling it's related to the output redirection process. Can you try creating the progressbar with `redirect_stdout=True` and test again?

**Comment by tboquet** [comment]
No pb I'll try this tomorow. I feel like it's a jupyter notebook error. I got a strange behavior with another library too.

**Comment by WoLpH** [comment]
Jupyter notebooks certainly change the rules a little bit, but it's a tested scenario and should function :) 

The biggest problem with Jupyter is that it takes the variables from the shell environment that triggered it. Not from Jupyter itself.

**Comment by WoLpH** [comment]
Notice: this issue has been closed because it has been inactive for 58 days. You may reopen this issue if it has been closed in error.

**Comment by jimrybarski** [comment]
Could you repoen this please? I also have the same issue, plus some additional information that might help.

With either `redirect_stderr=True`, `redirect_stdout=True` or nothing in the constructor in the code below, I get two output lines (one while the loop is running, and then the duplicate when it completes):

```
import progressbar
import time

with progressbar.ProgressBar(redirect_stderr=True) as pbar:
    pbar.start()
    for i in pbar(list(range(100))):
        time.sleep(0.05)
```

This does not produce duplicates (implicating the context manager):

```
import progressbar
import time

pbar = progressbar.ProgressBar(redirect_stderr=True)
pbar.start()
for i in pbar(list(range(100))):
    time.sleep(0.05)
```

This will have three duplicate lines at the end:

```
import progressbar
import time

with progressbar.ProgressBar(redirect_stderr=True) as pbar:
    pbar.start()
    for i in pbar(list(range(100))):
        time.sleep(0.05)
    pbar.finish()
```

Here's are screenshot just so it's clear what I mean by duplicates:

While any of these are running:
![screenshot_20180323_182758](https://user-images.githubusercontent.com/1509268/37857314-13d6031e-2ec8-11e8-88ee-2c4c1a153117.png)

After the loop is finished in the last example:
![screenshot_20180323_182846](https://user-images.githubusercontent.com/1509268/37857315-16564a72-2ec8-11e8-8ab6-7c0c8d82961a.png)

**Comment by WoLpH** [comment]
On the plus side, I can reproduce it. But... I have no clue why it's doing this :/

When manually trying to reproduce it with a few print statements I don't get any similar results but at least the progress bar is consistently repeating the print statements.

**Comment by davidparsson** [comment]
I'm seeing the same thing on with Python 3.6.2 without ipython/jupyter, with even less code:
```
import time
import progressbar

with progressbar.ProgressBar() as progress:
    for _ in progress(range(10)):
        time.sleep(0.1)
```

I'm using a minimal virtualenv with this installed:
```
progressbar2==3.36.0
python-utils==2.3.0
six==1.11.0
```

The issue is resolved by not using the context manager.

**Comment by WoLpH** [comment]
Ah, that makes sense. The context manager automatically does the `finish()` but it should check whether it's finished already. Thanks for tracking that down :)

**Comment by WoLpH** [comment]
I've

**Comment by WoLpH** [comment]
I've pushed an update to develop which should fix the issue. Can you guys test if it works correctly for you?

**Comment by davidparsson** [comment]
Yes, that resolves the issue for me. Thanks! 💐

**Comment by WoLpH** [comment]
Great! Now let's see if I can add a test that makes sure this doesn't happen again :P

**Comment by jimrybarski** [comment]
The update has resolved the problem for all of the scenarios I posted about. Thanks!
