### ISSUE TITLE
Multiline support

### ISSUE THREAD

**Issue by revolter** [WoLpH/python-progressbar#93]
#### Description

Is there any possibility to add multiline support? So, for example, to have:

```
Updating stuff:
50% (2 of 4) |##########          |
```

?

#### Versions

- Python version: `3.6.0 (default, Dec 24 2016, 08:01:42)`
- Python distribution/environment: `brew install python3`
- Operating System: `macOS Sierra 10.12.1 (16B2555)`
- Package version: `3.12.0`

**Comment by WoLpH** [comment]
It's not completely impossible but it would be a lot of work to implement within the current system. I think you could fairly easily wrap the script in your own console writing library to enable this.

The big problem is that there's no simple way of rewriting lines on all platforms which makes this very difficult. We're rewriting a single line using the `\r` character right now and I believe the `\b` character might help in this case but I haven't been able to produce anything workable so far.

**Comment by WoLpH** [comment]
One option might be to use a library such as [reprint](https://github.com/Yinzo/reprint) for the multiline part and print the progressbar as you normally would.

**Comment by revolter** [comment]
Yeah, too much of a hassle, I'll close this for now.
