### ISSUE TITLE
FormatCustomText fixed width

### ISSUE THREAD

**Issue by revolter** [WoLpH/python-progressbar#94]
#### Description

Is there any way to set a fixed width for the `FormatCustomText`?

So if I want to print:

```
#1 Foo
#2 Longer foo
#3 Bar
```

it won't jump from 6 characters to 13 and 6 again.

I really thought that's what `min_width` argument is for, but it looks like it isn't.

#### Versions

- Python version: `3.6.0 (default, Dec 24 2016, 08:01:42)`
- Python distribution/environment: `brew install python3`
- Operating System: `macOS Sierra 10.12.1 (16B2555)`
- Package version: `3.12.0`

**Comment by WoLpH** [comment]
The min_width argument is to tell the progressbar when to show or hide the
widget. If there's not enough space it will hide the widget.

As for a fixed width, that should be part of the Python formatter api. For
example: %20s will force a minimum of 20 characters. By adding a - after
the % you can change the direction of the padding.

**Comment by revolter** [comment]
> The min_width argument is to tell the progressbar when to show or hide the
widget. If there's not enough space it will hide the widget.

Yeah, figured it out later, though it's pretty confusing.

Didn't know about `%20s`, works like a charm, thanks!
