### ISSUE TITLE
Remove unnecessary padding from SimpleProgress

### ISSUE THREAD

**Issue by revolter** [WoLpH/python-progressbar#95]
#### Description

Having `max_value=9`, the `SimpleProgress` gets printed as

```
(  4 of 9)
```

instead of

```
(4 of 9)
```

#### Versions

- Python version: `3.6.0 (default, Dec 24 2016, 08:01:42)`
- Python distribution/environment: `brew install python3`
- Operating System: `macOS Sierra 10.12.1 (16B2555)`
- Package version: `3.12.0`

**Comment by WoLpH** [comment]
That's actually somewhat intentional since the `9` can also be `N/A` (which is 2 characters longer, hence 2 spaces). I agree that it's not that pretty though, I'll fix it in a better way so at least the parentheses are part of the progress bar.

**Comment by revolter** [comment]
Didn't know about `N/A`. At least put the spaces outside, as you said: `  (4 of 9)` or even `  (12 of 1000)` instead of `(  12 of 1000)`.

**Comment by WoLpH** [comment]
It's fixed in the develop release :)
