### ISSUE TITLE
Updating bar with value > max_value

### ISSUE THREAD

**Issue by almcleanuk** [WoLpH/python-progressbar#97]
In applications that deal with RESTful web APIs I frequently come across situations where the code looks like the folowing.

- API call to get number of "items" available
- Loop over a series of API calls to get those "items" in batches

The problem is that if I use a progress bar to track progress, naïve code suffers from a race condition if the number of "things" available changes between the call to get their count and the calls to fetch them. 

This results in a lot of repetitious boilerplate code along the lines:

    if count <= max_value:
        bar.update(count)

It's easy to forget to include the guard, which results in annoying non-deterministic failures that are hard to catch in testing. 

**It would be nice if the library could (optionally) include logic to ignore updates outside the expected range.**

**Comment by WoLpH** [comment]
Ignoring values outside of the range is possible of course (although I'd recommend simply catching the exception in that case). But wouldn't it be better to dynamically update the max_value as required?

Simply do a `bar.max_value = ...` inside the loop and you should be safe :)

**Comment by almcleanuk** [comment]
That seems to work. Thanks.

Specifically my code now looks like this:

    bar = progressbar.ProgressBar(max_value=expected_count)

and then inside the loop

    if expected_count is not progressbar.UnknownLength:
        bar.max_value = max(expected_count, count)
    bar.update(count)
