### ISSUE TITLE
Items per second widget ?

### ISSUE THREAD

**Issue by jvhaarst** [WoLpH/python-progressbar#98]
It would be great if there was a simple way to add an items per second widget.
Right now I'm using the TransferSpeed widgets, but at high speed they start to divide by 1024 instead of 1000 to add the SI prefix.
(and B/s could be changed to i/s)

**Comment by WoLpH** [comment]
Good idea and not that hard to implement actually :)

It's on my todo list but might still take a while since I'm absolutely swamped with work at the moment.

If anyone is interested in helping, please go ahead!

**Comment by WoLpH** [comment]
I've just added an items per second widget in https://github.com/WoLpH/python-progressbar/tree/v3.16.0 :)

**Comment by jvhaarst** [comment]
Super !
